### ISSUE TITLE
Wrong ip for doorbell cam

### ISSUE THREAD

**Issue by theeddie** [briis/unifiprotect#100]
For some reason, the script is trying to contact protect for the doorbell cam on 10.0.30.1. instead of 10.0.0.1 like it does with the rest of the cameras

av.error.TimeoutError: [Errno 110] Operation timed out: 'rtsp://10.0.30.1:7447/CFtR4fnhFTbTHc2S'; last error log: [tcp] Connection to tcp://10.0.30.1:7447?timeout=5000000 failed: Operation timed out[0m | stdout
-- | --

**Comment by briis** [comment]
That is very strange. The IP address is supplied by the API itself. Is 10.0.30.1 an address you recognise? I mean is it pointing to anything Unifi related? Have you checked in the Unifi Protect AP, what address is under RTSP?

**Comment by theeddie** [comment]
Its my vlan for bad stuff,   I gave the doorbell a static ip and then removed the top rtsp and it started working..  I am sure its something on my end


But it works now feel free to close thanks

**Comment by briis** [comment]
Glad you found the solution. I will close
