### ISSUE TITLE
Feature request: Status light

### ISSUE THREAD

**Issue by ChrisRomp** [briis/unifiprotect#102]
It would be great if the camera status light only came on while recording, but it seems like it's always on or always off. I'm using HA to enable recording on some of my interior cameras only during certain times, and I would love to be able to have HA turn the camera status light on while recording so I can tell just by looking at the camera.

Thanks!

**Comment by ChrisRomp** [comment]
To clarify, my feature request is to have a switch in HA, not for the behavior of the recording switch to change.

**Comment by briis** [comment]
Makes sense. I will look in to the API to see what is possible.

**Comment by briis** [comment]
Hi Chris,
I have submitted a 0.5.6 Beta release, which you can download under releases. Could you test if that gives you what you want?

**Comment by ChrisRomp** [comment]
I'll check it out!

**Comment by ChrisRomp** [comment]
I tested the switch. Seems to do exactly what it's supposed to do. Thanks!

**Comment by briis** [comment]
You are welcome. I will close this now, and then I have a few more things to do before I release this officially.
