### ISSUE TITLE
Camera Stream is Delayed by 15 seconds +

### ISSUE THREAD

**Issue by JCandle** [briis/unifiprotect#103]
I just installed this over the weekend. I'm a new HA user as well. 

The stream on my Lovelace is delayed by about 15 seconds. 15 seconds is an eternity if you have kids or are trying to use the stream to monitor a front door. 

Everything I am using is up to date. Apparently this issue occurs with more than just me, see this Reddit thread. 

https://reddit.com/r/homeassistant/comments/ijah50/_/g3cteix/?context=1

**Comment by briis** [comment]
Unfortunately this is a known issue, which is not directly related to this integration. The issues is the way HA streams an RTSP stream, and lack of possibilities to tune paraeters on that stream. To get a Live stream from UI, there is only the option of a RTSP stream, and as such there is nothing I can do about it, until HA has more tweaking options on the stream component.

I just tried again by adding the RTSP stream to a Generic Camera component, and the delay might vary a few seconds, but it is still there.

So sorry, but for now this is the best I can deliver.

**Comment by JCandle** [comment]
> Unfortunately this is a known issue, which is not directly related to this integration. The issues is the way HA streams an RTSP stream, and lack of possibilities to tune paraeters on that stream. To get a Live stream from UI, there is only the option of a RTSP stream, and as such there is nothing I can do about it, until HA has more tweaking options on the stream component.
> 
> 
> 
> I just tried again by adding the RTSP stream to a Generic Camera component, and the delay might vary a few seconds, but it is still there.
> 
> 
> 
> So sorry, but for now this is the best I can deliver.

You don't need to apologize. You are awesome and I'm lucky to have you do all this work for me and the community. Thank you. Sorry I did not make that clear originally. 

It seems from that Reddit thread that it is not the case if you use other ways of integrating the cameras. I haven't tried it, but thought perhaps there was an opportunity there. 

Thank you again.

**Comment by briis** [comment]
Thanks. I looked at the Video you linked to, and the guy is not using Unifi Protect, but the older software called Unfi Video. And with that software you had the option of getting a stream that was not RTSP, so that is why it works better. But this software will not run on the new CloudKey+ or the YDMP on UNVR boxes.

We can hope that UI will make the external streaming more flexible in Unifi Protect, and/or we can tweak the HA stream feature more. I will definitly watch out for it.

**Comment by JCandle** [comment]
Thanks. How can I describe the issue on their community board to try to bring some attention to it?

________________________________

**Comment by briis** [comment]
Just tested HA 0.115, and there has been some work done to the `stream` component. It seems to be a bit faster, and then you now have Audio support also. It should be released late next week. It will not give you realtime stream, but hopefully it will be better.

**Comment by freemann** [comment]
I'm running 0.115.2 and still having 15-20 secs delay.
Initially after a restart it's ~5 secs, but after a few minutes its back at 15-20 secs.

@JCandle what did you do to only have 5 secs delay?

**Comment by JCandle** [comment]
> I'm running 0.115.2 and still having 15-20 secs delay.
> Initially after a restart it's ~5 secs, but after a few minutes its back at 15-20 secs.
> 
> @JCandle what did you do to only have 5 secs delay?

It seemed to last a few days then back to 15-20 seconds.

**Comment by briis** [comment]
With the rewrite to pure web socket on UnifiOS devices this is now down to around 10 sec. on the UDMP and CloudKey+ I am testing on. (Will be the 0.6.3 release) 
This will not come down further, unless we switch from using the RTSP stream, to making our own stream using ffmpeg. That might happen, but is not currently being worked on. (Streams are not my core competency)

I'll close this now.
