### ISSUE TITLE
Feature request: Create a service to push text to Doorbell 

### ISSUE THREAD

**Issue by papacrown** [briis/unifiprotect#104]
First off, thanks for the integration it's great. 

I don't know if it's possible, but it would be great if we could push text to the Doorbell screen. We can currently do this via the Unifi Protect app, but I don't know if it would be possible to do it via a Home Assistant Service? 

Thanks!

**Comment by briis** [comment]
The doorbell is unfortunately still not launched in Europe, so I don't have one myself. I am not sure exactly what you are asking for: What doorbell screen are you talking about? Looking at pictures the doorbell does not seem to have a screen, only a Mic and Camera? So what happens when you do this from the UI APP?
Just for me to get an idea what API stuff I should be looking for?

/B

**Comment by papacrown** [comment]
So basically the UVC G4 DOORBELL  has a small screen under the button, in the attached image you can see it says "Ready for Setup". 
![image](https://user-images.githubusercontent.com/22719066/92241083-42f99200-ee83-11ea-8539-5d22d7e94259.jpeg)

Here's a video clip ([https://streamable.com/mfxgnz](https://streamable.com/mfxgnz)) from the App, which shows what the interface looks like and that you can type custom messages. The icon to launch the message screen is the "T" in a box on the bottom right. Once you set this message, it'll appear on the Doorbell screen and make a chime, so you can effectively talk to whoever is at the door via this small screen.

**Comment by adrum** [comment]
@briis I also have interest in this, and can add the functionality to pyunifiprotect if you would like. I have a doorbell to test with.

**Comment by briis** [comment]
Hi Austin,
I would really appreciate this. And I saw you are already answered the Issue #4 on Github, so please go ahead.
I will release a new version a little later today to enable users to turn the LED lights on and off. But the current codebase in pyunifiprotect is now up to date.

**Comment by briis** [comment]
A very nice person from the US, shipped me a Doorbell, so I can now test on this also. And the first thing I did, was to add this feature to the Integration. See the release notes on how to use.
