### ISSUE TITLE
Possible to get a status sensor that monitors status of connection to CKG2 or cameras?

### ISSUE THREAD

**Issue by jayscovill** [briis/unifiprotect#105]
This would be useful since I've had a few instances where HA has lost the connection to the CKG2+ or cameras.  Would be great to know about it so we can trigger an automation to restart HA, etc.

**Comment by briis** [comment]
Hi @jayscovill 
There is already an attribute called `online` on each camera. This attribute is true if it is online in Unifi Protect. You could easy create an automation that checks this attribute and if it is false, send you a message or similar.
If your CKG2+ is unavailable the state of each camera will also be unavailable, so you could check for this also in an Automation.

Does this help, or is there something else you are looking for?

/B

**Comment by jayscovill** [comment]
You know, I didn't even think to check the camera attributes.  Was just looking for an entity.  If the state of the cameras truly reflects the state of HA communications with the CKG2+ then that would work nicely.  I'll test it out.

Thanks!

**Comment by briis** [comment]
The online attribute is updated every 60 seconds. I have honestly never testet it, but it should work. Let me know how it goes.

**Comment by briis** [comment]
From your reply, I see this is resolved, so I will close it.
