### ISSUE TITLE
device_tracker

### ISSUE THREAD

**Issue by mycanaletto** [briis/unifiprotect#110]
Hello,
Would it be possible to have a device_tracker based on the presence of the mobile application?

Thanks again and congratulations for this integration!

lionel

**Comment by briis** [comment]
Thanks for the kind works.
To answer your question, that is not possible. That information is not exposed in the Unifi Protect API as I have seen.
However if your are running the Unifi Controller, there is an integration for that built-in to Home Assistant. Look [here](https://www.home-assistant.io/integrations/unifi/)

**Comment by mycanaletto** [comment]
Just an idea... I am using Unifi integration...

**Comment by briis** [comment]
Out of curiosity: Why would you like to have this integration give you a device_tracker? What do you see the benefit would be, compared to just use one of the other available Device Trackers in HA?

**Comment by mycanaletto** [comment]
My idea was to compare, but I'm not sure if it's relevant...

**Comment by briis** [comment]
I think it's out of scope for this integration to make a device tracker, but thanks for the idea. Keep them coming. 

I will close this now.
