### ISSUE TITLE
What's the optimal card setup for a camera or doorbell?

### ISSUE THREAD

**Issue by MattPark** [briis/unifiprotect#114]
Nice work on this Bjarne!

What the best card setup here?  I'm assuming that at this point the 2-way talk stuff won't work.  Is there a way to deeplink to the camera in the unifi protect mobile app?

Here's the setup I have now for the doorbell and it works, not sure if I'm missing any of the functionality you have built in here. 

![image](https://user-images.githubusercontent.com/1690680/94947839-51e85a00-04ac-11eb-9cf4-e3292545daad.png)

**Comment by briis** [comment]
Hi Matt,
I guess the optimal Card is very individual, depending on what you want to show and do. But what you show above is the most detailed, with the current possibilities in Home Assistant. You are right, there is no Two-Way Audio at the moment, but as of 0.115, there is One-Way Audio at last. So when you do live streaming you can hear the Audio from the Camera. 

Some people have the Camera View setting, set to Live, to do a constant stream, but personally I never do that, as it puts to much strain on the system.

**Comment by MattPark** [comment]
Thanks Bjarne -- appreciate the response here.
