### ISSUE TITLE
Camera not refreshing if loosing connection

### ISSUE THREAD

**Issue by irgusite** [briis/unifiprotect#115]
Hi,

I've an UVC camera connected via a nanostation loco m2, but due to the positionning of the antennas, sometimes is looses connection for a couple of seconds. The thing is, when the connection drops and gets back up, protect is able to resume the stream, but the integration, looses the stream and keeps showing an old prefetched stream. To resolve it, I have to reload the integration.

Do you think, there is a solution for that? I don't know if the problem is the integration or the stream component of HA.

**Comment by briis** [comment]
In what Lovelace card are you showing the stream? 
What happens if you click on the image, will it start the stream?
Have you added `stream:` to your `configuration.yaml`?

**Comment by briis** [comment]
Just released 0.6.0, with better error handling. Please let me know if that gives you better stability.

**Comment by irgusite** [comment]
Hey, sorry for not answering, but I had some personal problems. 

Thank you for the update, I will test it and keep you noticed if it solved the problem or not :)

**Comment by briis** [comment]
Thanks, and no worries. I hope you are fine now.

**Comment by briis** [comment]
This topic has been idle for over a month, so I will close it. Please re-open if the problem persist.
