### ISSUE TITLE
Not possible to configure

### ISSUE THREAD

**Issue by propelhat** [briis/unifiprotect#117]
I've installed  Unifi Protect for Home Assistant from HACS, but it doesn't show up under Configuration -> Integrations?

**Comment by briis** [comment]
If you have restarted Home Assistant, this is typically a Browser caching issue. When you are on the *Integrations* page in your browser, try and do a Hard Refresh of the page, and it should show up.

**Comment by propelhat** [comment]
Hi Bjarne
Thanks for the input, but after doing that, I still can't configure. Do you have any other suggestions? I've even tried different browsers.

**Comment by briis** [comment]
So just to make sure that I know what you are doing:
* You have installed Unifi Protect from HACS, AND restarted Home Assistant?
* When HA is back up, you go to the *Configuration* page and then you click on *Integrations*?
* When you are on THIS page (Integration) you have done a Hard Refresh of the Browser?
* Then you clicked the + Button in the lower right corner, and search for *Unifi Protect*?

And even if you do all that, Unifi Protect still does not show up?

**Comment by rikdejong93** [comment]
Hi, i'm having similar issues. 
I've added the unifi protect repository and i can see it in the HACS integrations.
However, i dont have any settings to change. I cannot see any ''configuration'' button. 
Using the most recent versions of both Unifi Protect and HomeAssistant.

**Comment by briis** [comment]
Did you follow the steps outlined above?

**Comment by rikdejong93** [comment]
Yes. i've done the steps. and i went to incognito mode to see if that made any difference, but sadly it didnt.

**Comment by rikdejong93** [comment]
Wait, i did a second refresh and then it showed when i hit the +. My bad i guess :)

**Comment by briis** [comment]
Great. I don't know why it sometimes is so hard to get that cache cleared. 
Hope you can use the Integration.

**Comment by rikdejong93** [comment]
Yeah it works like a charm. Thanks for your effort!!

**Comment by propelhat** [comment]
I'm so sorry for your inconvenience.  It works now.

**Comment by briis** [comment]
Glad it works for both of you. I'll close this issue now.
