### ISSUE TITLE
Feature request: Service to enable/disable HDR

### ISSUE THREAD

**Issue by brun0san** [briis/unifiprotect#119]
Not sure this one is possible or not, but it would be great if there could be a service which would allow HDR to be enabled or disabled. I know HDR is available on the G4-PRO, not sure about other models.

The reason behind this is that I find the image looks significantly better with HDR enabled at night time, but not so much during the day. If such feature was available then an automation could be setup to enable/disable HDR depending on the time of the day.

Thanks and keep up the great work!

**Comment by briis** [comment]
I am not sure, but let me look in to the API, and see what can be done.

**Comment by briis** [comment]
I checked thru the API, and it is possible to make a service to enabled HDR. But I checked my cameras, and here is what I can see:
- G3 Flex: HDR is available
- G3 Micro: HDR is NOT available
- G4 Pro: HDR is NOT available
- G4 Doorbell: HDR is available

Do you see the same?

**Comment by brun0san** [comment]
It is available to be enabled/disabled from the web interface as well as the mobile app, but only on my G4-PRO, I also have a couple done G3’s which do not have this available.

**Comment by brun0san** [comment]
![Uploading 5FDD2625-308C-4B86-9ABB-773CCD934C46.jpeg…]()

**Comment by briis** [comment]
What version of Unifi Protect are you running. Below is a screenshot of my setup. The Camera is a G4 Pro, and I am running Unifi Protect 1.16.0-beta.2, with IOS App version 1.4.3, and here you cannot set HDR anymore. You can set the Video Mode to High Frame Rate mode.

![IMG_0045](https://user-images.githubusercontent.com/24776272/96461883-36f44480-1225-11eb-8ae2-b0b8e7732203.png)

**Comment by brun0san** [comment]
I’m running UniFi Protect v1.13.2, according to the change log v1.13.4 enables HDR by default so this may be the problem. I thought it was still possible to disable it, but from what you’re saying it doesn’t seems to be the case. Have you noticed any changes in image quality since you’ve updated? Does the web interface also removes the HDR option?

**Comment by briis** [comment]
It is possible to disable it also on this version, but not on the G4 Camera series, only on some of the G3 Cameras. With the G4 Series there is now a High Frame Rate option, that can be enabled or disabled, and that might have the same effect.

Honestly, it so long ago I went away from 1.13.x so I can't remember if there is a significant change in the image quality. I have however made two new services as you can see below, where you can play with this. It is not released yet, but you can download the following files from this repository, under *custom_components/unifiprotect* and then restart HA to test it out:

* `camera.py`
* `const.py`
* `manifest.json`
* `services.yaml`

And here is the description of the new services:

## Release 0.5.7 (NOT RELEASED YET)
* New feature: Turn HDR mode on or off, asked for in Issue #119. Only selected Cameras support HDR mode, but for those cameras that support it, you can now switch this on or off by calling the service: `unifiprotect.set_hdr_mode`. Please note that when you use this Service the stream will reset, so expect a drop out in the stream for a little while.
* New feature: Turn High FPS video mode on or off. The G4 Cameras support High FPS video mode. With this release there is now a service to turn this on or off. Call the service `unifiprotect.set_highfps_video_mode`.

**Comment by briis** [comment]
I have now released the features in V0.5.7. I cannot test it on a 1.13.x system, so I am not sure if it works for you. Closing the issue now.

**Comment by brun0san** [comment]
My apologies I couldn't test this earlier @briis, it's working as expected :)

Thanks for the quick turn around and keep up the great work.

Cheers.
