### ISSUE TITLE
0.5.7.: KeyError: 'videoMode'

### ISSUE THREAD

**Issue by tbloth** [briis/unifiprotect#122]
Hi!
I updated to 0.5.7 this morning after the release has been made available (from within HACS) and got following error.
I had to circle back to 0.5.6. and got it working again

2020-10-21 10:54:17 ERROR (MainThread) [custom_components.unifiprotect] Unexpected error fetching unifiprotect data: 'videoMode'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 131, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 94, in update
    await self._get_camera_list()
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 274, in _get_camera_list
    video_mode = str(camera["videoMode"])
KeyError: 'videoMode'

**Comment by briis** [comment]
What version of Unifi Protect are you running? If you are on 1.13.x, that might be the problem.
I'll need to figure out how to fix that.

**Comment by tbloth** [comment]
yeah, still 1.13.7 ... I'm still not seeing the 1.15 version

**Comment by briis** [comment]
I thought so. I assume you are on A CloudKey+ - The UDMP is V1.14.x and here this works. I will make some changes and release 0.5.8 Beta. Please test if this works for you when it is released.

For now I have pulled the 0.5.7 release.

**Comment by tbloth** [comment]
exactly, along with CK+

**Comment by briis** [comment]
There is now a 0.5.8-Beta release. You need to enable Beta releases in HACS to see this. I would be gratefull if you could test that you can run this release, and also if these services work on a 1.13.x system.

**Comment by tbloth** [comment]
will do. and once 1.15 comes in, I'll make that available, too!

**Comment by tbloth** [comment]
ok, 0.5.8-beta works. Does it include the two new (highfps and HDR) options, too? Can't see them

**Comment by briis** [comment]
Yes they are included. When you are on the *Developer Tools* and *Services* page, try and do a Hard Refresh in your browser, and they should show up as Services.

**Comment by tbloth** [comment]
I just read that it need >1.13.x
so it is not in my environment

**Comment by briis** [comment]
The Services should still be there. The `videoMode` error you saw is related to the High FPS service, which you cannot use, but you might be able to use the On/off for HDR Service. And if you have a Doorbell, you should also be able to use that new service.

**Comment by tbloth** [comment]
nope, it's not there - using a G4Pro

**Comment by briis** [comment]
So if you go to the Services page under Developer Tools, you can't find a service called `unifiprotect.set_doorbell_lcd_message` ?

**Comment by tbloth** [comment]
oh wait, I was mistaken. I didn't look into the services page. I was looking for an according state.
Yes, it's there

**Comment by tbloth** [comment]
in fact I was thinking it will be like a switch, like what you have for activating IR for example

**Comment by briis** [comment]
Ahh. No I believe most of these services will be used in Automations, so we don't need a switch. I don't want to flood peoples entities with a lot of new things they don't use.
Calling a service is very easy in automations, so I decided on that approach.

**Comment by briis** [comment]
Closing this now. Expect a new release 0.5.8 latest tomorrow
