### ISSUE TITLE
HACS install: 404 at repository install on git/trees/v0.5.7 missing

### ISSUE THREAD

**Issue by sparks3875392** [briis/unifiprotect#123]
Thank you for this excellent integration. I updated to the latest version and get this error at install of the repository:

2020-10-21 11:23:03 ERROR (MainThread) [custom_components.hacs.api.repository] GitHub returned 404 for https://api.github.com/repos/briis/unifiprotect/git/trees/v0.5.7

**Comment by briis** [comment]
Yes, a user reported a critical error, so I had to pull it back. There is 0.5.8 Beta version available. And if all goes well I will release 0.5.8 later today.

**Comment by briis** [comment]
FYI, I will hold this a day or two, as I want to add a few other things also.

**Comment by briis** [comment]
Closing this. Expect 0.5.8 tomorrow the latest
