### ISSUE TITLE
Use websocket to insert motion flag

### ISSUE THREAD

**Issue by mcondren** [briis/unifiprotect#127]
I just saw that websocket support has been merged. Thank you! 
Can this feature be used to allow the integration to remotely ‘insert’ motion flags for cameras?  I have tensorflow running outside protect, since the motion detection in protect itself is so bad. Would love for HA to be able to insert a motion flag in the timeline of a camera when it detects a Person. Would make it so much easier than comparing time stamps between tensor flow and protect to try and find motion clips. You can jump right to motion flags in protect. In wouldn’t even mind if it was super accurate.

**Comment by briis** [comment]
I am not sure exactly what you would like. Is it an Attribute on the Camera itself, that holds the timestamp? Please describe the scenario.

**Comment by mcondren** [comment]
Apologies, let me try to be more clear. It is entirely possible that this isn’t doable (with websockets or otherwise). If so, feel free to close. 

**Scenario:**
-Some external tensorflow, blue iris, or any other third party stream analysis software watching the rtsp feeds from protect detects a person on the rtsp feed for camera X. 
-now HA knows that there is a person on camera X at time stamp Y. 
-I would like the ability for HA to ‘push’ that motion event into the protect timeline for that camera. 
-I can now go to that camera timeline in protect and click the motion button in the timeline view to see just the motion events and jump to them. Protect adds these motion flags to the camera timelines by default when a camera detects motion, to make those clips easier to find without scrubbing through the whole feed until you see something. 

My assumption is that there is an internal command that protect uses to insert these flags. What I am looking for is the ability to remotely insert these flags on a per camera basis given the args ‘camera’ and ‘time stamp’. 

Does that make sense?

**Comment by mcondren** [comment]
So I’m looking to push motion info into protect like you do when you change settings values. Rather than pull info out.

**Comment by briis** [comment]
Yes, now it makes sense and I understand what you want. I will need to a bit of testing on this, but don't get your hopes up. I found that there is only a certain amount of things that can be changed through the API, and I am not sure this is one of them.
I'll keep it open for now, and once I am done with the final changes for the 0.6.0 release, I will start testing.

**Comment by mcondren** [comment]
Thanks. Much appreciated.

**Comment by briis** [comment]
I have been looking through this again, and it is not possible to do that. UI is also now implementing their own Smart Detection, so that you can filter on these events in the timeline - only getting events where a person or a vehicle is detected. It does require the G4 series cameras to work and Protect V1.17.x or greater.

So I will close this now.
