### ISSUE TITLE
Camera does not show.

### ISSUE THREAD

**Issue by christian1986** [briis/unifiprotect#134]
For some reason, my cameras no longer show. I reinstalled the component and restarted but still nothing. Ideas?

![image](https://user-images.githubusercontent.com/4373980/97708655-6d4d8180-1ab9-11eb-8823-e39cf0997122.png)

![image](https://user-images.githubusercontent.com/4373980/97708784-9e2db680-1ab9-11eb-81e0-1af17b3a5426.png)

Newest version of unifi protect plug in and home-assistant.

**Comment by briis** [comment]
What version of Unifi Protect are are you running, and what HW?

**Comment by christian1986** [comment]
Unifi Dream Machine Pro - Version: 1.8.0

Unifi Protect - Version: 1.15.0

**Comment by briis** [comment]
Is there nothing in the log files?

If not, remove the Integration, try and add this to your configuration.yaml, restart HA, and try and add the Integration again. The look in the log file:

```yaml
logger:
  default: error
  logs:
    custom_components.unifiprotect: debug
````

**Comment by pironic** [comment]
I'm experiencing the same issue but enabling the debug logs on unifiprotect only output:
`2020-11-02 16:05:01 DEBUG (MainThread) [custom_components.unifiprotect] Connect to Unfi Protect`

no errors...

**Comment by pironic** [comment]
hmm... i did notice that the permissions options have changed on the UDM-Pro... i no longer see an option to grant access to a user to protect. odd. will investigate further and edit this comment if i find anything
![image](https://user-images.githubusercontent.com/541154/97929576-b8b89780-1d26-11eb-8c61-71d16485451b.png)

**Comment by briis** [comment]
Glad to hear it works now @pironic 
@christian1986 could you check if the same works for you?

**Comment by christian1986** [comment]
Same thing here. Changed the permission to administrator for the unifi protect and now it works.

**Comment by briis** [comment]
Fantastic. Glad it was that "little" thing. I'll close this now.
