### ISSUE TITLE
Doesn't show up when trying to add to integrations

### ISSUE THREAD

**Issue by madrobby** [briis/unifiprotect#136]
The README states that "This Integration is part of the default HACS store. Search for unifi protect under Integrations and install from there.".

I don't see it there. The only thing for "Unifi" that shows up is "Ubiquity UniFi". Is there a way to manually install the integration? 

I'm running Home Assistant on a Synology NAS, latest docker image, v0.117.1.

Thanks!

**Comment by briis** [comment]
You have to install it through HACS before it will show up on the Integration page. Have you installed HACS? https://hacs.xyz/

**Comment by madrobby** [comment]
In fact, I have not. Maybe add "if you don't know what HACS is, you probably need to install it" to the README with link to it. :) I'm new to this. Thank you!

**Comment by briis** [comment]
You are right, I should be a bit more specific. 
Absolutely no problem. 

Once you have it installed through HACS and restarted then refresh your browser when you are on the Integration page to make sure it shows up.
