### ISSUE TITLE
Onboarding screens wording needs udating now UnifiOS is available for Cloudkey

### ISSUE THREAD

**Issue by B-Hartley** [briis/unifiprotect#138]
Hi,

The integration confi flow screens say......

For Cloudkey use port 7443
for UDM Pro use port 443.

It would probably be more appropriate now to say:
Cloudkey version up to x - 7443
Cloudkey versions over x - 443

Or UnifiOS - 443

Or something like that?

Thanks

**Comment by briis** [comment]
You are right. I just discovered a few hours ago, that UnifiOS was now available for CloudKey. I will rework the README file ASAP.

**Comment by briis** [comment]
Done. README is already updated and Config Flow will have the new text on the next release (0.6.2)
Thank you for pointing this out.
