### ISSUE TITLE
UniFi OS for Cloud Keys in beta

### ISSUE THREAD

**Issue by eh8** [briis/unifiprotect#140]
[Ubiquiti has released a beta build of Unifi OS for the Cloud Key Gen 2s.](https://community.ui.com/releases/UniFi-Cloud-Key-Firmware-2-0-18/86571d09-9b02-4de7-9422-fd0d584cecea)

Since upgrading I have been able to load my Cloud Key Gen 2 Plus with this plugin. I have tried setting the port to be 443 and double-checked that my user permissions were set up properly, and everything worked.

Please let this be a confirmation that UniFi OS is working properly for Cloud Keys.

**Comment by briis** [comment]
I assume you got it working since you closed it?

**Comment by eh8** [comment]
Yes, I just wanted to document this receipt of a functional setup.
