### ISSUE TITLE
Migrating between Protect -> UnifiOS Protect

### ISSUE THREAD

**Issue by suiciety** [briis/unifiprotect#141]
I couldn't see it specifically in the instructions but now that UNifiOS is supported on CloudKey + does this integration automatically detect that and switch over to the new Webhook communication method when you migrate?

Or do you need to remove/re-install this integration to take advantage?

Cheers

**Comment by briis** [comment]
We have no way to check that you have migrated, so this is a manual process. The fastest is to to what @bdraco suggests in [this post](https://community.home-assistant.io/t/custom-component-unifi-protect/158041/348).

Alternate option is to delete the Integration, and then set it up again, using port 443.

**Comment by briis** [comment]
I will close this now. Please reopen if you still need help.
