### ISSUE TITLE
Error retrieving data from Unifi Protect

### ISSUE THREAD

**Issue by tomnz** [briis/unifiprotect#142]
I'm having trouble running through the integration config flow, and it's not super clear to me what's going wrong...

* I've installed 0.6.2 of `unifiprotect` through HACS.
* My UDM Pro is configured with a new local user who has administrative access to Protect.
* When running the config flow (port 443, IP/user/password all correct), I get the "Error retrieving data from Unifi Protect" message.

I've enabled debug logging for the integration, but the only messages I see are as follows:

```
2020-11-16 13:58:29 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Request url: https://192.168.1.1:443
2020-11-16 13:58:29 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] 200 text/html <ClientResponse(https://192.168.1.1:443) [200 OK]>
2020-11-16 13:58:29 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: True
2020-11-16 13:58:29 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Request url: https://192.168.1.1:443/api/auth/login
2020-11-16 13:58:29 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] 200 application/json <ClientResponse(https://192.168.1.1:443/api/auth/login) [200 OK]>
2020-11-16 13:58:29 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Authenticated successfully!
```

So it _seems_ like things are working, but I'm still getting the error. Any ideas?

**Comment by jonjon1123** [comment]
I am also experiencing this issue. Below are my logs. It looks like it authenticates successfully, but then has a problem as this line: `Fetching Unique ID failed: 500 - Reason: Internal Server Error`.
```
2020-11-19 08:14:08 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Request url: https://192.168.1.1:443
2020-11-19 08:14:08 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] 200 text/html <ClientResponse(https://192.168.1.1:443) [200 OK]>
<CIMultiDictProxy('Vary': 'Origin', 'X-DNS-Prefetch-Control': 'off', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Accept-Ranges': 'bytes', 'X-CSRF-Token': 'f2cf544a-fd16-4b9a-afe6-54147ce24d86', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '357', 'X-Response-Time': '9ms', 'Set-Cookie': 'TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmVG9rZW4iOiJmMmNmNTQ0YS1mZDE2LTRiOWEtYWZlNi01NDE0N2NlMjRkODYiLCJpYXQiOjE2MDU3OTUyNDgsImV4cCI6MTYwNTc5ODg0OH0.O5QnkoX_IzofpJU-QOrW1vO2JhahCucc-2TirJSuzfQ; path=/; secure; httponly', 'Date': 'Thu, 19 Nov 2020 14:14:08 GMT', 'Connection': 'keep-alive')>

2020-11-19 08:14:08 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: True
2020-11-19 08:14:08 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Request url: https://192.168.1.1:443/api/auth/login
2020-11-19 08:14:08 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] 200 application/json <ClientResponse(https://192.168.1.1:443/api/auth/login) [200 OK]>
<CIMultiDictProxy('Vary': 'Origin', 'X-DNS-Prefetch-Control': 'off', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Accept-Ranges': 'bytes', 'X-CSRF-Token': '2cbe471b-d85e-4da1-8971-dd30933d6beb', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '2457', 'X-Response-Time': '197ms', 'Set-Cookie': 'TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmVG9rZW4iOiIyY2JlNDcxYi1kODVlLTRkYTEtODk3MS1kZDMwOTMzZDZiZWIiLCJ1c2VySWQiOiJhMDZjYmNlOC0yNDEwLTQzZmItODNjNy1jNDliM2YyZWU5ZjIiLCJpYXQiOjE2MDU3OTUyNDgsImV4cCI6MTYwNTc5ODg0OH0.NYD4-d_INK9RbIOvoTIqTZ-HdylkW88zMlBEL0YEcZY; path=/; secure; httponly', 'Date': 'Thu, 19 Nov 2020 14:14:08 GMT', 'Connection': 'keep-alive')>

2020-11-19 08:14:08 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Authenticated successfully!
2020-11-19 08:14:08 DEBUG (MainThread) [custom_components.unifiprotect.config_flow] Fetching Unique ID failed: 500 - Reason: Internal Server Error
```

**Comment by tomnz** [comment]
Ahh I wasn't logging `custom_components.unifiprotect.config_flow` - I see the same 500 error message that you do when turning on that debug log.

I [pulled my UDM's support file](https://help.ui.com/hc/en-us/articles/360049956374-UniFi-UDM-Dream-Machine-Support-File-and-Logs) and in `unifi-core/errors.log` I see:

```2020-11-19T21:44:01.240Z - error: [https] 56ms 500 GET /proxy/protect/api/bootstrap```

Unfortunately I can't find anything more enlightening than that. I'm new to digging around in the UDM itself though - if there is additional config to increase the log verbosity or something let me know!

**Comment by briis** [comment]
The Internal Server Error 500 is a collective status code for server errors, so the UnifiOS device is reporting some sort of error, without being very specific. It happens when we try to pull some information about the UnifiOS device, that is used throughout the Integration - but unfortunately the device only returns a generic error 500.

I have not been able on any of my Unifi Protect devices to force this error, so it is hard to say what happens at your end.

One thing you could try, is to look directly in the Unifi protect error log, right after this happens. So if you try to go through the setup again, and you then get the error, please do the following:

1. ssh in to your UnifiOS device - typically the command will be `ssh root@ip_address`
2. Capture the file: `/srv/unifi-protect/logs/errors.log` 
3. Post the result here. (If it is a big file, please see if you can scrape only the relevant parts)

**Comment by jonjon1123** [comment]
So this is kinda embarrassing, but the fix for me was to reboot my UDM Pro after I added the user just for use in viewing cameras in UnifiOS. :) I looked at errors.log and nothing was being reported as an exception or error.

**Comment by tomnz** [comment]
I had to reset a couple times and deactivate/reactivate the user, but this also ended up working for me. Maybe worth adding a reset step to the instructions? Not sure if anyone else runs into this though. Closing the issue.

**Comment by briis** [comment]
Glad you both got it working.

**Comment by cumulosec** [comment]
I just wanted to comment I had this same issue and a reboot of my UDMP solved my issue. So maybe this should make it into the documentation to restart the UDMP after creating local user.

**Comment by Hengjie** [comment]
@ghost I have the same problem but are you all hosting home assistant locally as a podman container on the UDMP?

**Comment by briis** [comment]
I am not hosting Home Assistant on my UDMP, it runs on an Intel NUC with Debian on.
Are you running it directly on the UDMP?

**Comment by Hengjie** [comment]
> I am not hosting Home Assistant on my UDMP, it runs on an Intel NUC with Debian on.
> Are you running it directly on the UDMP?

Yes, I'm running it directly on my UDMP. However, I'm able to curl 192.168.1.1 fine. Could it be hitting the wrong path? Because when I log into my UDMP using my browser on 192.168.1.1, network logs show it uses `https://192.168.1.1/api/auth/login` on port 443, but the above config flow says it calls `https://192.168.1.1:443/api/auth` instead. I'm running the latest version of your integration on HA.

**Comment by briis** [comment]
I honestly don't know what you need to do. This is an untested and unsupported scenario, so I cannot help. The code is open source, so feel free to try out different things. If you get it working, please post it here, as other might benefit.

**Comment by Hengjie** [comment]
> I honestly don't know what you need to do. This is an untested and unsupported scenario, so I cannot help. The code is open source, so feel free to try out different things. If you get it working, please post it here, as other might benefit.

Could you ssh into your UDMP, run my above curl command and tell me if you see the csrf header?

**Comment by briis** [comment]
Just tried it and I get the exact same output as you showed above.
