### ISSUE TITLE
[FR] Adding new switch to disable recording

### ISSUE THREAD

**Issue by robinostlund** [briis/unifiprotect#143]
Hi,
Love your plugin, but would it be possible to add a switch that sets When To Record -> Never?

This would help out in some automations i need.

Thanks

**Comment by briis** [comment]
Thanks. 
There are two switches that switch off or on Recording mode. One for Motion and one for Always. If you switch off both of those, recording is 'Never'. What specifically would you like the new switch to do, that you cannot do now?

**Comment by robinostlund** [comment]
Ahaa oright that will work for me :) haven't even tried to disable both, so we can close this issue :)
