### ISSUE TITLE
Re-added integration but G4 Doorbell picture glance card not working

### ISSUE THREAD

**Issue by jayscovill** [briis/unifiprotect#144]
I recently had to factory reset my G4 doorbell and set it up again.  It appears in Unifi Protect with no problems.  

I removed and reinstalled the Unifi Protect integration and it's creating my camera entities fine.

 I have a couple of G3 dome and bullet cams that are showing in Lovelace just fine. But for some reason the G4 Doorbell won't display using a Picture Glance or Picture Entity card. All I get is a blank card saying "recording". So I'm thinking it has something to do with me having factory reset it and re-added to Protect. 

Yet it's showing in Protect and the camera entity is being created by the integration.  But it just won't show the video feed.

I'm running Hassio .118.2 and Protect 1.16.3-beta.2.  Any ideas about what I can do to get it back showing a feed in a Picture Entity or Picture Glance card?

**Comment by briis** [comment]
Could you check if the RTSP stream is enabled on the Camera? (See the README on how to do that)

**Comment by jayscovill** [comment]
Should add that G4 also doesn't show a recording status (Record Motion vs Record Always)

**Comment by jayscovill** [comment]
Oh man, I totally forgot about re-enabling RSTP!  Thanks, that was part of the problem.  I at least get the camera feed now when I click on the picture entity card...Still having a problem with the feed showing up in the picture entity card though.  Have tried re-adding the integration and restarting HA.

**Comment by jayscovill** [comment]
Ok, I fixed that problem by switching the camera view from Auto to Live even though my other cameras are set to auto and work fine.

**Comment by briis** [comment]
Just to check. Could you go to the Integrations page, and click on the devices within the Unifi Protect Integration. Then check that you don't have the Doorbell twice.

**Comment by jayscovill** [comment]
Only showing up once...also just noticed that for some reason the picture entity card for the camera is still showing a stream from last night.

**Comment by briis** [comment]
I am out of ideas, except for trying to restart your Protect device.

**Comment by jayscovill** [comment]
I figured it out.  When I reset the camera I forgot to go to it and enable anonymous snapshots!  All better now.  Thanks!

**Comment by briis** [comment]
I will close this now, as it seems your issue has been closed.
