### ISSUE TITLE
Error while setting up unifiprotect platform for sensor after v.0.6.3 upgrade

### ISSUE THREAD

**Issue by koldogut** [briis/unifiprotect#145]
As stated above, I'm getting this error after v.0.6.3 upgrade

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/unifiprotect/sensor.py", line 32, in async_setup_entry
    sensors.append(UnifiProtectSensor(upv_object, protect_data, camera, sensor))
  File "/config/custom_components/unifiprotect/sensor.py", line 45, in __init__
    super().__init__(upv_object, protect_data, camera_id, sensor)
  File "/config/custom_components/unifiprotect/entity.py", line 23, in __init__
    self._server_id = self._camera_data["server_id"]
KeyError: 'server_id'`

It was working like a charm before the upgrade, any ideas??

Thank you in advance

**Comment by datascope11** [comment]
Received this error (I think it was this one) as well after the most recent update. I have 3 Unifi cams that have been working flawlessly prior using this component. Issue now seems to be with the binary_sensor.motion_xxx - they do not report motion since the update (3 days ago now for me).

**Comment by briis** [comment]
Could you both tell me what version of Unifi Protect you are running, and on what HW UFP is running

**Comment by datascope11** [comment]
I'm running 1.14.11 on UDMP. Haven't updated anything in my Unifi stack for a while now, too afraid from what I read to bork a working install. Only things updated on were HA 118 and a couple of components (including this one).

**Comment by AntonShevchuk** [comment]
The same problem after update.
Home Assistant 0.118.3
UCK-G2-PLUS Controller 1.13.7

**Comment by briis** [comment]
So this seems. to be a problem with NON UnifiOS Devices. Unfortunately my backup CloudKey is already upgraded, so I will see if I can downgrade it again, to test this.

Until then I recommend you install the 0.6.2 release.

**Comment by datascope11** [comment]
I think I'm running UnifiOS on my UDMP, at least I believe it's included since 1.5 or something on UDMP. Running 1.8.0

**Comment by briis** [comment]
Yes you are on UnifiOS - all UDMP units are.
The latest version of Unifi Protect is 1.16.7, so your Unifi Protect version is might be too old, for some of the new things we pull from the API. You could try and restart your Unifi protect software, I have reports from other users that that has helped them.

**Comment by AntonShevchuk** [comment]
@briis sorry for off-topic - how I can upgrade CloudKey to UnifiOS?

**Comment by datascope11** [comment]
Thanks. I've restarted Protect and will see if motion detection comes back into the sensor. If not, I'll give the Protect update a whirl.

**Comment by monsieurlatte** [comment]
I'm going to add something, I'm too on 1.15 which is the latest offered to us on the UDMP build of protect.  However I want to add, I am now getting what appear motion sensor alerts from the doorbell sensor.  I can't narrow it down but in HA I have a trigger that when binary_sensor.doorbell_front_door triggers it alerts me through Alexa.  Last night (a couple hours after I updated my repo to the latest build), it was triggering even though no one was pushing the button.  I wasn't getting the push alert through the unifi app either.  So it seems it's confusing or combining push button with motion.  Just my .02

**Comment by datascope11** [comment]
No dice on the restart of Protect. Getting motion notifications via Protect app, but they are not carrying over to the binary sensor in HA.

**Comment by briis** [comment]
@AntonShevchuk: In order to upgrade your CloudKey+ to UnifiOS, you need to be on the Beta Channel. If you are not part of that, [look here](https://help.ui.com/hc/en-us/articles/204908664-How-To-Sign-Up-for-Early-Access). Then there are upgrade instructions [here](https://community.ui.com/releases/UniFi-Cloud-Key-Firmware-2-0-20/da2226fb-ee8f-4ce4-98dc-aae9effca4d1) (Release 2.0.20).

**Comment by briis** [comment]
@Others: Unfortunately Ubiquiti releases FW so often, that it is impossible for us to test against all versions. Once my UDMP and CloudKey+ are upgraded, that is the versions that are being testet against, and that might create backwards compatibility issues. The API changes with almost every new FW release, but it is not documented by Ubiquiti, so it is often hard to tell exactly what has changed.
Going forward I need to ensure that it is document what versions of the UI FW this has been testet against, so at least you know where it will work. 

Currently my setup is UDMP with FW 1.8.3-4 and Unifi Protect V1.16.7. With this combination everything works as expected. It is also tested against CloudKey+ with Unifi Protect 2.0.19. 

If you cannot upgrade to the latest release of the Protect Software, I recommend for now to go back to 0.6.2, which you all indicated was working for you, while we look at the issues.

**Comment by koldogut** [comment]
> Could you both tell me what version of Unifi Protect you are running, and on what HW UFP is running

UDM PRO FW ver 1.8.0 and Protect ver 1.15. I'll try to update to ver 1.8.3-4 and 1.16.7 today and come back to you asap.

**Comment by briis** [comment]
@koldogut Looking forward to your response. Note: UDMP FW 1.8.3-4 comes bundled with 1.16.7, so you only have to do ONE upgrade.

**Comment by briis** [comment]
I managed to roll my spare CloudKey+ back to FW V1.1.13 and Unifi Protect to V1.13.37, and I can confirm that Motion Detection is not working. We will look in to that.

**Comment by briis** [comment]
For those of you who are still on a CloudKey+ with FW 1.x, I believe I have found a fix for the motion sensors not working.
Could you try and download the [`binary_sensor.py`](https://github.com/briis/unifiprotect/blob/master/custom_components/unifiprotect/binary_sensor.py) and replace the one you have in your `custom_components/unifiprotect` and then restart HA.

**Comment by koldogut** [comment]
> @koldogut Looking forward to your response. Note: UDMP FW 1.8.3-4 comes bundled with 1.16.7, so you only have to do ONE upgrade.

I must say that despite the error everything seems to be working fine in ver 1.8.0; motion is triggered and streams works nice. Once updated to 1.8.3 I'll confirm if the error is gone.

**Comment by datascope11** [comment]
Agreed, all is working very smooth besides the motion sensor!
Thanks for the potential solutions. I think the most important part will be documenting which versions of this component work with what versions of Protect. 
The prescribed upgrade path here for UDMP FW 1.8.3-4 is a beta release, as is Protect 1.16.7. I have not traditionally be super comfortable jumping on the Unifi Beta train, it can be a shaky unstable train. I personally prefer to wait for general stable releases, given the uptime requirements I have on my network. I'm sure it's difficult with this component to support a bunch of FW versions, especially if Protect's API is constantly changing. 

I have to imagine most users are on stable releases of UnifiOS/Protect, and not the beta path. 
Appreciate all your work on this!

**Comment by briis** [comment]
Hi @datascope11 
I fully respect that people stay on the official releases. I have been burnt too, by running the Beta releases. In an ideal world I had a few devices with different FW versions to test on, but unfortunately that is not how it works in the real world.
But when we want to support new developments by Ubiquiti, at least I need to run the latest Beta, to see what they bring, and thus, this is where development and testing occurs.

I managed to downgrade my old CloudKey+, so I will let that follow the official release path. Hopefully, that will soon be a V2.x release, so that it is UnfiOS all over the place.

I will make sure for future release to document what they have been testet on, so at least people can make their own decision if they should risk upgrading.

**Comment by datascope11** [comment]
Can confirm, replacing the binary_sensor.py as you mentioned above works for Protect 1.14.11 running on UDMP v 1.18.0
Motion sensors back up and running.
Thanks

**Comment by briis** [comment]
WONDERFULL - The error was related to SmartDetection, which the UDMP with your version does not yet have. And the same for the CloudKey with V1.13.x.

**Comment by monsieurlatte** [comment]
@briis Just wanted to say, I rolled back to 0.6.2 and my false motion alerts (the ones that are being triggered on the doorbell, have disappeared.   I'm on a UDMP 1.8.0 running protect 1.15. I know you say you can't reproduce it, just letting you know.

**Comment by briis** [comment]
@monsieurlatte I. believe you are suffering from the same issue as datascope11. The version of FW and Unifi Protect, you are running does not support SmartDetection and that might be the cause of the issue. When I release 0.6.4 I suggest you try and install it, and see if this fixes the problem.

But glad the previous version works for you.

**Comment by monsieurlatte** [comment]
All good, just letting you know, so grateful for your work on this ❤️

**Comment by koldogut** [comment]
I can confirm that upgrade to 1.8.3 (beta) removes the error. thank you @briis for this brilliant work

**Comment by briis** [comment]
@koldogut Super. And if you have any G4 series cameras, you will also now have Person detection in Home Assistant, with these, as this is supported in this FW version.

**Comment by koldogut** [comment]
Not yet, but I have a really good integration of this custom-component with the robmarkcole's HASS-Deepstack-object for person and faces recognition (you both should talk if didn't yet ), working like a charm so far with 6 cameras (G3 Pro and Flex) after the latest updates.

**Comment by briis** [comment]
I while ago I did try the Deepstack, but couldn't really get it to work (I didn't try very hard), but with your comments I will give another go. Protect can do basic Person detection, but I would really like Face Detection, which I assume robmarkcole's component can do.

**Comment by briis** [comment]
I have just released 0.6.4 which I believe fixes the issues discussed here. If you find that things are still not working, please open a new issue.

**Comment by briis** [comment]
Just another note: On my test system I just experienced the same error as @koldogut mentioned in the first post of this issue:
`self._server_id = self._camera_data["server_id"] KeyError: 'server_id'`

It happened upon restart of HA, and was gone after a new restart. The error is related to us pulling some Server related data, during startup, and that routine either fails or is delayed. As I have only seen it once, it is a bit hard to debug, but I'll keep my eyes on it.
Fix seems to be to restart HA.
