### ISSUE TITLE
[FR] - Doorbell Button notification

### ISSUE THREAD

**Issue by jaburges** [briis/unifiprotect#149]
Hi there, 
Firstly thank you - love this component! 

I have the G4 doorbell (and have to say although its expensive with the Cloud Key Gen2+ i'm very impressed)

Is there a way to parse the doorbell push to a webhook or MQTT message?

**Comment by briis** [comment]
Glad you can use it.
There are no plans to add either MQTT or webhook push in to this integration, but it is still doable directly from Home Assistant.

You can. create an automation that triggers on doorbell push and then send of a MQTT message of your liking. Look at the documentation for the [MQTT Publish Service](https://www.home-assistant.io/docs/mqtt/service/) on how to that.

**Comment by jaburges** [comment]
awesome, i clearly didnt read all the docs - there is a binary_sensor for the doorbell
You hero!
