### ISSUE TITLE
Bug? G4 Doorbell binary sensor fires on disconnect/reconnect

### ISSUE THREAD

**Issue by lightbody** [briis/unifiprotect#151]
First off: I'm loving the progress you've been making on this project. Things have gotten *really* nice and because of this project I took the plunge and upgraded to the CKG2+ UnifiOS beta and I'm really pleased with the results.

The one small issue I've got going on right now is that my G4 Doorbell, while a bit more reliably after tweaking some wifi settings, still disconnects/reconnects every few days. And I worry that as the weather gets colder, it may happen more (I've heard about temperature being a potential problem).

The issue here is that I've wired up a NodeRed flow that looks for `binary_sensor.doorbell_front_door` firing and then tells my kitchen and bedroom Sonos to yell out "Ring ring ring ring!". It works great, except... at 3am when the doorbell disconnects and I significantly erode my wife's confidence in our home automation system 🤣 And then when it fires a second time a few minutes later, on reconnect, it really solidifies her opinion.

Any chance you could _not_ fire the doorbell trigger when the camera disconnects and reconnects? Or fire a different event?

Thanks!

**Comment by briis** [comment]
Great to hear that you enjoy it.
Did you upgrade to V0.6.6? Because we thought we had fixed exactly that problem in the 0.6.6 release?

**Comment by lightbody** [comment]
Oops, nope. I was on 0.6.4. Trying out 0.6.6 right now and will report back.

**Comment by lightbody** [comment]
Confirmed. Thank you!
