### ISSUE TITLE
Can't find UNVR

### ISSUE THREAD

**Issue by Calimerorulez** [briis/unifiprotect#156]
Hi!

I've tried everything, but I can't seem to make the integration find my UNVR (running firmware 1.3.33/Protect 1.17). Running Dockerized HA  0.118.5.

I have followed the steps, created an admin user, enabled streams, but I do not know how to add my UNVR.

Any suggestions? :)

**Comment by briis** [comment]
Just to check:
- You installed the Integration (via HACS or Manual) and restarted Home Assistant
- You then. went to the *Settings* menu and the selected *Integrations*
- Then you clicked the + button in the lower right corner, and searched for *Unifi Protect*
- And it is after filling out the form here presented with your UNVR data, that it does not work. Is that it?

Did you get an error message?

**Comment by Calimerorulez** [comment]
Hi @briis,

- Yes
- Yes
- Yes
- No, I'm not presented with a form...

I have cleared my browser cache, used Chrome and Edge, but no luck...

**Comment by briis** [comment]
When you are on the Integrations page, try and do a Hard Refresh of your browser.
Then click the button in the bottom right corner *+ Add Integration*
You should then be presented with a search menu where you type Unifi Protect. This should show the below - if not, either you have a caching issue or the Integration has not been properly installed
![Screenshot 2020-12-10 at 09 02 20](https://user-images.githubusercontent.com/24776272/101738701-d23bc480-3ac6-11eb-8f76-d665720e9f66.png)

Then select Unifi Protect and you should see this:
![Screenshot 2020-12-10 at 09 02 50](https://user-images.githubusercontent.com/24776272/101738762-eaabdf00-3ac6-11eb-8bbc-fc2bb2e2250c.png)

**Comment by Calimerorulez** [comment]
Hi,

I only get the screen in your first screenshot, I can add the integration, but without the option to enter the UNVR details, and then it asks me to restart HA. Please see my images below:

![unvr](https://user-images.githubusercontent.com/1130552/101815997-b49b4900-3b20-11eb-9112-d0d5e712e797.png)

![unvr2](https://user-images.githubusercontent.com/1130552/101816253-16f44980-3b21-11eb-93ea-a7ec2a761cf6.png)

![unvr3](https://user-images.githubusercontent.com/1130552/101816260-1a87d080-3b21-11eb-96b2-2dde8d877489.png)

![unvr5](https://user-images.githubusercontent.com/1130552/101816287-207db180-3b21-11eb-97e9-9551a0903427.png)

![unvr6](https://user-images.githubusercontent.com/1130552/101816502-620e5c80-3b21-11eb-9116-52d88426cb3a.png)

**Comment by briis** [comment]
The above is a screenshot from HACS, which is only a community store to Install Integrations like the Unifi Protect Integration. Of the steps I outlined earlier, you are now done with step 1 below. After restart you now need to do step 2 and 3.
1. You installed the Integration (via HACS or Manual) and restarted Home Assistant
2. Go to the Settings menu and then select Integrations (You find the *Settings* menu in the lower left bar.)
3. Make a Hard refresh when you are on the Integrations. page and then click the + button in the lower right corner, and searched for Unifi Protect

**Comment by Calimerorulez** [comment]
Oh my gosh, I feel real stupid now :( 

I can configure the integration now. Sorry for bothering you, and thank you for your detailed help/explaination!
