### ISSUE TITLE
Icons for Doorbell messages?

### ISSUE THREAD

**Issue by Flight777** [briis/unifiprotect#157]
Not sure if it's possible yet, but the default Unifi message for Packages, has a nice package icon in the message as well. Are we also able to put icons in messages? :)

**Comment by briis** [comment]
The default messages are available in the API, but only the text portion, so it seams that the icons are added when selecting the default texts.
The only way I can think of to do this, would be to send a unicode character that contains a symbol - but for that to work I need to figure what font they are using or where they get the symbols from.
I have tried sending a basic unicode string to the doorbell, but that does not get translated to a symbol.

**Comment by briis** [comment]
Hi @Flight777 
I did some more digging, and by examine the feed that comes from the Doorbell, I can se that the icon is actually a SVG files that is hardcoded in to the system. It adds a lot of html stuff around it, that I cannot inject directly. So currently this is unfortunately not possible.
Closing it now.
