### ISSUE TITLE
Feature Request: Audio Sensitivity

### ISSUE THREAD

**Issue by ChrisRomp** [briis/unifiprotect#158]
I'd like to be able to automate whether my cameras are recording audio or not. UniFi Protect has a "microphone sensitivity" slider under the camera settings, and turning it all the way down appears to effectively disable audio recording.

Is there a possibility of exposing this in HA?

**Comment by briis** [comment]
I will look in to the API, and see if it can be done.

**Comment by briis** [comment]
I had some time this morning, so this is now implemented. Update to release 0.6.7, which I just released. If it is as you expected, please close the issue.

**Comment by ChrisRomp** [comment]
Seems to work great!  Thank you!
