### ISSUE TITLE
DeprecationWarnings: verify_ssl is deprecated

### ISSUE THREAD

**Issue by copperek** [briis/unifiprotect#160]
with version home assistant 2020.12.0. I see the following deprecation warnings:
_/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py:356: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead response = await self.req.get(_

**Comment by briis** [comment]
Closed in release 0.7.0
