### ISSUE TITLE
Integration broken after CloudKey FW update

### ISSUE THREAD

**Issue by TroLoos** [briis/unifiprotect#168]
Hi, it seems like the newest Cloud Key firmware update changes access paths to UniFi Controller. It worked flawlessly until the recent update...

Right now I have UniFi-CloudKey-Gen2-Plus with 2.0.24 firmware installed, Protect version installed is 1.16.9.

Before the most recent update I used to access my Protect via https://IP_ADDRESS:SOME_PORT, right now it looks like it changed to https://IP_ADDRESS/protect/dashboard. It also changed Controller access path to https://IP_ADDRESS/network/site/SITE_NAME/dashboard.

Did anyone else noticed this breaking change?

**Comment by gregcohen** [comment]
I'm having the same issue... wish I hadn't updated to the new firmware since it broke the integration, but it's nice to have the people detection!

**Comment by briis** [comment]
When upgrading to 2.x FW, your devices are. now a UnifiOS device, and with that comes a change in the Port number. You go from 7443 to 443. The quick fix is what @bdraco suggests in [this post](https://community.home-assistant.io/t/custom-component-unifi-protect/158041/348?u=briis), or you can delete the Integration and add it again, specifying 443 as port.

Please try that.

**Comment by TroLoos** [comment]
> When upgrading to 2.x FW, your devices are. now a UnifiOS device, and with that comes a change in the Port number. You go from 7443 to 443. The quick fix is what @bdraco suggests in [this post](https://community.home-assistant.io/t/custom-component-unifi-protect/158041/348?u=briis), or you can delete the Integration and add it again, specifying 443 as port.
> 
> Please try that.

So simple, working like a charm again :-). Thanks!

**Comment by briis** [comment]
@gregcohen Did this work for you also?

**Comment by gregcohen** [comment]
Thanks, @briis , I changed the port to 443 and it was perfect. Thanks!

**Comment by chris-erickson** [comment]
Took me a long time to pull this all together so for future people, you can edit the config using the terminal (I use the flashed SD card method for HA setup)

This is where you change the port from 7443 -> 443
```
nano config/.storage/core.config_entries
```
Then restart HA, and reset the HomeKit camera entities using Developer Tools -> Services
```
Service: homekit.reset_accessory
Entity: <your camera entity>
```
I think the last step is needed so HomeKit gets the new address where it should look for the video feed.
