### ISSUE TITLE
Cameras not discovered (2021.1.2 bug?)

### ISSUE THREAD

**Issue by holman** [briis/unifiprotect#179]
Noticed all my camera picture entity cards were broken today. Not entirely surprising (it's a home network; everything breaks, haha). All of the camera entities 

I rebooted my UDM Pro, and then for good measure I removed the unifiprotect integration and re-added it. It correctly finds my UDM Pro and offers to add it to an area, like usual, but that's all it seems to do. The main integration only shows "1 device" and no entities (cameras, switches, etc.)

I point out 2021.1.2 just because I know that's when I first discovered there was a problem after clicking around post-upgrade (as well as it apparently fixing some sort of custom integration vulnerability?) But it could be something else as well (new Protect update I didn't notice happen?) <strike>I'm seeing this on two different sites, too; same problem.</strike> (edit: everything does show up fine after re-adding the integration on site number two, which is on a Cloud Key 2.) Nothing showing up in the error log, either.

**Comment by holman** [comment]
Ahhhhhh nevermind! I am, as you might imagine, an idiot. Apparently the permissions on my local user weren't entirely correct (in which case... not sure how they got changed!)

Added the appropriate Protect permissions for the user and we're good to go again. Sorry for the time!

**Comment by briis** [comment]
I have had one other using reporting this, did you by any chance activate 2FA on your Ubiquiti Account?

**Comment by holman** [comment]
Oooh, yes I did. That’s been one of the only recent changes I’be made.

**Comment by briis** [comment]
It seems Ubiquiti does something to the Local Users when you do that, so I think this is the reason for the change in permissions, as this was exactly the same that happened to the other user.
