### ISSUE TITLE
G3 Flex Unavailable

### ISSUE THREAD

**Issue by rlust** [briis/unifiprotect#186]
I have two G3 Flex cameras. One of them that was working now comes up unavailable, other one is working.
Any ideas on where to look?

**Comment by briis** [comment]
Please start looking in the UniFi Protect APP, or Protect Web App. Is the camera available there?

**Comment by thomas70** [comment]
Same here. After i upgraded the Cloud Key Gen2 yesterday it seems that all is running on port 443, Both protect and the wlan controller.

**Comment by rlust** [comment]
During the unavailable issue my Protect app were working fine. I removed the HASSIO Protect integration and re installed. Now so far it is working fine.

Thanks for the help!

**Comment by thomas70** [comment]
uninstall/install worked for me too

**Comment by briis** [comment]
Seems that it is working now, so I will close this.
