### ISSUE TITLE
Separate Access to Various Types of Motion

### ISSUE THREAD

**Issue by taylorlightfoot** [briis/unifiprotect#187]
It appears that motion detection in Home Assistant for a Unifi Protect camera is triggered by any of these three items:  Motion, Smart detection of person, Smart detection of vehicle.  

I would love to have separate access to each motion type.  For example, I want my doorbells to not use IR at night because I can better identify cars and their colors with it turned off.  But I would love to set up an automation to turn on the IR if a person is detected, since they're difficult to see at night with IR turned off.

**Comment by briis** [comment]
You have access to all these settings from HA. What is it specific you are missing?

**Comment by taylorlightfoot** [comment]
I believe the integration only gives two states for motion: "detected motion" and "cleared (no motion detected)"

I would like either different motion sensors for each type of motion, or keep one sensor and be more specific in the state to indicate what caused the motion.  I'm looking to turn on the IR lights, but only when the motion detected is a person, not motion from a car detected or motion from non car/non person.

**Comment by briis** [comment]
As your doorbell supports Smart Detection, you can check for the `event_object` attribute. That will contain either `person` or `vehicle` if this is what is detected. Here is an example of a trigger in an automation that only fires if a person is detected:

```yaml
trigger:
  - platform: state
    entity_id: binary_sensor.motion_doorbell
    to: person
    attribute: event_object
```

**Comment by taylorlightfoot** [comment]
Oh wow, I feel dumb overlooking that, but I do see it now.  This is great.  if Ubiquiti add smart detections for additional object types, would they automatically show up as well in the event_object attribute?  or would you have to add support for new objects?  

I'm excited to try out the automation i have in mind.  Thank you so much for your work on this integration, it has been one of my favorites for Home Assistant.

**Comment by briis** [comment]
If they continue as they do now, it will turn-up automatically. This also happened when they added vehicle as object type. I look in a specific array in the API, where they store this.

Thank for the kind words, appreciate it.

**Comment by taylorlightfoot** [comment]
I got it working and it works just how I envisioned.  Thank you for your help and sorry for the erroneous issue submission.
