### ISSUE TITLE
Unifi Access - Feature Request

### ISSUE THREAD

**Issue by Dodoooh** [briis/unifiprotect#188]
hello I love this integration. I wanted to ask if there is a possibility to direct your interest to a newer product from Unifi > [Unifi Access. ](https://store.ui.com/collections/unifi-door-access/products/unifi-access-starter-kit)

I've had this setup up and running for some time now and would love to integrate it with HomeAssistant. 
( doorbell, user presence, states ect.)

Unfortunately I haven't found out anything regarding API, however I can't find one for Protect either. Any idea where to find this? 

If there is interest I like to share log's, source code ect. with you. But I would need to know what exactly you need.

**Comment by briis** [comment]
I am aware of that product line, and it looks interesting, even for Private Homes.

All API's from Ubiquiti are un-documented, so it is always reverse engineering to figure out what is going on - this is also the way we find the features in Protect.

When you look at your CloudKey+ or UDMP, you see that Ubiquiti has a separate product for the Controller, Protect, Access and Talk and in HA there is currently support for Controller and Protect. So I don't believe that Access should be integrated in this product, but rather have its own Integration. Then the beauty of HA is that you can integrate the different parts in automations, scripts etc.

I would love to look at making that Integration, but without any of the HW available, it will be close to impossible to do, even if you could send me some dumps, logs etc. As we need to reverse engineer this, I would need to have access to HW. It is available in Europe, but a Starter kit would cost me 424 EUR plus VAT and that is a bit much for a product that I currently have only a limited use case for.

So I am sorry, but this will not be part of this Integration, but I promise that if I get my hands on the HW one day, I will look at making an Integration.

**Comment by briis** [comment]
I will close this issue, as this will not be built-in here. If I get my hands on the Hardware, I will see if we can make a Unifi Access Integration.
