### ISSUE TITLE
Make a standard home assistant component

### ISSUE THREAD

**Issue by frankhommers** [briis/unifiprotect#19]
What is needed to make this component a standard (non custom) home assistant component?

### For 0.11
- [x] select & other cleanups https://github.com/briis/unifiprotect/pull/346
- [x] Remove mention of non-unifios from config flow (Should just be changing the text) https://github.com/briis/unifiprotect/pull/349
- [x] raise `ConfigEntryAuthFailed` and Reauth flow (https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#reauthentication) https://github.com/briis/unifiprotect/pull/350
- [x] Remove username/password from options flow (after reauth implemented) https://github.com/briis/unifiprotect/pull/350

### After 0.11 / part of core merge (will likely be breaking changes)
- [x] Remove `extra_state_attributes` that are also sensor/binary_sensor from `camera.py` (audit for any duplicate extra_state_attributes and remove) https://github.com/briis/unifiprotect/pull/414
- [x] Remove `ATTR_DEVICE_MODEL` from `entity.py` `extra_state_attributes` since its duplicated in the device registry https://github.com/briis/unifiprotect/pull/414
- [x] Drop custom services that overlap with the select entities https://github.com/briis/unifiprotect/pull/414
- [x] Remove `_async_fire_events` from `binary_sensor.py` (duplicate functionality with state change event) https://github.com/briis/unifiprotect/pull/414
- [x] Config Flow Tests

**Comment by briis** [comment]
Eventually it would be great to have this implemented as a standard Integration. I honestly don't know what it would take, but would love some advice, from a person who knows. 
Do I need to adjust this so that it can be installed from the *Integrations* section in HA? I think I could do that, but what the process then is, I don't know. (It might be in the DEV docs I guess). 

Where the Integration is at this stage, I think that I would like to keep it as is. When you make an Official Integration, updates gets a lot more restricted, and as I don't think we are done yet, it is much easier to distribute new features and bug fixes through HACS.

**Comment by bdraco** [comment]
@briis Feel free to reach out and ping me if you need help.  I've opened a few issues for 0.4.0.  If you make a PR to your master I'm happy to run though and do a more exhaustive review of items that would be an issue merging into `core`.

**Comment by briis** [comment]
Hi @bdraco,
Thanks for all the great suggestions, which I have implemented. (Still have a few questions which you can see in the issues).
I am totally self-taught on Python, and I am still trying to learn, so even though I would love to get this in to `core` I get a bit spooked about all the things I need to do. But if you can help, I would love to give it a shot. I guess first thing is to do a good review of the code-base, and ensure it conforms to the requirements of `core`. So if you can do that, I would appreciate it.

**Comment by bdraco** [comment]
@briis I've opened up issues for the things that stood out as issues that would come up on a PR to core.  Its by no means an exhaustive list, and I can do another pass once everything is sorted out.  Things are is much better shape than a lot of the PRs I see to core so 👍

**Comment by briis** [comment]
Thanks @bdraco 
I will start working my way through your suggestions - I really appreciate it, and I learn a lot at the same time. Thx.

**Comment by christian1986** [comment]
Any news on this:)?

**Comment by briis** [comment]
With the help of many people I think the component is more or less ready to be a core Integration. I just don't know where to start this. I know it has to run through a Test Environment, but I don't know where to start on this. So this is really whats keeping me from not doing it. But I will see if I can find some time to dig through documentation, and start the process.

**Comment by dsabella84** [comment]
@briis I would love to help you get this integrated as a standard integration.  Have you looked into the integration documentation at all yet?

**Comment by briis** [comment]
Hi @dsabella84 
That would definitely be appreciated. I have only glimsed through the documentation, as I decided not to do it before I thought I had a more or less 'finished' version. I find it easier to make changes that way. I would still love to convert it to a push model, but I guess I could start on the Core Integration. 
@bdraco already helped me a lot, and according to him, the code should be almost ready.

How would you suggest to proceed?

**Comment by dsabella84** [comment]
I was going to run it through a branch and perform some testing on it.  Ill let you know if i run into any issues.

Any assistance with the push model approach you were thinking?

**Comment by briis** [comment]
That sounds great, looking forward to hear how that plays out.

With regards to the push model, I had some writing forth and back with the author of the Homebridge Unifi Protect Plugin, and he has done it all. He documented it also as you can see from this topic: https://github.com/briis/pyunifiprotect/issues/4#issuecomment-688916500, he even fixed the issue I have with the stream not being realtime.

So my thoughts were first to implement all this in the [IO module](https://github.com/briis/pyunifiprotect) and then adjust this component to take advantage of the events being pushed instead of pulled. I am totally self taught on Python, and I feel this is over my head, and therefore I am not really sure how to start.

**Comment by NVader2000** [comment]
+1

**Comment by ChadGnad** [comment]
+2

**Comment by briis** [comment]
One day it will be. Currently there are still a lot of new stuff that needs to be added, combined with the constant changes in the underlying API, that makes it faster and easier to handle outside the Core HA cycle.

**Comment by AngellusMortis** [comment]
Added the TODO list that @bdraco made in a seperate issue since we are actively tracking / working on getting the integration merged into HA core.

**Comment by AngellusMortis** [comment]
Just realized I have not posted an update here yet. We are well on our way to merging `unifiprotect` into HA core. We should hopefully have everything in the 2022.2 release of HA core. We already have the `camera`, `media_player` and `button` platforms merged in. That leaves `light`, `number`, `sensor`, `binary_sensor` and the extra misc. services. The largest part was the initial PR and tests though, so I expect to easily do 2+ platforms between now and the release of 2022.2 beta to make sure we get them all in.

Also, the 0.12.0-beta is available as the last version of the HACS version. It has all of the deprecations removed from the 0.11.x release as well as a number of bugfixes we discovered as part of the HA core merge.

**Comment by AngellusMortis** [comment]
Migration is officially complete! 0.12.0-beta9 is now officially on par with the version that is in HA Core. It will be available in 2022.2.0.

Steps to migrate:

1. Upgrade to the latest 0.11.x release or the latest 0.12.0-beta release for the HACS `unifiprotect` integration and restart Home Assistant.
1. Upgrade to Home Assistant 2022.2.x
1. Remove your HACS `unifiprotect` integration and restart Home Assistant. It is safe to ignore the warning about needing to remove your config first.
