### ISSUE TITLE
Feature Request - Camera luminance exposed as sensor

### ISSUE THREAD

**Issue by johntdyer** [briis/unifiprotect#198]
It would be amazing for a sensor for each camera showing the luminance of the camera.  I'd love to be able to use that for automation triggers based brightness in the area the camera is placed.  I am not sure if the API exposes that data but figured I'd ask

**Comment by briis** [comment]
Unfortunately Luminance or any other brightness value is exposed in the API. The only thing that is there is a parameter `IsDark` which I assume the Camera uses to switch IR on. I have not done testing on this, to see if it actually uses some kind of brightness sensor, or it is simply sunset/sunrise that determines if this parameter is true or false.

**Comment by briis** [comment]
As this cannot be done, I am closing the issue.
