### ISSUE TITLE
Entity created for cameras without status light

### ISSUE THREAD

**Issue by ZuluWhiskey** [briis/unifiprotect#200]
I have two G3 Bullet cameras and the integration has created status light switch entities for them. I tried using the switches and saw nothing on the camera, a quick Google showed that they don't have this feature (I think the G4 does though).

Obviously I can disable the entities but thought I'd raise an issue in case this was something that was fixable within the integration itself?

**Comment by briis** [comment]
Hi there,
Are you sure about this? I don't have a G3 Bullet camera, but I have a G3 Flex, and this has a little blue light on the front that indicates if it is adopted - this can be turned off by the this switch, as you can turn it off in the Protect App. This is what the switch does for G3 Cameras.

I know for G4 Pro's this is a lot more obvious as this has a big blue ring.

**Comment by ZuluWhiskey** [comment]
> Hi there,
> 
> Are you sure about this? I don't have a G3 Bullet camera, but I have a G3 Flex, and this has a little blue light on the front that indicates if it is adopted - this can be turned off by the this switch, as you can turn it off in the Protect App. This is what the switch does for G3 Cameras.
> 
> 
> 
> I know for G4 Pro's this is a lot more obvious as this has a big blue ring. 

I can't find any documentation that shows the light and I've found a couple of posts online where people (granted not representatives of UniFi) have said that the cameras don't have the status light. I've looked at pictures on the documentation and also online and can't see the status light referenced anywhere either.

Oddly though, I've looked into it more and there is a toggle for the status light in the UI, but I have found [a post from 9 months ago in the UniFi forums](https://community.ui.com/questions/Unifi-G3-Pro-Status-Light-Not-working/c664d623-ac56-4fe3-8418-198f5d9050ba) where UniFi acknowledged that the G3 Pro doesn't have the status light and it will be removed from the UI. Obviously this isn't the bullet either so isn't conclusive but the cameras are very similar! 

Sounds like a UniFi issue at the moment, so perhaps once they remove it from the UI it'll remove the switch from your integration 👍

**Comment by briis** [comment]
I once had a G3 Bullet (Not PRO) and that had the little led light, but as you say the PRO does not. There is a Flag in the API that checks for that, but as long as it is in the Protect APP, then I am positive it will still say True, it just does nothing. For now, you can disable the switch so it does not show up in Lovelace, and then let me know when you see the feature go away in the Protect APP, then I can make a modification to the module.

**Comment by ZuluWhiskey** [comment]
> I once had a G3 Bullet (Not PRO) and that had the little led light, but as you say the PRO does not. There is a Flag in the API that checks for that, but as long as it is in the Protect APP, then I am positive it will still say True, it just does nothing. For now, you can disable the switch so it does not show up in Lovelace, and then let me know when you see the feature go away in the Protect APP, then I can make a modification to the module.

I'll be completely honest, my G3 Bullets are high up so I'm unable to inspect it closely - Hence me trying to Google / search online. I'll close this as, as you say, if it is an issue then it sits with UniFi and not yourself 👍
Thanks for creating such a useful integration 😃
