### ISSUE TITLE
After the 2021.3.x the 'live' setting makes the camera go blank

### ISSUE THREAD

**Issue by fribse** [briis/unifiprotect#203]
I have both unifi and nest camera integration activated.
I only have 1 nest, the video doorbell, so I wouldn't know if this applies to other nest cameras.

I have the camera showing like this:
```
type: picture-entity
entity: camera.indgang
camera_image: camera.indgang
show_name: false
show_state: false
```
If I add
`camera_view: live`

It goes black, and doesn't show anything.

**Comment by fribse** [comment]
I'm not sure if this relates to the problem, looking in the log the only one I find that could be close to anything with this is this one:

 Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:130
Integration: Stream (documentation, issues)
First occurred: 7. marts 2021 17.30.45 (212 occurrences)
Last logged: 09.29.31
Error opening stream: rtsps://stream-eu1-charlie.dropcam.com:443/sdm_live_stream/CiQA2vuxr0SUhyOWYql5O57CGtwWIckN52XZRuos3[...]

**Comment by briis** [comment]
There have been some issues reported with the stream component and live view, but I currently have no issues with the Unifi Protect Integration. 

@fribse Is the camera you refer to above a Unifi Camera or the Nest camera? When I look at *charlie.dropcam.com:443/sdm_live_stream/CiQA2vuxr0SUhyOWYql5O57CGtwWIckN52XZRuos3[...]* that you posted above, I am positive this has nothing to do with Unifi Protect.

**Comment by fribse** [comment]
Darned, sorry Bjarne, I was looking in your github to see if you had solved it, and I was meaning to post it in the nest integration github, sorry, just ignore me :-)
