### ISSUE TITLE
The device is disabled by Config entry.

### ISSUE THREAD

**Issue by lowrisk75** [briis/unifiprotect#207]
I'm new to HA, so pretty sure is something I did but I have an issue today with my G4 PRO 

The device is disabled by Config entry (when I click on the device), that's weird because on my Dashboard I can see the live feed no problem.

Also when it was working, and I was in the device>automatisation, I had nothing for on person detection (which I can do with other Netatmo onsite) is this an expected behaviour or a bad configuration from myself?

I'm running the last HA version with the official image/Raspberry Pi 4, I manually added the "stream: inside the configuration file as following :
`stream: rtsps://unifiIP:7441/JDGJH35434hs?enableSrtp`

**Comment by briis** [comment]
If I read this right you are not using the Unifi Protect Integration, you have just added the camera directly using the RTSP stream. Is that correct? If yes, please ask in the community, as this is only about the Unofficial Unifi Protect Integration.

**Comment by lowrisk75** [comment]
I did add the  Unofficial Unifi Protect Integration HACS, but in the Wiki (I might misunderstood, English is not my primary language) "Before you restart Home Assistant, make sure that the stream component is enabled. Open configuration.yaml and look for stream:. If not found add stream: somewhere in the file and save it."
so as I didn't see, I manually added + the RTSPS link I got from UniFi Protect.
I still can see the stream, and button on my dash example :
Record Always UVC G4 Pri, MOtion UVC - C4 PRO which I think is from the custom integration
(seems like I have an issue with the time server though as it's indicate uptime 2671 weeks ago

**Comment by briis** [comment]
OK, you did it a bit wrong. The only thing you need to have in your `configuration.yaml` file is this line: `stream:` nothing about the cameras. After you made that edit, restart Home Assistant.

Before you configure Unifi Protect in Home Assistant be sure that you have created a local user with administrative rights, as described [here](https://github.com/briis/unifiprotect#prerequisites)

Once you have created the local user,  follow the [Configuration](https://github.com/briis/unifiprotect#configuration) section in the README file, that should add all your cameras to Home Assistant.

**Comment by lowrisk75** [comment]
Thank you, it's back to normal, It's probably the stream: line alright.

Just for information when I click on configuration>device>UVC G4 PRO>Automations, I have "Motion UVC G4 Pro is detecting motion" but I have no specific detection events like I have with the Netatmo Pro (e.g on Person detection / on car detection...) just to be sure is that an expected behaviour ?

I read in the README file "AUTOMATE PERSON DETECTION" about a script (again I'm new to Home Assistant) is that suppose to go  in the configuration file too? anyway I'm getting off topic I'll play around and find a way

**Comment by briis** [comment]
For all the G4 Cameras you have the option of enabling Smart Detection, that then only triggers when a Person or Vehicle is detected. There will a switch created for each Camera called `switch.record_smart_CAMERA_NAME`. If you active that for a camera, the camera will enabled smart detection. Then you have a binary sensor also for each camera named `binary_sensor.motion_CAMERA_NAME`. If you look at that sensor in the developer tools, you can see it has an attribute called `event_object` That will tell you if a person or vehicle has been detected. Hope this helps a little.

There is a lot of help to get in the Community Forum, if you need help with automations and such. Here is a [link to the post about this Integration](https://community.home-assistant.io/t/custom-component-unifi-protect/158041)

**Comment by lowrisk75** [comment]
thanks a lot
