### ISSUE TITLE
record on motion switch resets motion events settings

### ISSUE THREAD

**Issue by squirtbrnr** [briis/unifiprotect#210]
I have an automation that toggles the record on motion and record always switches based on device trackers and time of day.  I have also used the switch by itself.  Every time I do, the motion events settings for the camera as viewed from the UniFi Protect webpage is reset to the defaults.  There are no errors or notices in the logs for HA.  I don't know where on my UDM-Pro or UniFi Protect to look for logs, but let me know If you need more debug logging.

UDM-Pro - firmware 1.9.0
UniFi Protect - version 1.17.4
HA - docker 2021.3.4
UniFi Protect custom component - v0.8.3

My camera motion events settings are:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/35356217/111409312-b2f39b00-86a4-11eb-9faf-5d43c53d5b6e.png">

After toggling the switch it reverts to:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/35356217/111409423-e9c9b100-86a4-11eb-8852-388348736814.png">

**Comment by squirtbrnr** [comment]
this also happens using the built in set recording mode service of the component.

**Comment by briis** [comment]
I can confirm that I can replicate this. I will see what can be done.

**Comment by briis** [comment]
Made a quick fix. To test it out, could you modify the `manifest.json` file in the unifiprotect directory and change this line:

```json
"requirements": [
    "pyunifiprotect==0.29.2"
  ],
```
to this:
```json
"requirements": [
    "pyunifiprotect==0.30.1"
  ],
```
Then restart Home Assistant, and let me know if this works.

**Comment by squirtbrnr** [comment]
it's working with that change.  the motion events settings stay as they were after toggling the record on motion and record always switches.

**Comment by briis** [comment]
You are welcome. I will soon send out a new release where this will be included. I will close this issue now.
