### ISSUE TITLE
Feature request: Change chime on G4 doorbell

### ISSUE THREAD

**Issue by mohlek** [briis/unifiprotect#211]
It would be nice to have the ability to change the chime on the g4 doorbell.

I'd like to have an automation which disables the chime at night so that I only receive push notification.

Currently I don't see a fitting file to add the code and I don't want to mess up the code base.
So if you can give me a few hints where to add the code I would take a look and try to implement it on my own.

**Comment by briis** [comment]
I am not absolutely sure this can be controlled from the API, but I will look in to it.

**Comment by briis** [comment]
I did some checking and I found a way to stop the attached Mechanical or Digital Chime to stop sounding. (Or almost, if I listen carefully it still makes a microsecond of sound, but not something I believe you could hear when sleeping).

The Protect App will still sound if you set that up, I cannot stop that. Would this help your use case?

**Comment by mohlek** [comment]
Yeah that would absolutely do what I want.

If I set the chime via protect ui to none there is no sound. Not even for a microsecond. Is this the same property?

**Comment by briis** [comment]
I assume you mean the below setting in the APP? And no this is not it, that can not be manipulated in the API, and if you read the text below, there is a warning to set it correctly due to power usage. What I do is set the Chime Duration to 0, to turn it off, and then set it back to default (300) to enable it again.

<img width="388" alt="Skærmbillede 2021-03-20 kl  18 59 46" src="https://user-images.githubusercontent.com/24776272/111881000-cfe2e380-89ae-11eb-9101-0cfe3d696b38.png">

**Comment by mohlek** [comment]
fyi
https://github.com/briis/pyunifiprotect/commit/ebfdfa2b5d4ac991377bc9cef0f9173b53abe9c7#r48513025

**Comment by mohlek** [comment]
https://github.com/briis/unifiprotect/pull/212
https://github.com/briis/unifiprotect/pull/213

**Comment by slootjes** [comment]
Nice work! When will v0.8.5 be tagged? Excited to try it :)

**Comment by briis** [comment]
Thanks. I am planning to release this with the next day or two.

**Comment by slootjes** [comment]
Awesome, thanks!

**Comment by mohlek** [comment]
how is the release doing? 😄

**Comment by briis** [comment]
I got caught up in another project, and totally forgot to release it. Will do it now 😄

**Comment by briis** [comment]
RELEASED!!!! 0.8.5
