### ISSUE TITLE
Snapshot live view mode option

### ISSUE THREAD

**Issue by houshasen** [briis/unifiprotect#214]
I just learned that HomeSeer uses Snapshots for their live view. It is seen as ultra-low frame rate live view but the benefit there I saw is instantaneous. RTSP (at least on my current setup) sometimes take 10+ seconds to load. Even when it loads, the contents are lagging may be 10+ seconds of real live.

So I hope there is some options to user how Camera Entity interface on Lovelace UI and Live streaming up on clicking the tile:

1. Snapshot successive captures for both live and entity tile
2. Snapshot successive capture for entity tile. Live stream using RTSP.
3. Keep current static image for entity tile. Live stream using snap shot succession.

**Comment by briis** [comment]
In your configuration.yaml file you have a line called `stream:` If you remove this line, the live streaming will be done exactly as you describe above, and you are right, this gives less latency. The only downside is that you loose Audio, but if you don't need that, just remove or comment out the `stream:` line.

Let me know if this does what you want.

**Comment by houshasen** [comment]
> In your configuration.yaml file you have a line called `stream:` If you remove this line, the live streaming will be done exactly as you describe above, and you are right, this gives less latency. The only downside is that you loose Audio, but if you don't need that, just remove or comment out the `stream:` line.
> 
> Let me know if this does what you want.

Thank you for very quick reply. I do not see the stream option in my configuration.yaml. Can they be hiding elsewhere?

**Comment by briis** [comment]
No, I don't believe it can.
Another suggestion is to go to the Unifi Protect Web APP, and on each Camera, turn of the RTSP Stream in all resolutions. Then restart Home Assistant, and see if that helps.
I have noticed that sometimes Unifi Protect turns RSTP back-on by itself, so just check that after you have turned it off. If that is the case then this is not a solution. Else I will look at a programatic approach.

**Comment by houshasen** [comment]
I can confirm turning off RTSP DOES work i.e. LIVE view is successive
snapshots identical to HomeSeer.

I know it is probably not the highest priority for many, but I hope this
would be optional setup from the Plugin side rather than turning of RTSP
because RTSP has its own spots.
1. Use in other tools.
2. Sounds

So ideally, I hope one can set Live view to RTSP vs. Snapshots by clicking
some toggle on the fly like right upper corner little icon RTSP <->
Snapshots but if this is too hard, I'd at least hope from entity advanced
configuration where we have the toggle says RTSP stream ON/OFF perhaps with
some explanation (RTSP provides audio and smooth video but lagging) vs.
Snapshots real time but no audio and extremely low frame rates.

Thank you

**Comment by briis** [comment]
I will put it in as an option when setting up the Integration.

**Comment by houshasen** [comment]
Thank you! That would be great.

**Comment by briis** [comment]
This is now done, and will be part of the next release. I could not make an "on the fly" solution, but from the Configure Menu on the Integration, you can now disable RTSP for all Cameras.

**Comment by houshasen** [comment]
That’s fantastic. Looking forward to it.

**Comment by briis** [comment]
Btw. there is a Pull Request on the HA Core, for the Stream component, that might lower the delay significantly. I have not had any chance to test it, but it looks promising. If all goes well that should be in the 2021.6 release - but the change is significantly, so it might be later or NOT.

**Comment by houshasen** [comment]
Working as intended. Thank you!
