### ISSUE TITLE
ClientSession is being leaked on setup retry/auth failure

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#217]
If the integration fails to setup we need to manually close the client session created from 
`async_create_clientsession` before returning/raising

**Comment by bdraco** [comment]
I'll put something together when I've had more sleep

**Comment by briis** [comment]
Thanks Nick.

**Comment by bdraco** [comment]
This affects a lot of integrations 
https://github.com/home-assistant/core/pull/47886#issuecomment-800611244

I'm going to do an audit. It will be a few days

**Comment by briis** [comment]
It looks like a need to make some changes to other Integrations I made as well, once I see how you fix this. 😅

**Comment by bdraco** [comment]
Potential solution https://github.com/home-assistant/core/pull/48908

**Comment by briis** [comment]
I looked at the code, and will this then fix it for all Integrations, without any code change?

Btw: Isn't it very late where you are  😌

**Comment by bdraco** [comment]
> I looked at the code, and will this then fix it for all Integrations, without any code change?

Thats the idea
> 
> Btw: Isn't it very late where you are  😌

...and yes it is

**Comment by bdraco** [comment]
The change is happening in next month's release so the problem will just go away :)

Anyone who has the leak probably just needs to restart once or twice a month to avoid the memory exhaustion until next month's release.

**Comment by briis** [comment]
Perfect. Thanks for the work you put in for all of us to fix this.
