### ISSUE TITLE
Feature Request: Remember state when using switch.

### ISSUE THREAD

**Issue by vandalon** [briis/unifiprotect#22]
Hi,

Thanks you so much for this awesome add on. 

As a extra feature for the switch I think it would be nice to switch between previous state and off. Now if it's recording always, and I switch to off, then on again, the camera is set to record on motion. I think it would be nice to switch  back to always, if the previous state was always. 

Other option would be to make 2 switches. one for always recording , the other for on motion. but then one switch should automatically turn of the other because having them both on would be confusing :)

Again, 
Thank you for your great work!

**Comment by briis** [comment]
Thank you fir the feedback. I like the idea, and will look in to what is the best way to implement this. Currently the component does not support the 'Always Recording' mode, but I have also thought about how I could do that. Once I have given it some thoughts I will let you know.

**Comment by vandalon** [comment]
Maybe storing the previous state in the sensor as attribute and use that for the switch?

**Comment by briis** [comment]
Yes that is definitely an option. 
Ideally, instead of switch, an `input_select` component would be better, as this can hold all 3 states the recording mode supports and then it would just be pulling the state from the camera.  I am just not sure it is possible to make a custom input_select component. 
But I am doing some more digging and thinking.

**Comment by briis** [comment]
My personal preference is a Dropdown, with the 3 values that the Camera accepts. But right now, I don't how to do that. So what would you say to this suggestion:

* Create a new service called `unifiprotect.enable_always_recording`, which sets the recording mode for a specific camera to *always*
* Create a new Switch, that enables/disables *always* recording. If enabled the current switch, will automatically be disabled and vice versa. The state of the Switch will be determined by the camera state in Unifi Protect, so it will always display the latest state. (As does the other Switch)

Would that work for you?

**Comment by vandalon** [comment]
Maybe create a service unifiprotect.set_recording_mode which can be "on_motion" or always"?
creating a switch "record_always" would be a good idea I think. If on, the camera switch will use 'always' and otherwise it will use 'on_motion'.

**Comment by briis** [comment]
Thanks. I will work on that. Will post when done.

**Comment by briis** [comment]
Release V0.1.3 contains the new functionality, so I will close this issue.

**Comment by vandalon** [comment]
You Sir, are awesome! Thank you
