### ISSUE TITLE
Trying to look into the future

### ISSUE THREAD

**Issue by johanjongsma** [briis/unifiprotect#223]
Hi Bjarne,

I'm planning to change my sliding glass doors, and since ordinary sensors only monitor if the door is opened or not, I'm thinking about breaking glass sensing.

Q: Do you expect (or does it already exist) such a feature in Unifi Protect, in let's say within six months?

All the best, Johan

**Comment by johanjongsma** [comment]
I saw that sensor, but I was more thinking along the lines of acoustic monitoring, hence I was thinking of my cameras. Something like this: https://www.vivint.com/resources/article/how-do-glass-break-detectors-work, but then using the microphone of the camera. Does that need to be done by UI or could we 'add something' to monitor the audio stream?

Johan

**Comment by briis** [comment]
Got it. Interesting thought, and in most of the Ubiquiti cameras there is already a microphone, so technically we have what we need. Unfortunately the API does not expose an event based on Audio detected (as far as I have seen), so for this to work we would need to write something that constantly listens to the audio stream, and detects that specific glass-breaking frequency - and this is beyond the scope of this integration.

I can only suggest you ask Ubiquiti to add this feature to the Protect system, and then we can capture it.

**Comment by briis** [comment]
Hi Johan,
As there is not much I can do from here, I will close this now. I will keep an eye out for new sensors or possibilities with the cameras.
