### ISSUE TITLE
OpenSSL SSL_ERROR_SYSCALL when connecting to Cloud Key Gen2

### ISSUE THREAD

**Issue by blaines** [briis/unifiprotect#227]
I'm using home assistant as a docker container https://hub.docker.com/r/homeassistant/home-assistant

It turns out that in recent alpine linux versions openssl is not compiled with "enable-weak-ssl-ciphers". Because of this, at least for my installation of Unifi Protect, I cannot make the connection without rebuilding the image. I might make a more detailed bug upstream, as many IoT devices are likely built using weak and old ciphers and should probably be more permissive as a docker image.

```
bash-5.0# curl -k https://192.168.x.x
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 192.168.x.x:443
```

All other non-alpine-linux systems make the connection just fine. This issue might only be useful as a heads up for future problems.

**Comment by briis** [comment]
Thanks for the heads-up Blaine. I am in no way an openssl expert, to say the least, but it seems that you have been able to solve it for your specific use case. If this becomes a more generic problem, we will have to see if we can find a solution for it. Thanks

**Comment by briis** [comment]
I will close this now, but flagged it as information for later use.
