### ISSUE TITLE
Camera stream error

### ISSUE THREAD

**Issue by bjarnekrottje** [briis/unifiprotect#228]
Home Assistant Configuration details:
Version: Core 2021.5.0
Unifi Protect integration v0.8.7

When trying to stream the doorbell video to my Google Hub, I get the following error:

_Triggered manually at May 6, 2021, 4:03:40 PM
Call service camera.play_stream on entities camera.voordeur_deurbel
Stopped because an error was encountered at May 6, 2021, 4:03:40 PM (runtime: 0.01 seconds)
camera.voordeur_deurbel does not support play stream service_
![image](https://user-images.githubusercontent.com/46538710/117313723-706d6400-ae86-11eb-8ec8-6c4309805fec.png)

This is the automation in which it happens:

![image](https://user-images.githubusercontent.com/46538710/117313623-59c70d00-ae86-11eb-8321-8da4c10d6b53.png)

Do the UniFi Protect camera's support streaming their video to a different device?
https://community.ui.com/questions/Google-Home-Hub-Support/e0892d60-ece1-4193-8ad5-8b4640aea730#answer/ac9dcf6a-f301-4850-9074-93950fe32489
Here I saw someone who got it working, but unfortunately I seem to get this exact error every time, also with other UniFi Protect camera's. What could be the problem?
Thanks in advance!

**Comment by briis** [comment]
I have just tested this in my setup, which is equal to yours. I also used the Doorbell Camera and streamed to a Nest Hub, without any issues. I even have sound. So this is not a Unifi Protect issue. 

I used this service call:

```yaml
service: camera.play_stream
target:
  entity_id: camera.kamera_doerklokke
data:
  media_player: media_player.alrum
```

**Comment by briis** [comment]
As said, I am sure this has nothing to do with this Integration, it must be something else. Here are few things to check/try out:

* Have you this line `stream:` in your `configuration.yaml` file? Else try add it, and restart Home Assistant.
* Also did you install the [Google Cast Integration](https://www.home-assistant.io/integrations/cast/)? 
* And [Google Assistant](https://www.home-assistant.io/integrations/google_assistant)
* Try and turn-off the high resolution RTSP stream in the Unifi Protect APP. Click the Camera, and select the `Manage` tab, and then turn off the High and Medium streams. Then go back to the Integrations page in HA, and click the 3 dots in the lower right corner and Reload the Integration. And then try to stream again. Nest Hubs don't like the very High Res Streams.
* Finally try and search [the Forum](https://community.home-assistant.io/), maybe someone has had the same issue .

Those are the ideas I have for now

**Comment by bjarnekrottje** [comment]
Changing the RTSP stream and rebooting my UniFi setup did the trick. Thanks for the tips!

**Comment by bjarnekrottje** [comment]
I did notice that when RTSP is disabled, it gives that error.  So when RTSP is not enabled, you can not stream the video.
Is that intentional? Because of the quite large delay, it would be nice to disable RTSP but still be able to stream it to a chromecast.

**Comment by briis** [comment]
Cast only supports certain stream formats, and when you turn off the RTSP stream, you are actually not streaming anymore, but just refreshing the image every second - and that is not supported by Chromecast.

There is an issue with the stream component in HA, that creates this delay, but I just saw that a PR is raised, that should hopefully take most of that delay away. Hopefully that will be in the June release of HA.

**Comment by bjarnekrottje** [comment]
Alright, that makes sense. Well thanks for the information and help!
