### ISSUE TITLE
Anonymous Snapshot Refresh Cycle

### ISSUE THREAD

**Issue by mikebol** [briis/unifiprotect#229]
I am using Unifi Protect with 6 cameras and have these setup through Home Assistant (2021.5) and working fine.  I have all of the cameras setup with anonymous snapshots enabled.  With the camaras on a panel, I am still only seeing thumbnail refreshes every 10 seconds.  Reading through your documentation, enabling the anonymous snapshots should enable faster refresh cycles but I'm not seeing that.

```
type: picture-entity
entity: camera.basement_slider
show_name: false
show_state: false
camera_view: auto
aspect_ratio: '16:7
```

Do I need to use a different control or configuration for this to work properly?

Mike

**Comment by briis** [comment]
Hi Mike,
Anonymous Snapshots are no longer needed, and will not make things refresh faster. I assume when you say that Thumbnails only refresh every 10 seconds it is in a Lovelace Card? That is not related to this Integration, but is the way HA works. If you want to have a Live image, then you can use the [Picture Glance Card](https://www.home-assistant.io/lovelace/picture-glance/) and set `camera_view` to `live`.

**Comment by mikebol** [comment]
Thank you for the FAST reply.  This is exactly what I needed.

Mike
