### ISSUE TITLE
Does not work with Unifi Video (self hosted)

### ISSUE THREAD

**Issue by todfox** [briis/unifiprotect#23]
Same issue as https://github.com/briis/unifiprotect/issues/21#issue-556960051

**Comment by briis** [comment]
Hi,
This is not supposed to Work with Unifi Video, as this is a total different application. The issue in #21 is that it is Unifi Protect that runs on that HW, but it is implemented differently than on the CloudKey.
For Unifi Video, take a look at this : https://www.home-assistant.io/integrations/uvc/
