### ISSUE TITLE
No Preview when anonymous screenshot is enabled.

### ISSUE THREAD

**Issue by lowrisk75** [briis/unifiprotect#232]
Info 
I always used the integration without "anonymous preview", I decided to enable it when I reinstalled the integration (I reseted UniFi Protect and have to start over).

When Anonymous preview is enable, I cannot have any preview of the camera (but the steam work just fine)
https://ibb.co/t33Bzmr
https://ibb.co/JK4qZPz
https://ibb.co/d5fk1ZJ

As soon as I disabled it, everything is back to normal.

-- I enabled anonymous screenshot in the camera UI.

PS: who have access to anonymous preview ? is that only the local user / local storage or is that a remotely shared with UI network (I suppose it isn't but if so, the issue might be due to my CloudFlare Access)

**Comment by briis** [comment]
Hi,
Anonymous snapsnots is not needed anymore. It was only a workaround until we could fix the bug preventing the image to refresh. This has been solved a few month ago. So I recommend you turn off Anonymous Snapshots on your cameras, and turn off the feature in this Integration. If you still have issues, then post it here.

Who has access to anonymous snapshots? This integration only runs on your internal network so this does not by itself pose any risk. But in the end it depends on, how your network is setup. If your cameras are available from the internet, people would be able to see the snapshots - another reason to turn it off.
