### ISSUE TITLE
UniFi Protect as Media Source

### ISSUE THREAD

**Issue by SeraphimSerapis** [briis/unifiprotect#237]
I am not sure if this is even possible, but it would be fantastic to get access to the recordings (for instance motion events etc) via the Home Assistant Media Browser. Has this been explored already?

**Comment by briis** [comment]
There is no official support for accessing the stored files in Protect. There is a guy who [made a tool](https://community.ui.com/questions/Tool-for-downloading-footage-from-UniFi-Protect/47057c1d-112b-4092-b488-a380286933df), that can bulk download the recordings, but I have never used it, and I am not sure it still works on this version of Protect.

There is always the option of letting HA start a recording session, when motion happens.

So for now, I cannot do anything on this.

**Comment by SeraphimSerapis** [comment]
Much appreciated, thanks for the feedback! Would you prefer for me to close the issue or keep it open for the case that this will ever be a possibility?

**Comment by briis** [comment]
If this shows up, I will remember. And honestly, if it shows up, I would guess it would be the Protect APP having the option of storing or copying the recordings to a NAS or similar. So by that time, I think it would be much easier just to move or copy these files to the Media directory from the Protect APP. But lets see.

So please close for now.

**Comment by SeraphimSerapis** [comment]
Done! And thank you for this brilliant integration ❤️

**Comment by AngellusMortis** [comment]
I think it would be feasible to do this now with the current APIs are I am seeing in the Webapp. I did some poking around in https://github.com/briis/pyunifiprotect/ and I think I can make it work. I think it is about time I actually put my Python skills to use for the HA community.

**Comment by briis** [comment]
You are very welcome to give it a go. My Python skills are not where I can do it. Just make a PR when you have something to test and I will merge it.

Thanks.

Bjarne

P.S. I am on vacation right now, so limited access to systems. Will be back in a week or so.
