### ISSUE TITLE
FR: Fire event for doorbell button

### ISSUE THREAD

**Issue by TomBrien** [briis/unifiprotect#239]
The current Home Assistant [standard](https://developers.home-assistant.io/docs/core/entity/switch/) for things like buttons which don't have a persisted state is to fire an event rather than toggle a `binary_sensor`. Obviously a breaking change for this is undesirable, would it be possible to fire an event in addition to the sensor for now? This would allow for more consistent automation triggers for similar devices.

Many thanks for the great component.

**Comment by briis** [comment]
This has just been released in 0.8.9, so I am closing the issue
