### ISSUE TITLE
FR: Ability to Update G4 Doorbell Status Message

### ISSUE THREAD

**Issue by tehkurt** [briis/unifiprotect#240]
Would be nice to be able to set the status message on the G4 Doorbell doorbell via automations.

**Comment by briis** [comment]
Hi,
That is already. possible. Look at [this section](https://github.com/briis/unifiprotect#special-unifi-protect-services) in the README file, and go to `unifiprotect.set_doorbell_lcd_message`. Is that what you are looking for?
