### ISSUE TITLE
Decreased image size

### ISSUE THREAD

**Issue by patdemko** [briis/unifiprotect#241]
I use the cameras created by this integration to feed the doods integration to do object detection and then I save images of anything detected to be viewed later.  I just noticed that a few days ago the images being saved are much smaller than they used to be for all of my cameras except for my doorbell camera.  I think this is around the time I installed the latest release (v0.8.8).  I'm also noticing the decreased image size when viewing a live stream of the camera.  Should anything of changed in the latest release to affect the image size for all the cameras except for the doorbell?  Here's a before and after image showing what I mean (click on the images to open them up to see the actual size difference).

Before Image
![before](https://user-images.githubusercontent.com/11141892/119921572-3ef33000-bf3c-11eb-8d56-3cf905096cd9.jpg)

After image
![after](https://user-images.githubusercontent.com/11141892/119921587-44e91100-bf3c-11eb-847d-8438aeb6a362.jpg)

**Comment by briis** [comment]
Yes a change was implemented in 0.8.8, where the size of the image is determined by the feed we get from Protect. This was done to ensure that the aspect ratio is correct. If you go in to the Protect Web APP, and select a Camera, and then go to *Settings* and *RTSP* you can see that there are 3 different sizes available. This Integration will always select the size with the highest resolution. I have a few G4 PRO Cameras, and if you look at those you will see that they have the following three resolutions: High (3840x2160), Medium (1280x720) and Low (640x360). If I disable the High Stream, the image captured would then be 1280x720.
So try and look at the cameras in Protect and if you have disabled the High Stream, then reenable it. You can then reload the Integration from the Integrations page, to enable the new resolution. Let me know if this helps.

AND, sorry for not being clear on this - but the change was necessary, to ensure the correct sizes - what I had before was an educated guess.

**Comment by patdemko** [comment]
Thanks, that was it.  For some reason I had the high RTSP feed active for the doorbell but not the other cameras.  Once I activated the high RTSP feed for all the other cameras and then reloaded the integration it is now back to the way it was.  Thanks again for the help!
