### ISSUE TITLE
Question:  Multiple Unifi NVR/Protect units onsite to connect to?

### ISSUE THREAD

**Issue by jamesliin** [briis/unifiprotect#243]
Is it possible to already? or is it something that would need further development, 
to allow the ability to connect to multiple Unifi Protect-NVR's on our network, 

Or another way to ask, is the ability to grab multiple cameras from multiple NVR servers, 
We have 4 NVR's, and Id like to use cameras from each NVR within one dashboard.  

Thank you again for great work on neat project

**Comment by briis** [comment]
This is already supported. If you have more than one NVR, then you just add the Integration again, with the new server details.

**Comment by jamesliin** [comment]
Thank you for this information,
