### ISSUE TITLE
[Question]: Non RTSP; Image size

### ISSUE THREAD

**Issue by rajeevan** [briis/unifiprotect#244]
Hello,

I'm happy to see more realtime and fast loading image in the Homeassitant.. However, I have these cameras plugged into DeepstackAI https://github.com/robmarkcole/HASS-Deepstack-object for object detection. I see that the Image grabbed by the Deepstack is the default thumbnail resolution.

Is it possible to customise or even specify larger image size to be returned?

Thanks a lot for all the work you have put in this and continued update :) 

I'm using this plug-in for scanning and notification when not home and integration of doorbell with Google Home.

**Comment by briis** [comment]
I recommend you use the service `camera.snapshot` service instead of the Thumbnail. That will give you the highest possible image size. The thumbnail will always be - a thumbnail - so a small image, and it might even have a delay.
