### ISSUE TITLE
403 Forbidden Error in HA Logs when trying to update LCD Message via automation

### ISSUE THREAD

**Issue by tehkurt** [briis/unifiprotect#247]
When the automation runs that calls for the LCD display to changed, this error prints in the logs:

Setting Doorbell Custom Text failed: 403 - Reason: Forbidden

All other functions of integration seem to be working as expected. Error first started showing up yesterday, but no updates to Protect, Cloudkey, or HASS between working and not.

Cloudkey 2.1.11
Protect 1.19.0-beta.10
HA: 2021.6.3

**Comment by briis** [comment]
Are you sure that the user you have setup has Administrative Rights?

**Comment by tehkurt** [comment]
My HA user is set up with administrator rights for protect. Although I had already tried it prior to reporting here, a full restart of the cloudkey and HA vm seems to have resolved the issue.

**Comment by briis** [comment]
OK, glad to hear that. Watch it for a while, and if it keeps stable, please close this. Thanks.
