### ISSUE TITLE
Allow FQDM in addition to IP Address

### ISSUE THREAD

**Issue by LanceMcCarthy** [briis/unifiprotect#248]
You can easily pull the IP address form a fully qualified domain name (FQDN) in your script, but restricting us to only using IP addresses eliminates everyone who has a dynamic IP address from the ISP.

In case you're not familiar, here is the easiest way to get the IP address form any FQDN

```

# this is what this feature request is all about.
# I want to use a domain name, like duckdns, so that the WAN IP is always up to date
$udmpro_fqdn=mydomain.com

#I would allow this parameter to be set, but if you're going to hard code it, use cloudflare
$dns_nameserver=dns1.cloudflare.com

# boom, easy grep of nslookup
ip_address="$(nslookup -type=A $udmpro_fqdn $dns_nameserver | grep "Address" | awk '{print $2}' | sed -n 2p)"
```

**Comment by briis** [comment]
This was designed to only work inside your LAN, for security reasons. Accessing this through a WAN connection could create all sorts of network related timing issues as the Integrations pushes information to Home Assistant.

Did I read your request right?

**Comment by LanceMcCarthy** [comment]
Correct. I have two UDM Pros in two different physical locations, but Home Assistant is only behind one of them.

So in order for me to connect to the 2nd one, I can think of two options:

- Use the WAN IP address (or an FQDN which is always up to date with the WAN IP address) 
- Have a site-to-site VPN between the UDM Pros (so that the 2nd UDM Pro's IP address is accessible by HA)

I understand your concern about using a WAN IP address. Unfortunately, even with the site-to-site VPN setup between the UDM Pros, unifiprotect integration is not working (see screenshot below).

## Example
Let me give you an example that matches my simple setup

- UDM Pro Installations
  - UDM Pro 1 - `192.168.1.1`
  - UDM Pro 2 - `192.168.0.1`
- Home Assistant Instances
  - Main HA: `192.168.1.25`

As you can see, **Main HA** is on the UDM Pro 1's network. This works flawlessly with the UDM Pro 1's Protect instance and the unifiprotect Integration.

However, if I try to set up a 2nd unifiprotect Integration pointing to the UDM Pro 2's IP address (192.168.0.1), I always get an error. Just to make sure this is not a VPN issue, see the ping test in the following screenshot.

![image](https://user-images.githubusercontent.com/3520532/122808736-412a7f00-d29b-11eb-85a1-5fb9e43e0497.png)

# Conclusion and Final Question
A large portion of UDM Pro users I know uses the WAN IP address of their UDM Pro (for things like VPNs to UniFi portal management). Is this WAN limitation in this integration or the UDM Pro, because I can easily access my Protect instance from the WAN IP or FQDN address at any time (I personally use a FQDN because it stays synced with my WAN IP).

If it is within your power to do so, make this an advanced option for powers users who know what they're doing. Thanks!

**Comment by LanceMcCarthy** [comment]
I figured out a workaround. Albeit cumbersome, because it requires an extra  Home assistant installaiton, it is an option for me to have all my Protect camera feeds inside the single Home assistant dashboard.

1. Install a new Home Assistant instance inside the same network as the 2nd UDM Pro
2. Install and setup the **unifiprotect** Integration on the extra Home Assistant instance
3. On the original Home Assistant instance, install the **Remote Home Assistant** integration
4. Configure Remote Home Assistant to connect to the 2nd Home assistant instance
5. Observe all unifiprotect sensors are now available in the main Home Assistant instance

![image](https://user-images.githubusercontent.com/3520532/122811908-075b7780-d29f-11eb-83f8-5ee8eefa469b.png)

**Comment by briis** [comment]
Hi Lance,
I put it on as an Enhancement, and will look at it as soon as I have time.

**Comment by AngellusMortis** [comment]
It is interesting that the FQDN does not work. I have mine set up over LAN using a DNS name (I have a PiHole set up I double as a DNS so I can use real SSL certs, and everything). Everything works great with the DNS name,

**Comment by LanceMcCarthy** [comment]
@AngellusMortis maybe yours works because the Pihole is serving local dns queries?

I do also run Pihole, and nginx reverse proxy for ssl of all my servers, but ultimately the UDM Pros I have must get dns requests answered by Godaddy (because my UDM pros are in different countries and I run a custom ddns to update those IP addresses every 15 minutes)

**Comment by AngellusMortis** [comment]
It is a local only DNS record, yeah. My UDMPro that controls the network that my HA RPI is on uses my PiHole for DNS so the DNS is pushed out to every device on my network. It should not matter _who_ serves the DNS. Whether it is a PiHole, your ISP's DNS server or GoDaddy. DNS is DNS. 

Can your HA instance resolve the DNS from the command line?

**Comment by AngellusMortis** [comment]
It is also worth noting that your "workaround" for accessing the other Protect instance is actually probably more secure then connecting to it directly. It allows you to access your Protect instance without directly allowing external network access. That obviously does not matter if you already have external network access enabled.

**Comment by LanceMcCarthy** [comment]
@AngellusMortis the good news is `nslookup` from the HA command line does return the correct WAN IP of the remote UDM Pro. So I know it's technically possible, because the upstream DNS requests are passing through the PiHole.

I'll try this approach again, thanks for the tips.

**Comment by AngellusMortis** [comment]
Any update on this? Did you get it all working?

**Comment by AngellusMortis** [comment]
Added a lot more code that should help with this. It will require the IP you want to access your device via over the Internet to have the WAN IP configured as connection host. I think this done for UDM Pros with remote access on.
