### ISSUE TITLE
Getting Internal Server Error after core update to core-2021.6.5 

### ISSUE THREAD

**Issue by webdados** [briis/unifiprotect#249]
I'm getting this in the logs:

```
Logger: pyunifiprotect.unifi_protect_server
Source: /usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py:562
First occurred: 10:12:25 AM (3 occurrences)
Last logged: 10:12:45 AM

Error Code: 500 - Error Status: Internal Server Error
```

The cameras feed and motion detection are still working.

**Comment by briis** [comment]
Do you have 3 cameras? This caused by the snapshot routine, where I try to read the camera image width and height, before they have been set I believe. I will try to set a default value, if the value cannot be read, and then it will be updated on subsequent calls to the function.

**Comment by webdados** [comment]
I have just 1 camera for the moment. This happens even if the camera is not connected at the moment.

**Comment by briis** [comment]
I believe I have a fix. To test it out, could you modify the `manifest.json` file in the unifiprotect directory and change this line:

```json
"requirements": [
    "pyunifiprotect==0.30.18"
  ],
```
to this:
```json
"requirements": [
    "pyunifiprotect==0.30.19"
  ],
```
Then restart Home Assistant, and let me know if this works.

**Comment by webdados** [comment]
Yes, it's fixed. Thanks!
