### ISSUE TITLE
Camera Delay

### ISSUE THREAD

**Issue by vandalon** [briis/unifiprotect#25]
When using the stream component the delay of the camera is about 10 seconds. I know this has something to do with key frames and hls. But maybe you have any idea how to reduce this?

Also, when not using the stream component the image only updates once every 10 seconds it would be nice to have a config option to increase this up to once or twice per second. (the generic camera component of HA also fetches the image as fast as possible I think.) :)

**Comment by briis** [comment]
As @robban says in this post [Axis Cam – Delay in live Stream on Lovelace](https://community.home-assistant.io/t/axis-cam-delay-in-live-stream-on-lovelace/132135/2?u=briis ) this is unfortunately an issue when streaming through Home Assistant. I don't have any way of optimizing the stream - the only way of lowering the delay, is minimizing the quality of the stream (Frame Rate and Image Size), but it will only minimize the delay, not remove it.

The standard update time for any Home Assistant component is 10 seconds. I will look in to adding the scan_interval config option and also update the image at the same time.

**Comment by vandalon** [comment]
Thanks!

**Comment by briis** [comment]
No further action to be taken by this component, but would great if Home Assistant in general could improve the Stream Service
