### ISSUE TITLE
Enhance save_thumbnail_image to mkdir

### ISSUE THREAD

**Issue by andrewkroh** [briis/unifiprotect#250]
This is a feature request to have the `unifiprotect.save_thumbnail_image` create the directories if it does not exist. The use case is organizing saved images in a date hierarchy like `snapshots/2021/06/18/2021-06-18T18:02:53Z_garage_person.jpg`.

https://github.com/briis/unifiprotect/blob/a7db2268df5ee9978f401f33a84a0e7dc3a06402/custom_components/unifiprotect/camera.py#L331-L335

The core `camera.snapshot` has this behavior.

https://github.com/home-assistant/core/blob/6a7968593d8e024fc6c4c2f7535a6a18b0f2f34a/homeassistant/components/camera/__init__.py#L673-L674

Thanks for your time on this project. It's a really awesome integration 🙇 . I just discovered it today.

**Comment by briis** [comment]
I will look at this as soon as I can.

**Comment by briis** [comment]
This has just been released in 0.8.9, so I am closing the issue
