### ISSUE TITLE
unifi protect is not showing up as an available integration

### ISSUE THREAD

**Issue by rayjlinden** [briis/unifiprotect#251]
Has the name changed or something?  I was following the directions on the README.md  to search for "unifi protect" - but it finds nothing.  This is on a bran new install of HA.

**Comment by andrewkroh** [comment]
Did you install it via HACS? First you need to install it via HACS, then restart, then you'll find it on your Integrations search. You may need to clear your browser cache after the install because I think the list of integrations is cached.

**Comment by rayjlinden** [comment]
Ah.  I missed the bit about HACS.  Actually, I did not even know about it -
so I got more learning to do…

**Comment by briis** [comment]
And after you install it via HCAS, please do a hard refresh of the Integrations page, to be sure you will see the integration. Closing this now.
