### ISSUE TITLE
No more binary_sensor updates after NvrError

### ISSUE THREAD

**Issue by andrewkroh** [briis/unifiprotect#255]
My Unifi controller rebooted and I think this integration may not have fully recovered after that occurred. There were a few connectivity related exceptions (`ClientConnectorError`) followed by one `NvrError`. That last exception might have been while the controller was still coming up.

```
2021-06-30 19:45:43 ERROR (MainThread) [custom_components.unifiprotect.data] Error while updating
Traceback (most recent call last):
  File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 123, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 306, in _get_device_list
    raise NvrError(
pyunifiprotect.unifi_protect_server.NvrError: Fetching Camera List failed: 404 - Reason: Not Found
```

Version: v0.8.8
HA Version: 2021.5.5
Attachment: [home-assistant-logs.csv](https://github.com/briis/unifiprotect/files/6748390/home-assistant-logs.csv)

After the NvrError at 19:45, home assistant stopped getting any `sensor` and `binary_sensor` updates related to Unifi Protect. Only the `camera` entities were updating (every 5m). I was logging events with the [Elasticsearch integration](https://github.com/legrego/homeassistant-elasticsearch) so I took a look at the data:

<img width="1072" alt="Screen Shot 2021-07-01 at 8 35 49 AM" src="https://user-images.githubusercontent.com/4565752/124125934-251ba000-da48-11eb-9008-4ef6537f92b3.png">

I thought maybe the code was missing some exception handling around this line to trigger a retry (but I'm not at all familiar with writing home assistant integrations).
https://github.com/briis/unifiprotect/blob/631cfd64b5c9cb1a72c605a5b0c404d7d98b1aec/custom_components/unifiprotect/__init__.py#L99

**Comment by briis** [comment]
Thanks for the detailed log, looks good, I need to look at that Integration 😁

> await protect_data.async_setup() 

If you look at the next two lines after the above, they first check if we got data returned, and if not the line `raise ConfigEntryNotReady` will then retry getting data, or eventually give up. If have tested this many times, by pulling the plug on my Protect Server, and my entity always recovers after that. I do get entries in the log files, but I do not see it crash completely.

If you go to Configuration->Integrations and then select the Unifi Protect integration and then click the 3 dots, you should be able to re-initialize the integration without restarting HA. Does this generate the same error as above?

**Comment by andrewkroh** [comment]
> If you go to Configuration->Integrations and then select the Unifi Protect integration and then click the 3 dots, you should be able to re-initialize the integration without restarting HA. Does this generate the same error as above?

Things look good after that. No exceptions and I'm getting binary_sensor updates.

> If you look at the next two lines after the above, they first check if we got data returned, and if not the line raise ConfigEntryNotReady will then retry getting data, or eventually give up.

I'm not much of a Pythonista so forgive my ignorance 😄 . I assumed that if an exception was raised in `async_setup` that it would never even get to execute those two lines where it checks for data received. I was thinking it needed to try/except around that call and then raise ConfigEntryNotReady. BTW is ConfigEntryNotReady what triggers HA to retry?

**Comment by briis** [comment]
I don't know all the *Internals* of Home Assistant, but I have learned that raising the `ConfigEntryNotReady` is the correct way to do it, if an Integration does not supply the expected data on startup. I assume that this will restart the init process, and it has shown to work (Most of the time)

**Comment by AngellusMortis** [comment]
This should be reduced or removed in the 0.11. Please let us know if you see this error anymore.

**Comment by AngellusMortis** [comment]
Not heard back on this one and 0.11 is finally in stable. Closing for now, but please let us know if you keep having the issue.
