### ISSUE TITLE
G4 Doorbell binary sensor state change not triggering automation

### ISSUE THREAD

**Issue by stake63** [briis/unifiprotect#257]
First off, great integration, thankyou. 

Secondly I'm a complete novice so my issue may just be my inexperience so any assistance would be much appreciated.

I have created an automation to announce a doorbell press (G4 Doorbell) on my Google Home Hub. If I run the automation from within Home Assistant (RUN ACTIONS)  it works fine, however when I press the doorbell it doesn't run

I can see the state changes being registered in Home Assistant

![image](https://user-images.githubusercontent.com/86786176/124387284-423ec000-dd21-11eb-9e91-073627dd677e.png)

Running a CK Gen2+ with latest UnifiOS 2.1.11 and Protect 1.18.1

Thanks

**Comment by briis** [comment]
Could you post the yaml of the automation you are trying to run?

**Comment by briis** [comment]
With the latest 0.8.9 release I introduced a new way of detecting the doorbell press - I added an event. If you [look here](https://github.com/briis/unifiprotect#send-a-notfication-when-the-doorbell-is-pressed), in the README, you can see a very basic example on how to automate that.

**Comment by stake63** [comment]
Hi briis,
Yes I did see that before but didn't know how to interpret it but now it makes sense to me. I just change the event trigger to what you described and it worked perfectly.

Here is my code, it may help others
`alias: Doorbell
description: ''
trigger:
  - platform: event
    event_type: unifiprotect_doorbell
    event_data: {}
condition: []
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.8
    target:
      device_id: d374e7f879f1785287d640c03097d3e0
  - service: tts.google_translate_say
    data:
      message: Someone is at the door
      entity_id: media_player.family_room_display
  - delay:
      hours: 0
      minutes: 0
      seconds: 4
      milliseconds: 0
  - service: media_player.volume_set
    target:
      device_id: d374e7f879f1785287d640c03097d3e0
    data:
      volume_level: 0.3
mode: single
`

Thank you so much

**Comment by briis** [comment]
Wonderfull, glad it works. I will close this now.
