### ISSUE TITLE
Motion Score Attribute and Motion Binary Sensor desired behavior

### ISSUE THREAD

**Issue by tfer6** [briis/unifiprotect#258]
Is the motion score attribute supposed to update when the motion binary sensor turns on, or off?  I ask, because I have two cameras at the front of my house (doorbell & G3 Flex) and their behaviors are opposite.   When the doorbell sensor turns on, the motion score has some number >0; when it turns off the score is 0.  When the G3 Flex sensor turns on the motion score is 0 and when it turns off, it's >0.  I tried removing and reinstalling the integration to see if that would change the behavior of one of them, but no luck.  They keep being opposites.  I also tried power cycling both cameras, with no luck.

**Comment by briis** [comment]
The different camera types are unfortunately behaving differently. G4 Series normally give you a motion score when turning on, but there should be a final score when the sensor turns off, together with a length of the event. The G3 series, don't give a score before the sensor turns off.

I have G4 Pro, Doorbell, G3 Micro, G3 Flex, G4 Dome and even the AI 360 and the above is how it works for all those.

**Comment by tfer6** [comment]
Ah...  very unfortunate.  Thanks for the explanation.  I was driving myself crazy trying to figure it out.
