### ISSUE TITLE
Thumbnail image not/rarely available for doorbell

### ISSUE THREAD

**Issue by TomBrien** [briis/unifiprotect#265]
I am seeing a lot of log entries when trying to update a last thumbnail image immediately after motion clears:

```logtalk
Logger: homeassistant.components.automation.update_doorbell_motion_image
Source: custom_components/unifiprotect/camera.py:238
Integration: Automation (documentation, issues)
First occurred: 11 July 2021, 12:23:20 (462 occurrences)
Last logged: 9:49:19

Update doorbell motion image: Error executing script. Unexpected error for call_service at pos 1: Thumbnail Request failed: 404 - Reason: Not Found
While executing automation automation.update_doorbell_motion_image
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 666, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 811, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/unifiprotect/camera.py", line 238, in async_save_thumbnail
    image = await self.upv_object.get_thumbnail(self._device_id, image_width)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 507, in get_thumbnail
    raise NvrError(
pyunifiprotect.unifi_protect_server.NvrError: Thumbnail Request failed: 404 - Reason: Not Found
```

The automation that calls the last thumbnail service is pretty simple:

```yaml
alias: Update doorbell motion image
id: a38bc872-29d6-4e1d-919c-f13f64e1b473
mode: restart
trigger:
  - platform: state
    entity_id: binary_sensor.motion_g4_doorbell
    from: 'on'
    to: 'off'
action:
  - service: unifiprotect.save_thumbnail_image
    data:
      entity_id: camera.g4_doorbell
      filename: /config/www/motion/doorbell_latest.jpg
```

I'm guessing the controller is generating the thumbnail and it isn't present at that time. If so I would expect a small delay would fix this but I wonder if it's better handled by some retry logic in the component or I'm missing something.

**Comment by TomBrien** [comment]
Actually I'm seeing those error on pretty much every call to `unifiprotect.save_thumbnail_image`

**Comment by briis** [comment]
The issue with this call, is that the Thumbnail image is not available right after an event occur, it will be generated by Protect after the event, so there can be timing issues. I recommend using the `camera.snapshot` service instead.

**Comment by TomBrien** [comment]
Actually I'm getting the 404 error pretty much every time I try and get the thumbnail including when calling the service through developer tools with no recent motion

**Comment by briis** [comment]
I will look in to this, but I highly recommend to use the `camera.snapshot` feature instead, as this is always available, and gives better image quality.

**Comment by AngellusMortis** [comment]
I am going to close this one for now. We are removing `unifiprotect.save_thumbnail_image` in 0.10 to prevent confusion since it does not necessarily work like everyone would expect. 

We are looking into a new/better way to provide the actually UFP thumbnails for events though rather then forcing you to take snapshots.
