### ISSUE TITLE
Image quality dropped after doorbell resolution fix

### ISSUE THREAD

**Issue by jeroenvandisseldorp** [briis/unifiprotect#266]
Hi Bjarne,

I only noticed this last week: after you fixed the doorbell resolution (https://github.com/briis/unifiprotect/issues/235) it seems that the image quality of all my Unifi protect cameras has dropped significantly. This is best illustrated by my doorbell snapshots, which I take when the doorbell is pressed. Where those snapshots used to be around 280kB with the "old skewed resolution", after the fix the snapshots with proper resolution are only 27kB. My snapshot script is the same as before. 

Is there a way I can control a camera's image quality manually, or is there something you modified in the module code?

Two example snapshots attached. One of mid-May before the resolution fix, and one from last week.

![snapshot-20210516-135247-doorbell](https://user-images.githubusercontent.com/26811807/126124962-0c0adecd-69ed-4a02-a0ec-cf427c534a18.png)

![snapshot-20210714-200421-doorbell](https://user-images.githubusercontent.com/26811807/126123476-afb4e5c0-195a-4fdc-a6ed-4f3a8077a30d.png)

**Comment by jeroenvandisseldorp** [comment]
With "resolution" I meant aspect ratio above. The two snapshots already indicate that resolution has also changed.

**Comment by briis** [comment]
Hi Jeroen,
Before the fix, I set a fixed Image Size and Width, for all G4 cameras, which then led to the wrong aspect ration on the Doorbell. Now I read the values from the actual stream, and use that. So my guess is, that you have not enabled the highest resolution RTSP stream, and that is why the image gets smaller. If you go in to the protect app, and enable the highest possible RTSP stream, then you should also get a higher quality snapshot.
Can you try this?

Note: You will have to restart the UniFi Protect Integration after the change in the Protect Web App. Integration page, click the 3 dots, and reload.

**Comment by jeroenvandisseldorp** [comment]
All my cameras are already set to highest resolution. Recording also is in highest resolution and the app gives me full picture quality. The doorbell specifically is set to "1200p" and When To Use is set to Always. There is however a small grey text undernath the 1200p setting in the settings screen for the doorbell that says "This will not apply to the web platform". Is the unifiprotect plugin for HA considered "web platform"?

**Comment by briis** [comment]
Hmm strange. Just to confirm: If you go to settings on the Camera in the Proect Web App, you have the below enabled?
And no the Integration is not a Web platform. I take the snapshot using the image width and height from the below settings. So if this is enabled the image should be 1600x1200, which is the max width for the doorbell with the current Aspect Ratio. Before that it was much larger, but that was a scaled image with the wrong aspect ratio. Can you check what the image size is of the snapshot?

<img width="376" alt="Skærmbillede 2021-07-19 kl  11 47 31" src="https://user-images.githubusercontent.com/24776272/126141016-e2dfe493-dd07-46ba-8430-3b62243089ed.png">

**Comment by jeroenvandisseldorp** [comment]
Ah got it. I misunderstood and checked the settings in the Android app. Found the settings and updated them. Full quality now! And I did not even have to restart HA or the unifiprotect module. Thanks a lot for pointing this out!
