### ISSUE TITLE
PICTURE ? 

### ISSUE THREAD

**Issue by barto95100** [briis/unifiprotect#27]
Hi, just one question, with this it's not possibel to view image/video on view section in HA ? 

because i configure a user with admin roles, configure in configuration.yaml but nothing in View but in developper tool a view the state = OK

**Comment by briis** [comment]
Hi,
This should work just fine. Besides setting up the base `unifiprotect` integration in configuration.yaml, you also need to add:
````yaml
camera:
  platform: unifiprotect
````
And then you can use a picture-glance card in your front end to display the picture and stream.

Did I understand your issue correctly?

**Comment by briis** [comment]
I assume this is closed now, else reopen.
