### ISSUE TITLE
Latest Unifi update broke the integration

### ISSUE THREAD

**Issue by shoxcorp** [briis/unifiprotect#272]
Hello! I updated yesterday to the new Unifi which merges accounts with the online platform. Unfortunately it broke this integration. Im getting:

Config entry 'name here' for unifiprotect integration not ready yet: Call https://192.168.x.xxx:7443/api/auth received 404 Not Found; Retrying in background

any ideas? 

my protect version is 1.18.1
Home Assistant 2021.7.4

edit: if i try re-adding the integration using UnfiOS (443) i get "Aborted" .

**Comment by briis** [comment]
I had another user with this issue, and he solved it by creating a new local user in Protect with admin rights and then use that account for connecting. Could you try that?

**Comment by shoxcorp** [comment]
Just tried with a new super admin account, both 443 an 7443 didnt do it :(

**Comment by shoxcorp** [comment]
ps

If I go to https://192.168.x.xxx:7443/api/auth I get: 
"Cannot GET /api/auth"

If I go to https://192.168.x.xxx:443/api/auth I get: 
"Not Found"

**Comment by briis** [comment]
I am on vacation right now, so it will be at least a week before I can look at this.

**Comment by shoxcorp** [comment]
All good. Enjoy your vacation!

**Comment by shoxcorp** [comment]
Ok I got it working! I had to completely remove (not disable) the old integration which was using 7443 and use 443 instead. It's all working now! Thanks and sorry for the noise. Hopefully this helps someone!
