### ISSUE TITLE
Possible to use Multi Cloudkey Gen2 ?

### ISSUE THREAD

**Issue by barto95100** [briis/unifiprotect#28]
Hi, just a question, it's possible to configure Two or more Cloudkey Gen2 ?

**Comment by briis** [comment]
Unfortunately not at the moment. Out of curiosity, why would you need that?

**Comment by barto95100** [comment]
Because I leave in France and I have a house in Portugal 

My two hose have a cloudkey gen2 with 6 cam in portugal and 4 in france

And in lovelace is great to view all camera france and portugal :)
