### ISSUE TITLE
Image resolution in Core 2021.9.0

### ISSUE THREAD

**Issue by dodg3r** [briis/unifiprotect#282]
Hi.

I´m using core-2021.9.0b0 and in the release notes is says:

Thanks to @bdraco, camera images can now be scaled to a resolution that fits the device/screen you are looking at; Additionally, they only update when visible. This makes cameras usable in any bandwidth situation.

And I get this is my logs:

`The camera entity camera.garage does not support requesting width and height, please open an issue with the integration author.`

I dont know what it mean but i thought maybe you where interested :)

**Comment by briis** [comment]
Closing this, as this is now fixed in 0.9.0.
