### ISSUE TITLE
camera requesting width and height

### ISSUE THREAD

**Issue by jazbraz** [briis/unifiprotect#283]
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:465
Integration: Kamera (documentation, issues)
First occurred: 0:02:44 (1 occurrences)
Last logged: 0:02:44

The camera entity camera.biorum does not support requesting width and height, please open an issue with the integration author

**Comment by bdraco** [comment]
This is a dupe of https://github.com/briis/unifiprotect/issues/282
