### ISSUE TITLE
The new viewport select entity isn't showing up

### ISSUE THREAD

**Issue by samhed** [briis/unifiprotect#288]
I read in your release notes that we should get a new viewport select when using the latest version of this integration. Either I can't find it, or it isn't added properly.

I can't find it under the devices or entities listed for the integration, and I can't find a single "select" entity, only a few unrelated "input_select". I have tried reloading the integration, restarting home assistant, reinstalling the integration and restarting the CKG2+.

I'm running v0.9.0 of the UniFi Protect Integration from HACS, on Home Assistant 2021.8.8. I have three different views in UniFi Protect, all of them have the "Share view with others"-option enabled. Running version 1.19.0 of UniFi protect on a CKG2+.

**Comment by briis** [comment]
When I run my system I now have this entity: `select.viewer_viewport` and that select entity is populated with my shared views.

You have restarted HA after the upgrade to 0.9.0?

**Comment by samhed** [comment]
Ok, good to know how it's supposed to be.

Yes, I've restarted HA since the upgrade, and I did it once again now just to be sure - the issue persists unfortunately.

**Comment by briis** [comment]
Could you try and turn on debugging and see if this shows something? Look at #286 for how to do that.
And just to verify - Your viewport shows up in the UniFi Protect APP?

**Comment by samhed** [comment]
Yes, I'll turn on debugging when I get home today, thanks for providing instructions.

The viewport shows up in the UniFi Protect web interface, I can switch between the views when at the "Live View" page. It doesn't show up in the Android app however, is it supposed to?

**Comment by briis** [comment]
If you go to the UniFi Protect Web App, and click on UNIFI DEVICES to the Left, you will get a list of all the devices attached to Protect. Do you have a device with model name `Viewport`?

Just to be sure: The Viewport is a physical devices like this: https://store.ui.com/collections/unifi-protect-accessories/products/unifi-protect-viewport?_pos=1&_sid=f9030556a&_ss=r
I am sorry if this is obvious, but just wanted to be sure.

**Comment by samhed** [comment]
Ohhh... I'm so sorry - I have completely misunderstood this whole thing. I do not have a viewport device. I thought this was about the different "views" that can be configured, and that those would appear as an entity in HA.

Apologies for wasting your time, and thank you for being patient with me :pray:

**Comment by briis** [comment]
Absolutely no problem Samuel. Glad we figured it out. The Viewport is only applicable if you want to monitor your Camera feeds all the time, without a Computer. I have bought one, but only because of this Integration, so I could test the functionality. I don't use it.
