### ISSUE TITLE
Homekit Not Streaming

### ISSUE THREAD

**Issue by germanhans** [briis/unifiprotect#289]
The snapshots update every 10 sec on Homekit, but when I tap a camera to view full screen, the image freezes, half the screen turns green, then it just updates with the snapshots. 

I have G4 doorbell and G4 pros, and am running just a standard Homekit and Home Assistant setup, no fanciness, since I am not a programmer.

**Comment by briis** [comment]
I am sorry, I am not a Homekit expert, so I suggest you ask in the Community Forum. I can say, that I added a G4 Pro and the G4 Doorbell to Homekit, and I do get some green on parts of the image when I click it in the Home App. But after 2-3 seconds it goes away and the image streams as it should.

**Comment by germanhans** [comment]
For now, I just disabled the top resolution of the RTSP streams in Protect. 4K and 2K aren't loved by the default setup I have, apparently. As soon as I did this, things are fine. Still haven't figured out how to enable the audio though. The cameras are just fine streaming 4K in the native Protect App. But, if you remove the option for a 4K RTSP stream, things are much better.

**Comment by briis** [comment]
Thanks for the info about the stream resolution. With regards to sound, I am not sure if Homekit supports AAC as sound format - this is what is send from HA - so that might be the reason for no sound.

**Comment by mrustenbach** [comment]
Hello - I am having the same issue as @germanhans. Half the screen is green on my G4 Bullet but perfectly fine on my G4 Doorbell. Waiting does not resolve the issue. About to test reducing RSTP resolution. Curious if this is a software related issue or an issue with the Home Assistant HW not being able to keep up?
