### ISSUE TITLE
Feature Request: Infrared switch

### ISSUE THREAD

**Issue by thomas70** [briis/unifiprotect#29]
Love to have a switch to turn on/off Infrared

**Comment by briis** [comment]
Hi,
That should be possible. The IR settings has 3 modes:
* auto
* auto (Filter only, no LED's)
* always enable

So the closest to full OFF, is the second mode *auto (Filter only, no LED's)* but what would you prefer for ON? *auto* or *always enable*?

**Comment by thomas70** [comment]
The Android APP har 4 modes:

![Screenshot_20200402-210654_UniFi Protect](https://user-images.githubusercontent.com/17246315/78291751-3e246100-7526-11ea-80bd-4f88278284f0.jpg)

**Comment by briis** [comment]
Yes, you are right. The same goes for the IOS App.Always Disable will be OFF. So next question: What should ON be equal to then: Auto or Always Enable? What's your preference?

**Comment by thomas70** [comment]
Im my case. I am struggling with som light that makes the auto not working. So Always Enable/Always Disable. But other could have other needs.
Also Always Enable / Auto could work for me

**Comment by thomas70** [comment]
Maybe a dumb question. Is it possible to make a input_select with 4 options ?

**Comment by briis** [comment]
Thanks for the answer. I think I will try and add 2 config options for the Switch, like:
```
switch:
  - platform: unifiprotect
    ir_on: <type always or auto>
    ir_off: <type always or led_only>
```
that way people can select themself.
As far as I know, you cannot add a input_select as a component, but I could make a Service where you can set the IR status, and then it is easy to make an input_select yourself.
I'll start the work and let you know when done.

**Comment by thomas70** [comment]
Thanks :-)

**Comment by briis** [comment]
This is now done. Should be available in HACS soon. See the README.md for more information on how to use. Let me know if you need changes.
I will close this for now, and feel free to reopen if needed.
