### ISSUE TITLE
Unifi Protect not showing in integration 

### ISSUE THREAD

**Issue by Whizbop** [briis/unifiprotect#290]
UDMP with unifi protect (latest stable). looking to have my G4 doorbell chime on my apple homepod mini.
I have Home Assistant with supervisor installed on a pi4 running.
I have HACS installed but under configuration add integration the UniFi protect doesn't show.

Things I have tried:
Reinstalling Hacs and hard refreshing, clearing cache.

I think I can install it manually but I would rather have ability to have it updated automatically.

Any suggestions? Thank you!

**Comment by briis** [comment]
Please read #262 in the Discussion Area. Below is an abstract:

> So once you select Unifi Protect in HACS, and install it, the only thing that happens is that the necessary files are copied to Home Assistant. Then you need to re-start Home Assistant, for the system to pick-up the new files. At this point, Unifi protect is now part of Integrations that can be installed from the Integrations page.

> But, this page often gets cached in your browser, so to ensure you can find Unifi Protect, go to the Integrations page, and do a hard refresh of your browser (CMD+R on a Mac).
Now press the button in the lower right corner named + ADD INTEGRATION, and search for Unifi Protect. It should now be available to configure.

Does this help?

**Comment by Whizbop** [comment]
It magically populated in hacs integration repository today. Guess it needed some time to pool the repository? Either way I was able to install it. Thank you for all you do!

**Comment by briis** [comment]
Wonderfull. Glad it worked out.
