### ISSUE TITLE
"does not support play stream service"

### ISSUE THREAD

**Issue by zkiifreak** [briis/unifiprotect#291]
Hi there
Really enjoy your integration! Thanks 👌
I'm trying to stream the camera stream through camera.play_stream service but I'm experiencing the following error:
`
2021-09-04 10:14:22 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2827719560] Error handling message: camera.uvc_g3_instant does not support play stream service`
I've enabled the `stream` integration in `configuration.yaml`.
Is this a non-implemented feature in the Protect integration or an error in HA?

**Comment by zkiifreak** [comment]
> This is supported and should work fine. I just tested by playing the stream from a G3 Flex to a Nest Hub.
> 
> Have you added the `stream:` to your `configuration.yaml` file?

As stated, yes I have :)
Might it be because I'm trying to play it on my LG WebOS TV?

**Comment by briis** [comment]
Sorry did not see that: 
> As stated, yes I have :)

Oh yes, LG TV's have an issue with casting. I have never gotten mine to work. This is a cast issue not related to this integration.

**Comment by zkiifreak** [comment]
> Sorry did not see that:
> 
> > As stated, yes I have :)
> 
> Oh yes, LG TV's have an issue with casting. I have never gotten mine to work. This is a cast issue not related to this integration.

OK - thanks for clarification :) I'll stop trying to make it work then :-P
Have a great day!
