### ISSUE TITLE
No Config Flow Executed on Installation

### ISSUE THREAD

**Issue by kedeshur** [briis/unifiprotect#298]
HASS Container version: core-2021.9.6
HACS: 1.15.2
UniFi Protect Integration: 0.9.0
Configuration / Prerequisites - Complete

I've tried uninstalling and installing HACS and Unifi Protect a few times now and I am unable to get the config flow to trigger on install. I have tried manually replacing the user_input in the config_flow.py with the desired values, looking at .storage/core.config_entries to see if the data is populated in there (it isn't), and a few other things. To be clear, after installing the Unifi Protect integration, a prompt never appears to fill out the required information within config_flow.py. The DEBUG logs look good and show it's downloading all the files from GitHub and saving them correctly in /config/custom_components/unifiprotect, and that it loaded them successfully.

```
2021-09-13 18:24:40 DEBUG (MainThread) [custom_components.hacs] <Integration briis/unifiprotect> Getting repository information
2021-09-13 18:24:40 DEBUG (MainThread) [custom_components.hacs] Did not update briis/unifiprotect, content was not modified
2021-09-13 18:24:40 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/briis/unifiprotect/v0.9.0/custom_components/unifiprotect/__init__.py
... 
2021-09-13 18:24:41 DEBUG (MainThread) [custom_components.hacs] Saving /config/custom_components/unifiprotect/util.py
2021-09-13 18:24:41 INFO (SyncWorker_4) [homeassistant.loader] Loaded unifiprotect from custom_components.unifiprotect
2021-09-13 18:24:41 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration unifiprotect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

Any other suggestions to try and get the config_flow.py file to trigger like it should on install? If not, does anyone have an example of what info and the format that gets populated in .storage/core.config_entries? Am I missing something else entirely??

**Comment by briis** [comment]
Can you confirm you followed the steps outlined in #262?

**Comment by kedeshur** [comment]
Hey @briis,

Confirmed. Here was my process up to the point I have installed Unifi Protect. I'm running in a container, so I do this after starting my docker image with:

0. `docker run -d --network=host --name homeassistant -v /home/pi/hass/config:/config --expose 8123 --restart=unless-stopped --privileged -e TZ=CST --device /dev/ttyUSB0:/dev/ttyUSB0 ghcr.io/home-assistant/raspberrypi4-homeassistant:stable`
1. `docker exec -it homeassistant bash` (https://hacs.xyz/docs/setup/download)
2. Then run `wget -O - https://get.hacs.xyz | bash -` 
3. Restart the docker container with `docker restart homeassistant` and restart the server via the Server Controls menu panel
4. Install the HACS integration (https://hacs.xyz/docs/configuration/basic)
5. Wait a bit for everything to install given GitHub rate limiting / downloading of 90ish repos
6. Install Unifi Protect (it does show up after waiting) through the HACS Integrations Page (this completes successfully per logs)
7. This is the step I'm stuck on since no options allow me to configure the Unifi Protect plugin. Is there a way to force this step if it doesn't happen via the UI? Or manually populate the .storage/core.config_entries?

Also, even if I can't get this working, where do I donate?! The software itself is cool and your response time here is totally unexpected. Thanks so much!

**Comment by briis** [comment]
Hi @kedeshur 
I am still not sure you are on the right page. When you are in Home Assistant click on the *Configuration* icon in the left menu (at the bottom). Then you get a new page, and here you click *Integrations*. When you are on this page, do a hard Refresh of your browser (CMD+R on a Mac), and then click the *+ ADD INTEGRATION* in the lower right of the screen. Here you can search for UniFi Protect.

Currently I don't do donations - but thanks for offering it. I get a lot og help from the community, so I am just happy to be able to give something back.

**Comment by kedeshur** [comment]
@briis,

Ah, you were right about #262. I was trying to configure it from HACS and not through the native HA Integrations after downloading it through HACS... PEBCAC fail and I really appreciate your patience and answering my question so quickly.
