### ISSUE TITLE
2FA?

### ISSUE THREAD

**Issue by ExR90** [briis/unifiprotect#300]
I'm unable to authenticate to my nvr. I suspect it's because I have 2fa on my ubnt account. Does the plug in support 2fa? I found a post that suggests it's just a matter of updating the authentication request adding the 2fa token.

https://community.ui.com/questions/Unifi-Protect-API-or-Motion-alerts-hit-API/b5c6cf44-651c-4751-98a8-c55d7ce9bd5f?page=9

**Comment by briis** [comment]
This Integration does not access the Internet at all, so it does not use UI's login method.
As stated in the README.md file, you need to create a Local User on your device, with admin rights, and use that account to login. There is no 2FA for local accounts

**Comment by ExR90** [comment]
Indeed that did work with local user. My bad. Well, if you ever wanted to include cloud accounts/2FA, allegedly there is the change to do so, allegedly :-)

Thanks
