### ISSUE TITLE
If I use any switch of the unified protect integration I get an Error

### ISSUE THREAD

**Issue by pschyrembel258** [briis/unifiprotect#303]
If I try to enable recording motion on my Lovelace switch. I become the following Error:
Fehler beim Aufrufen des Diensts switch/turn_off. Unifi Protect reported authorization failure on request: https://local IP of UDMP:443/proxy/protect/api/cameras/6140c2c60119fe0387000403 received 403
I've installed the integration with local user. Do I have to configure something else on the UDM pro? Portforwarding?
Thanks for your help.
Daniel

**Comment by briis** [comment]
Does the local user you have created have Admin Rights? Like you see below. This is needed for it to change settings in UnFi Protect.

<img width="389" alt="Skærmbillede 2021-09-27 kl  17 23 48" src="https://user-images.githubusercontent.com/24776272/134938018-7c69dab0-340c-433a-bbfd-9a14c260360e.png">
?

**Comment by pschyrembel258** [comment]
That was the hint. I've had only admin rights at the network section. Thank you very much. Problem solved.
