### ISSUE TITLE
Can't get streams

### ISSUE THREAD

**Issue by gohassgo** [briis/unifiprotect#31]
I've set this up with HACS and a Cloud Key G2+ and camera still images show in Lovelace and they refresh regularly. I've enabled the medium quality RTSP stream for each camera.

Is there another required setting I missed somewhere?

Thanks!

**Comment by zacs** [comment]
It's unclear what your problem is. What do you mean by "can't get streams"? 

Have you added 

```
stream:
```

to your config?

**Comment by gohassgo** [comment]
I am only able to get still images in HA. When clicking on a camera card's image, I get a pop-up window that I think should be a live stream, but instead only has the title and a gear icon. I did not have `stream:` in config as I'm not on a Mac, but I just added it and restarted and see that this does enable streaming in the picture-entity card. Woohoo! 

The picture-entity card has an option for setting the camera to "live." Here's [an excerpt](https://www.home-assistant.io/integrations/stream/#streaming-in-lovelace) from the stream integration page:

> Streaming in Lovelace
> As of Home Assistant version 0.92 you can now live-stream a camera feed directly in lovelace. To do this add either picture-entity, picture-glance or picture-elements, set camera_image to a stream-ready camera entity and set camera_view to live in one of your Lovelace views.

Just a quirk with the live stream and the picture-entity card--"live" is only refreshing the image every 11 seconds. If I leave the setting on Auto, clicking the preview/still image pops-up the live view window and has a "Preload stream" checkbox in the upper-right corner.

**Comment by gohassgo** [comment]
I had opened a case in home-assistant/core as this all started with trying to stream to an Echo Show (it's supposed to be enabled in 0.108.0b2), but I closed it since I wasn't getting any streams at all.

https://github.com/home-assistant/core/issues/33675

I'm not sure at this point if this is a core issue, something with this integration, or both.

Thanks

**Comment by zacs** [comment]
Nice, glad it worked out. A quick tip, in case you plan on viewing the stream on any devices like Google Homes, it really helps to check the "Preload stream" checkbox. It takes load times from ~15-20sec to ~2-3sec. I have a different setup than you obviously (GH vs Echo) but mine was pretty flakey until I checked that box for my most-used cameras. It'll definitely take up CPU cycles though, so if you're on a Pi it might not be the best.

**Comment by gohassgo** [comment]
This started working after a subsequent HA Core update, but I'm not sure which one...
