### ISSUE TITLE
Improve support for UP-Sense

### ISSUE THREAD

**Issue by Madbeefer** [briis/unifiprotect#315]
I am not sure if its by design or not, but my UFP Sense sensors no longer show up in the integration. I've tried removing them from my cloud key and adding them back in, still nothing.

**Comment by Madbeefer** [comment]
I got in and ran
 unifi-protect generate-sample-data -o /config/ufp-data --actual --w 300 -U (USER) -P (PASSWORD) -a 192.168.x.x
and I get bash : !@ event not found

**Comment by AngellusMortis** [comment]
If your username is an email, put it on quotes "

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AngellusMortis** [comment]
Actually, if you just remove the username (`-U`) and password (`-P`) options, it will prompt you for them interactively and then you do not need to worry about special characters in your username/password.

**Comment by Madbeefer** [comment]
Ok I got the data files, but I can't find my user name or password in any of them..

**Comment by AngellusMortis** [comment]
You password is not in any of the files. The only sensitive credentials in files is your `accessKey` in `sample_boostrap.json`. 

Your username should be inside of `sample_boostrap.json` as well under `users`. You can safely delete that whole block as we do need your user data to debug sensors.

**Comment by Madbeefer** [comment]
Ok done, I'll try to attach them on the home assistant forum .

**Comment by AngellusMortis** [comment]
Awesome, got the date. From what I could gather from the data, it looks like you only have the Temperature sensor enabled? 

So that means for your configuration, you should have:

* sensor: battery level
* binary_sensor: is battery level low?
* sensor: current temperature (C)
* binary_sensor: is LED enabled?

It looks like there was a single event that happened while you were gathering data. The temperature when from 24.51 C to 25.33 C.

**Comment by Madbeefer** [comment]
The motion sensor should have been enabled as well. I can go and turn on all the sensors and run it again that way you can see all of data from all the sensor.

**Comment by AngellusMortis** [comment]
The motion settings definitely where set to off.

```json
    "motionSettings": {
        "isEnabled": false,
        "sensitivity": 100
    },
```

And yeah, if you want to turn _everything_ on and then generate data again (make sure you try to also trigger the events!), that would be awesome.

**Comment by AngellusMortis** [comment]
Also, if you can change the "thresholds" for one of the seconds, that would also be great. It looks like there is a low and high threshold of some kind of the Light settings and Temperature settings. 

A screenshot of the settings in Protect would possible be help for me to understand how to map some of the raw values to what they actually do in Protect.

**Comment by Madbeefer** [comment]
I'll see what I can do.

**Comment by Madbeefer** [comment]
Ok theres some screen shots and more data

**Comment by briis** [comment]
Thanks for the data @Madbeefer. It has been so long since we last worked on the UFP Sense device, and your title says they they are no longer shown, so can you confirm that at a point in time they did show up? If yes, can you remember what version of the Integration that was?
It is just when I look through the code, they should not show up, but we might have cleaned that part out by accident.

**Comment by Madbeefer** [comment]
Hmm I want to say it worked fine until I renamed it from its default name. I tried resetting it to default again and it wouldn't come back. So it was whatever non beta version about two weeks ago..

**Comment by briis** [comment]
Thanks.

**Comment by briis** [comment]
Another question: This can be implemented in a few ways, due to the number of sensors in that one physical device.
My suggestion is that we create a `binary_sensor` for the each physical device for the following events:
- Motion
- Door Open/Close
- Alarm On/off

Then we could also create a `sensor` for temperature, humidity and ambient and that would then 6 sensors for each physical device. Or we could attach the temperature, humidity and ambient values as attributes to the binary sensors.

What would you prefer?

**Comment by Madbeefer** [comment]
I like the binary_sensor for the events and separate sensors for the temp, humidity and ambient.

**Comment by briis** [comment]
So I have just done a very rough initial implementation, and before I add more code I need to know if this works and gives my intended result. As none of us have the Sense device we need you to do the testing, and that means copying files from this Github and overwriting what you have now in your `custom_components/unifiprotect` directory in your HA installation. I hope you are OK with this. If the integration stops working, you can always go to HACS and click Reinstall to get the latest working version.

So for the initial test I want you to make sure you are running the version 0.10.0-beta.3. If you do that, then download the latest files from [this Github](https://github.com/briis/unifiprotect/archive/refs/heads/master.zip) and then copy all the files from `custom_components/unifiprotect` to the same directory on you HA installation. (You don't need to copy the translations directory.)

The restart HA, and what I would expect to see now, are 3 new binary sensors per UFP Sense device you have. 1 for motion, 1 for door open/close and one for alarm. If we are lucky the motion sensor might actually change the state when there is motion, the two others will always be off, as we need to implement the event.

Please take a screenshot of the STATES page under the development tools in HA, just filtering on these devices, so that I can see what gets in to HA.

**Comment by Madbeefer** [comment]
Done, and the UFP Sense didn't come up.

**Comment by briis** [comment]
Hmmm....
Could you turn on the debug log and see if something shows up in the log file

**Comment by Madbeefer** [comment]
This is what I've found so far.
Logger: homeassistant.setup
Source: setup.py:316
First occurred: 3:32:30 AM (6 occurrences)
Last logged: 3:32:30 AM

Unable to prepare setup for platform unifiprotect.binary_sensor: Platform not found (cannot import name 'ENTITY_CATEGORY_DIAGNOSTIC' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
Unable to prepare setup for platform unifiprotect.sensor: Platform not found (cannot import name 'ENTITY_CATEGORY_DIAGNOSTIC' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
Unable to prepare setup for platform unifiprotect.switch: Platform not found (cannot import name 'ENTITY_CATEGORY_CONFIG' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
Unable to prepare setup for platform unifiprotect.number: Platform not found (cannot import name 'ENTITY_CATEGORY_CONFIG' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
Unable to prepare setup for platform unifiprotect.select: Platform not found (cannot import name 'ENTITY_CATEGORY_CONFIG' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

**Comment by AngellusMortis** [comment]
@briis's local code likely has stuff for the `.11` beta. So you probably need that installed to use his code.

**Comment by Madbeefer** [comment]
I put 
logger:
  default: debug

in my config and it didn't change what I found in the logs. I am sure I am missing something.

**Comment by briis** [comment]
Hi @Madbeefer 
@AngellusMortis is right, I put stuff in there that need 2021.11 of HA. This code has now been removed, so could you download again from Github and overwrite the following 5 files:
- `binary_sensor.py`
- `sensor.py`
- `switch.py`
- `select.py`
- `number.py`
 
Then restart HA and let us now what you find.

**Comment by Madbeefer** [comment]
It shows up now. I can see a door sensor, a motion sensor and a safety sensor.. They do not change states though.

**Comment by briis** [comment]
Perfect, then we are on the right track.
After I posted the above I also added the file `manifest.json` as @AngellusMortis found a bug in the IO module, that has now been fixed. Could you edit the file `manifest.json` and change the value `"pyunifiprotect==0.35.3"` to `"pyunifiprotect==0.35.4"`. The restart HA and check if motion and maybe door open events are happening.

If you already have 0.35.4 in the manifest file, then you don't need to do anything - then I have to work on the event logic

**Comment by briis** [comment]
Found another thing that causes issues on a HA installation below 2021.11. Could you download the `camera.py` file also and replace that. Remember to restart.

**Comment by Madbeefer** [comment]
I do have a instance running 2021.11, I can switch to using that one since it should be coming out of beta soon

**Comment by briis** [comment]
It was actually great you did not run on the 2021.11 version, as this helped me spot the incompatibility with older versions, that I had not thought of. I have now changed the files above again, so that if you run on 2021.11 you will get the new Entity Category division, but if you are not, it will just be ignored.

Most important is now to check if pyunifiprotect V0.35.4 changed the binary sensor state for door and motion sensor.

**Comment by Madbeefer** [comment]
I made the edit and now the integration won't load.

**Comment by briis** [comment]
Can you post the output of the HA Log? Also did you replace the camera.py file?

**Comment by Madbeefer** [comment]
here are the logs
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 12:06:29 AM (3 occurrences)
Last logged: 12:06:35 AM

Unable to install package pyunifiprotect==0.35.4: ERROR: Could not find a version that satisfies the requirement pyunifiprotect==0.35.4 (from versions: 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.14, 0.15, 0.16, 0.17, 0.18, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.19.5, 0.19.6, 0.19.7, 0.19.8, 0.19.9, 0.20.0, 0.21.0, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 0.23.0, 0.23.1, 0.24.0, 0.24.1, 0.24.2, 0.24.3, 0.24.4, 0.24.5, 0.24.6, 0.24.7, 0.24.8, 0.24.9, 0.24.10, 0.25.0, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.26.4, 0.26.5, 0.26.6, 0.26.7, 0.26.8, 0.27.0, 0.28.0, 0.28.1, 0.28.2, 0.28.3, 0.28.4, 0.28.5, 0.28.6, 0.28.7, 0.28.7.4, 0.28.8, 0.29.0, 0.29.1, 0.29.2, 0.30.0, 0.30.1, 0.30.2, 0.30.3, 0.30.4, 0.30.5, 0.30.6, 0.30.7, 0.30.14, 0.30.15, 0.30.16, 0.30.17, 0.30.18, 0.30.19, 0.30.20, 0.31.0, 0.31.1, 0.31.2, 0.31.3, 0.31.4, 0.31.5, 0.31.6, 0.31.7, 0.31.8, 0.31.9, 0.32b1, 0.32.0, 0.33.0, 0.33.1, 0.33.2, 0.33.3, 0.33.4, 0.34.0, 0.34.1, 0.34.2, 0.34.3, 0.35.0, 0.35.1, 0.35.2, 0.35.3) ERROR: No matching distribution found for pyunifiprotect==0.35.4 WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.


Logger: homeassistant.setup
Source: setup.py:178
First occurred: 12:06:35 AM (1 occurrences)
Last logged: 12:06:35 AM

Setup failed for unifiprotect: Requirements for unifiprotect not found: ['pyunifiprotect==0.35.4'].

**Comment by Madbeefer** [comment]
the camera file was replaced.

**Comment by briis** [comment]
Got it. You were just too fast. It takes a little while before the new version gets recognized in pypi. Just restart HA again and it should work.

**Comment by briis** [comment]
Btw. you posted the below screenshot. Could also click on the Settings icon in the top and post what you see here?
<img width="300" alt="Capture1" src="https://user-images.githubusercontent.com/24776272/139635795-4e4d46b1-01c9-47b1-8dbb-5a469549497f.PNG">

**Comment by Madbeefer** [comment]
I am still getting the same error.. I'll try again later.
<img width="301" alt="Capture6" src="https://user-images.githubusercontent.com/34440759/139636166-45657e5f-9f5b-4900-bd3a-07e287fa18f7.PNG">

**Comment by Madbeefer** [comment]
<img width="272" alt="Capture7" src="https://user-images.githubusercontent.com/34440759/139636230-c7db3b20-1a6f-4b93-b04b-74f2f03e59a4.PNG">

This is the rest.

**Comment by briis** [comment]
Thanks for the above. There are a couple of settings that could be changed from the HA UI, but for the first release we will concentrate on getting the sensors and binary_sensors added.

The 0.35.4 version is existing, so it must be some kind of caching issue. Try and delete the `__pycache__` directory in `custom_components/unifiprotect`, restart HA and see if this works.

<img width="824" alt="Skærmbillede 2021-11-01 kl  08 26 46" src="https://user-images.githubusercontent.com/24776272/139636690-6895df88-c9e7-4a8c-bfee-23dcd9208219.png">
.

**Comment by Madbeefer** [comment]
deleted and rebooted, same error.

**Comment by briis** [comment]
Just to make sure nothing got wrong in the edit. Could you download the `manifest.json` file from this Github and replace it in your directory. I know it works as I have tested it on 3 different HA instances.

**Comment by Madbeefer** [comment]
Deleted everything and copied over new from github. Still same error.

**Comment by briis** [comment]
I have no clue whats going on - it should just work. Just for the fun of it, if you change it back to 035.3 will it then start?

**Comment by Madbeefer** [comment]
Ok I was able to get it to start, I had to delete it a few times and restart even more.. I did change it back to 035.3 and I'm back to where I was before when the entities wouldn't change state.

**Comment by briis** [comment]
This is a caching issue somewhere. Anyway, let us leave it there for now, I will do a couple of changes anyway the next few days, and then I will let you know when you can try again with hopefully working binary_sensors and some sensors for the temp, lux and other values.

**Comment by Madbeefer** [comment]
Ok no problem, let me know if theres anything you need me to do.

**Comment by briis** [comment]
I have now made some edits and the sensors you see now is what I will implement until I am convinced that this device will actually ever hit the shelves. It has been without any updates for the last 8 month, and it might because of the component shortage ww but it does mean that there are very few units out there.

What you will see with this release will still need some tweaking, and I will do that, so that we have a working version.

Please download all the files again, and then copy from the `custom_components/unifiprotect` to the `custom_components/unifiprotect` in your HA instance and restart HA.

What I hope you get is:

````
Binary Sensors:
  - motion
  - door
  - battery_low
````
I have removed the alarm sensor again, as I can't see where it would get its state from in the current dataset

````
Sensors:
- battery_level
- light_level
- humidity_level
- temperature_level
- ble_signal (Bluetooth Signal Strength)
````

It has to pull pyunifiprotect V0.35.5, which was build 18 hours agao, so I do hope it works this time.

**Comment by Madbeefer** [comment]
Ok its looking better. The temp sensor seems to work, it shows Celsius instead of Fahrenheit. Motion sensor still doesn't change states along with the door sensor.

**Comment by briis** [comment]
Good. It means the base structure is OK. I will work on the event handling and get the Temp Sensor to reflect imperial or metric units. I will let you know when there is something new to test.

In the meantime: Could you go to *Developer Tools* in your HA instance and then STATES and see if you can filter out the sensors and binary sensors for this. Then take a screenshot so that I can see how it shows up in HA.

**Comment by Madbeefer** [comment]
<img width="556" alt="Capture8" src="https://user-images.githubusercontent.com/34440759/139809788-3f2cbb24-5efd-4b40-85c1-9b569b50f5d9.PNG">
is that what your looking for?

**Comment by briis** [comment]
Yes that will work, or you could go further down to the *Current Entities* and filter on these rows, so you get something like the below. This might make it possible to see them all. Instead of the attribute filter Unifi you might be able to use UFP-SENSE
<img width="1004" alt="Skærmbillede 2021-11-02 kl  09 16 47" src="https://user-images.githubusercontent.com/24776272/139810187-9ae6191e-6d70-4def-bacb-637799b0f616.png">
:

**Comment by Madbeefer** [comment]
<img width="963" alt="Capture9" src="https://user-images.githubusercontent.com/34440759/139810885-befa0909-9134-4737-8f36-fe54efedb3c6.PNG">
<img width="943" alt="Capture10" src="https://user-images.githubusercontent.com/34440759/139810887-47b91fff-c0cf-4dc5-a8ea-5ca57a8f998b.PNG">

That should be all of them

**Comment by briis** [comment]
All sensors should now show the correct unit and the temperature sensor should convert to F if you use imperial units. You can download the updated `sensor.py` file and replace the one in your HA directory. 
I will now work on the events for the binary sensor, which can take a bit longer.

**Comment by Madbeefer** [comment]
Those are now correct.

**Comment by briis** [comment]
We are still not getting all the events in but tried to fix the motion event. Could you pull the following 2 files: `binary_sensor.py` and `manifest.json`, replace them in your HA installation, restart HA and see if this has any effect on Motion detection?

**Comment by briis** [comment]
From the sample data I have, I am missing event information for motion and door open. So could I ask you the run the function to generate sample data again, and this time make sure that you move in front of the sensor while it is running. And also, even though this might not be used as a open/close sensor, could you take the magnet and make sure to simulate a open/close by moving the magnet in front of the sensor. Then send the data to us again.

Thanks

**Comment by Madbeefer** [comment]
When I collected the data the last time I was actually handling the sensor since its not mounted and I was running a magnet around it periodically. I can try again.

**Comment by briis** [comment]
Just make sure that the *Events to Capture* settings have enabled all services. Maybe also try and lift the sensor to see if get a vibration alarm. Thanks

Btw. Download the two files above before capturing the data. The manifest file will download the latest version of the IO module.

**Comment by Madbeefer** [comment]
Ok downloaded the new files and things are going kind of nuts...the door and motion seem to be tied together and the battery goes normal low repeatedly..

I'll collect some data.

**Comment by briis** [comment]
> the door and motion seem to be tied together

Good :) It means it is picking up the events. That why I need the data, so I can separate them.

**Comment by Madbeefer** [comment]
Ok well I've tried a couple times to I keep getting this same message
<img width="626" alt="Capture11" src="https://user-images.githubusercontent.com/34440759/140040307-d832f9d3-5048-4b5a-b4fc-d682c9c7042b.PNG">
.

**Comment by briis** [comment]
Ok, I will need @AngellusMortis to look at this.

**Comment by briis** [comment]
Just double checking, you did supply username and password?

**Comment by Madbeefer** [comment]
Yup, I have the command line I used saved so its the same one

**Comment by Madbeefer** [comment]
I deleted the user name and password from the command line, entered them when prompted, same thing.

**Comment by briis** [comment]
OK thanks. I need @AngellusMortis to look at this, as this is his code. We will be back when fixed.

**Comment by AngellusMortis** [comment]
@Madbeefer Did you accidently use the wrong URL and is everything running? It is trying to make a request to `https://192.168.15.2:443`. Is that the URL toy your Unifi console?

**Comment by AngellusMortis** [comment]
Also, if you plan to run commands often to help us debug stuff, you may want to consider making a `.env` file with your details in it as described in the pyunifiprotect README: https://github.com/briis/pyunifiprotect#authenticating-with-your-local-protect-instance

**Comment by Madbeefer** [comment]
@AngellusMortis Yes that is the correct address, I have a cloud key gen 2 not a UDM Pro. I'll take another crack at it when I get off work tonight.

**Comment by briis** [comment]
So I made some modifications to the binary sensors. Could you pull the latest version of `binary_sensor.py` and `manifest.json` from this Github, and overwrite the ones in your current HA installation. Restart HA and let me know if the sensors detect changes.

**Comment by Madbeefer** [comment]
Ok the binary's are still changing at the same time when they decide to change, I don't know whats triggering them now.. I tried to get a log set again, still same error.. I did get one file, which I'll attach to a message.

**Comment by Madbeefer** [comment]
<img width="910" alt="Capture12" src="https://user-images.githubusercontent.com/34440759/140294703-e4fb32a3-0318-414b-82cf-575c6fc22610.PNG"
<img width="944" alt="Capture13" src="https://user-images.githubusercontent.com/34440759/140294719-ecc47fe8-2f7e-44ef-85cb-e05808e32ada.PNG">
>

**Comment by Madbeefer** [comment]
<img width="944" alt="Capture13" src="https://user-images.githubusercontent.com/34440759/140294803-4e2488d0-7491-4140-84b6-f29488ab2408.PNG">

**Comment by Madbeefer** [comment]
<img width="910" alt="Capture12" src="https://user-images.githubusercontent.com/34440759/140294853-39afb335-e2e0-4326-94e1-02df6a5652cc.PNG">

**Comment by briis** [comment]
Thanks - Damn it is tough to do this without access to the device!

I can see there is still some old stuff around from the first try, could I get you to delete the integration, and then just re-add it. That would get rid of the binary_sensor.safety....

Just to make sure there is a clean set of sensors.

**Comment by Madbeefer** [comment]
Too bad you're in Denmark I have two I could lend you one.

**Comment by Madbeefer** [comment]
I'm reinstalling and giving it another go.

**Comment by Madbeefer** [comment]
Shipping wasn't as bad as I thought..so it could be an option.

**Comment by briis** [comment]
I am happy to pay for all the cost in advance if you are willing to lend it to me.

**Comment by briis** [comment]
I can even buy it from you, if you want me to do that?

**Comment by Madbeefer** [comment]
<img width="261" alt="clear" src="https://user-images.githubusercontent.com/34440759/140298754-95806cee-2b2c-4ea1-aae4-a3c32899957c.PNG">

**Comment by Madbeefer** [comment]
<img width="282" alt="motion" src="https://user-images.githubusercontent.com/34440759/140298790-a4c5710c-7984-495e-85c9-3a8fdf8a5dbf.PNG">

**Comment by Madbeefer** [comment]
Ok thats what I get when it goes from motion to motion

**Comment by Madbeefer** [comment]
I got a couple plans for them, so I don't think I want to sell them, but I'd be open to shipping.

**Comment by briis** [comment]
Got it. At least you get some changes in the events, now I need to get them separated. And once this is done, I would really love to add some options for changing some of the settings, but that is another journey.

> I got a couple plans for them, so I don't think I want to sell them, but I'd be open to shipping.

No problem, If I can borrow one for a few weeks, I should be able to get this done. So if you are OK with it, let me know what express shipping cost, and I can transfer the money to you on Paypal if you have such an account.

**Comment by briis** [comment]
Btw. Later today I will release 0.10.0-beta.4 which includes all we have here, plus a new trial on the update of the binary sensors. So when that comes out, please update to that, so that you are on par.

**Comment by Madbeefer** [comment]
I upgraded and tried to generate logs on both my HA instances I still got the same error when trying to generate the data.

**Comment by briis** [comment]
Ok, never mind for now. Do you see any changes in the binary sensors? Are they still updating simultaneous?

**Comment by Madbeefer** [comment]
Yes, the battery low, door and motion still seems to change with the motion sensor.

**Comment by briis** [comment]
I will give et one more go, and if that does not work, I will leave this until I can get a my hands on a device. Looking at the code it should work, but as you say it doesn't and it is hard to debug without looking at the values coming in.

**Comment by Madbeefer** [comment]
I'm going to try a few things with my cloud key 2 and see if I can get it to work.

**Comment by Madbeefer** [comment]
Is there a way to get the logs with SSL off?

**Comment by Madbeefer** [comment]
<img width="585" alt="Capture123" src="https://user-images.githubusercontent.com/34440759/140606564-16d2d373-cccd-4d04-a7b0-0ff7cc8d5ea7.PNG">

I thnk this might be part of the problem.. At the end of my error trying to get the logs it says it can't get a response from that address and thats what I see when I go there.

**Comment by briis** [comment]
I don't think this is an issue, as my setup responds in the same way. There is a unifi.local certificate which is not validated. But I get the log files without issues.

**Comment by Madbeefer** [comment]
Hmm, looks like theres a new beta for protect.. maybe that might help.

**Comment by briis** [comment]
It should not make a difference, but I am running 1.20.0-beta.7

**Comment by Madbeefer** [comment]
I just went from beta 5 to 7, didn't make a difference.. my camera is currently disconnected. I wonder if thats causing an issue..

**Comment by Madbeefer** [comment]
Nope..

**Comment by Madbeefer** [comment]
Message me your address and I'll see what shipping will cost.

**Comment by briis** [comment]
I send it to you on the HA Community PM.

**Comment by AngellusMortis** [comment]
Removing bug label since you two seemed to have gotten the sensor in a better state. I will leave the issue open though since I think @briis has more planned once we get our hands on a sensor.

**Comment by AngellusMortis** [comment]
@Madbeefer, are you able to test 0.11-beta3? We want to make sure nothing was broken for the Sense.

**Comment by Madbeefer** [comment]
It looks like the door sensor is no longer tied to the battery low alarm/warning and the motion detection sensor. The temp an lux sensors don't appear to be correct though.. I'll watch them over the next day and see if they make sense.

**Comment by AngellusMortis** [comment]
0.12.0-beta10 added full support for UP-Sense devices. It is recommended you remove and re-add your UniFi Protect integration so the entities can be created fresh with all of the features correctly.
