### ISSUE TITLE
Motion Sensor entity does not survive Device becoming unavailable

### ISSUE THREAD

**Issue by jb123567** [briis/unifiprotect#317]
If a camera becomes unavailable, for example due to a firmware update or a network update the motion sensor entity will no longer update and HA needs to be restarted.

**Comment by AngellusMortis** [comment]
This should be resolved in the 0.11 beta. Are you able to install it and test it out?

**Comment by jb123567** [comment]
Already installed, will let you know if the error occurs again!

**Comment by AngellusMortis** [comment]
It sounds like the issue is fixed since we have not heard back. I am going to close this for now and if you have any more issues, let us know!
