### ISSUE TITLE
doorbell connects and disconnects throughout the day

### ISSUE THREAD

**Issue by Alain-GitHA** [briis/unifiprotect#319]
### Home Assistant Version?

2021.10.6

### UniFi Protect Version?

1.19.2

### UniFi Protect HA Integration version?

0.9.1

### What happened?

I have my G4 Doorbell camera installed and running for 2-3 weeks, before I setup and configured the HA Unifi Protect integration, and the doorbell unit was always on. Now the G4 Doorbell goes offline and back online few times a day.

This maybe an issue with the unit itself, rather than the integration, as I'm able to do most of what I need from the integration. However, I wanted to see if there are others with a similar problem.
See UniFi Protect log from the last couple of days.

![image](https://user-images.githubusercontent.com/93016553/139562089-8787c322-f6ce-4d91-8cd8-22fb498633df.png)

I will disable the integration for few days, to see if the unit remain stable, as it could be the unit or the wifi connection causing the problem.

Regards,
Alain

**Comment by bdraco** [comment]
That looks like a wifi stability issue. Consider putting the doorbell on its own ssid with 5ghz disabled

**Comment by Alain-GitHA** [comment]
Hi bdraco, I have not though of that possibility.
I have changed the Wifi connection to th 2.4GHz for the G4 doorbell, and it looks far more stable with a stronger connection and faster updates.

Thanks so much for your suggestion. I will monitor the system for the next couple of days.

Cheers,
Alain

**Comment by briis** [comment]
@Alain-GitHA How is it going with this one - did changing the WiFi make it more stable?

**Comment by Alain-GitHA** [comment]
Hi Briis,
Thank you for the follow up.
I have changed the device to a 2GHz band, and the connection is a lot more stable, and the drop outs have decreased. However, they still occur.
![image](https://user-images.githubusercontent.com/93016553/140024460-7112193f-8ab8-4564-acda-1067ed85c478.png)
![image](https://user-images.githubusercontent.com/93016553/140024524-52ee9c10-b4cc-4e72-aa50-d66e3d3f9c7e.png)

Open to other suggestions...

Regards,
Alain

**Comment by briis** [comment]
Basically this is not an issue with this Integration, but as bdraco wrote above this is an issue with your network. 
My doorbell moves between 60% to 100% WiFi Experience, but it does not disconnect. Would it be possible to move the Access Point so that it gives better coverage for the Doorbell?

**Comment by Alain-GitHA** [comment]
Understood. I will run few other tests as well. Having said that, my doorbell remains constant on 100% WiFi experience. I cannot relocate the U6-Lite from downstairs, however it is 6-7 meters away from the doorbell (plus the wall).
Thank you for your time and help.
Alain

**Comment by briis** [comment]
Just a thought - Do you have more than one AP? If so, are you sure the Doorbell is connecting to the closest one? In the latest version of the UniFi Controller, you can lock a device to a specific Access Point, so that whenever you update devices or an AP reboots, the Doorbell will attach to that specific AP again.

**Comment by Alain-GitHA** [comment]
That's a good idea. Thanks Briis.
I will go over the settings and see if I can lock the doorbell to the AP downstairs.
Perhaps there is a way to configure a log for the device, and see what it does over a week.
Cheers,
Alain

**Comment by briis** [comment]
Good luck. Try and browse the [UI Forum](https://community.ui.com/questions) also, I have seen other people having the same issues.

I will close this issue now.
