### ISSUE TITLE
Slow w/ G4

### ISSUE THREAD

**Issue by VinistoisR** [briis/unifiprotect#32]
I have this working on a couple of HA installs and its fantastic.  One new install with some G4 cameras and its very slow.  When loading the page, the images are just gray boxes for ~10s, and similarly takes ages to pull up the full view. Preload stream is enabled and working.   I tried to set the cameras down to 10fps and reduce the bit rate, but it seems to make no difference. 

Is there anything obvious I could be missing that would affect the performance this way?

**Comment by briis** [comment]
I have a couple of G4's also, and I agree with you, loading the image can be a bit slow. It might be because of the size of the image from these 4K cameras. I'll look in to it, and see if I can find a way to speed up the proces.

**Comment by briis** [comment]
Hi @VinistoisR 
I think I might have found a solution, but before I do all the work, could you test that you also see improvements in load time of the image. Please download the file `custom_components/unifi_protect/unifi_protect_server.py` from the `dev` branch and overwrite the file you currently have on your system. Restart Home Assistant and let me know how that goes?

What I did, is I hardcoded the image size to 1024x768, which gives a very little file to download. If this works, I will give you the option of configuring the size your self, to find the size that works for you.

**Comment by VinistoisR** [comment]
its better, yes, maybe halfed the loading time.  But still nowhere near my other installations, which pop up immediately. 

With your new version the aspect ration is no longer correct (the cameras look squished horizontally)

There are 6 cameras, the first one appears immediately (G3 Pro).  The others take about 5-6 seconds, and in the meantime I get a grey block.   On my other installs, I never see the grey block.

**Comment by briis** [comment]
I made some further adjustments that should fix the Aspect Ratio. I now use the same sizes as the Unifi Protect Web App uses, and on my installation it looks correct. Please download the same file from the DEV branch.
I only have 3 Cameras, 2 G4 Pro's and 1 G3 Flex. When I attach each camera to a Picture Glance Plugin, they load immediately. (I run HA on an Intel NUC)

**Comment by VinistoisR** [comment]
Big improvement, thank you.  I came to the site of the installation and the streaming is indeed very fast now.   If only we could get rid of the time delay, but I think that's part of the stream module.

**Comment by briis** [comment]
Great. I will include this in a new release 0.1.5. And with regards to the delay, I see the same stream delay, even though I access a camera directly, so I also think this has to do with the HA stream module.
