### ISSUE TITLE
After updating Protect, HA core has to be restarted to get rid of warning.

### ISSUE THREAD

**Issue by Calimerorulez** [briis/unifiprotect#321]
### Home Assistant Version?

2021.10.7

### UniFi Protect Version?

1.20.0-7

### UniFi Protect HA Integration version?

v0.10.0-beta.3

### What happened?

Not exactly a bug, but each time I upgrade Protect, I have to restart HA core to get rid of the following warning:

`WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling`

### Relevant log output

```shell
WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
```

**Comment by AngellusMortis** [comment]
You are required to restart Home Assistant after upgrading Protect anyways. HACS should be telling you that.

**Comment by AngellusMortis** [comment]
I did confirm this behavior when I just upgraded to `beta.7`. It should definitely be automatically reconnecting the WS when it comes back online.

**Comment by briis** [comment]
I can confirm this too. A Reload from the UniFi Protect integration on the Integration Page is enough though, you don't need to restart HA Core

**Comment by briis** [comment]
Could you look at this @AngellusMortis ?

**Comment by AngellusMortis** [comment]
I was about to. Just pushing up something from the new upgrading to the new beta version.

**Comment by AngellusMortis** [comment]
@Calimerorulez I am going to do a head and close this one in favor of https://github.com/briis/unifiprotect/issues/297.

We have some improvements in the pipeline I will post in that issue once they go out. Just want to combine the tracking of the issues.

**Comment by vandalon** [comment]
> We have some improvements in the pipeline I will post in that issue once they go out. Just want to combine the tracking of the issues.

Hi, Are the mentioned improvements already pushed? I too am have the same issues. Reloading the integration fixes it, but somehow WebSocket does not reconnect automatically.

**Comment by AngellusMortis** [comment]
Search is your friend. https://github.com/briis/unifiprotect/issues/441

**Comment by vandalon** [comment]
Thanks, I did see that issue, but was not sure if it was the same thing. I've updated to the latest beta and will monitor :)

**Comment by vandalon** [comment]
Hi, I've tested with the lastert beta (12.0-beta8) and still the binary sensor stops working after a while and logs show ```Websocket connection not active, failing back to polling```
