### ISSUE TITLE
UniFi Protect Version is not supported by this Integration

### ISSUE THREAD

**Issue by debiano82** [briis/unifiprotect#322]
### Home Assistant Version?

2021.11.0

### UniFi Protect Version?

1.19.2

### UniFi Protect HA Integration version?

0.10.0-beta.3

### What happened?

UniFi Protect Version is not supported by this Integration

**Comment by AngellusMortis** [comment]
Beta versions of this integration are only for if you are running the matching Unifi Protect beta. 0.10 will required UFP version 1.20 or newer. 

Please disable beta for the HACS integration and downgrade to 0.9.1. At least until 1.20 for UFP hits GA.

**Comment by debiano82** [comment]
after downgrade i have same problem.

**Comment by briis** [comment]
You have to go in to HACS, find the Unifi Protect Integration, click the three dots in the lower right corner, and then select Reinstall. Here you select 0.9.1. When this is completed you must restart Home Assistant, and then install again from the Integrations Page.

**Comment by debiano82** [comment]
Tnx !

**Comment by briis** [comment]
If it is running again, please close the issue.
