### ISSUE TITLE
Ability to change the hostname/port for UFP

### ISSUE THREAD

**Issue by AngellusMortis** [briis/unifiprotect#323]
### New Feature

It would be great to be able to change the hostname/port/password for UFP without removing the integration. 

I just bought and migrated to a UNVR Pro from a UDM Pro and I was able to transfer my installation for Protect, but for HA I had to manually edit the underlaying HA config to update it since I did not want to have to set every all of the entities back up since they had not changed. Editing the HA raw config worked like a charm, but it would have been great if it could have been done via the UI.

It is something that would _only_ be safe to do if you did directly migrate your Protect instance, so limit useful-ness. Maybe having to edit the raw config is the best choice for more advanced users.

**Comment by briis** [comment]
The issue is that the MAC Address of the UFP is used to to create unique id's and thus this cause some dead devices in HA. Creating a block of code to change that, might not be worth the effort. Port, Username and Password can be easy done, it is just adding them to the options part of the config flow.

**Comment by AngellusMortis** [comment]
All of the devices were fine for mine. The actual camera entities got got duplicated, but those were really easy to just remove the old ones for. All of the "not camera" entities like the sensors and everything were fine. I do have two NVR devices now though (one for my UNVR-PRO and one for my UDM-PRO).

**Comment by briis** [comment]
Yes the double cameras and the left-over UDMP is what I see as the issue. Honestly, unless you have customized the entities, I find it a lot easier just to delete the integration and re-add it again. Then you have a clean installation.

I still think I might add the Username and Password to the Options Config Flow, should a user have changed that

**Comment by AngellusMortis** [comment]
Added in latest RC. Closing.
