### ISSUE TITLE
Unable to stream to Nest Hub

### ISSUE THREAD

**Issue by SeBsZ** [briis/unifiprotect#326]
### Home Assistant Version?

2021.10.0

### UniFi Protect Version?

1.19.2

### UniFi Protect HA Integration version?

Latest release 0.9.1

### What happened?

My Google Nest Hub shows a "Not Connected" image with a heart and Nabu Casa. I can see the camera streams just fine in the home assistant web UI. The issue is with streaming to the hub. Many thanks for your time.

**Comment by AngellusMortis** [comment]
Please note: "latest release" is not a valid answer for what version of the integration you are using. Please check HACS and add the correct version number.

**Comment by AngellusMortis** [comment]
Also, as the component does not actually provide a way to cast Unifi Cameras to other devices, please include the service call and/or automation you are using to initiate casting video to your Nest Hub

**Comment by SeBsZ** [comment]
Hey, I basically edited the version in right away, toy must have missed it because you were really quick! Sorry.

The way I initiate the video stream is by clicking Cameras on the hub and then I choose the camera I want with the subtitle "home assistant cloud by Nabu Casa". Do you want me to add a video or photo?

If I ask the hub to stream the camera to my tv, I get the same "not connected" image on my tv.

**Comment by AngellusMortis** [comment]
I do not actually use any Google Home products or Nabu Casa (my HA instance is 100% local network only). So I have no idea what @briis might need to help you debug your problem. Just asking some basic questions to help out.

**Comment by AngellusMortis** [comment]
You may want to provide details on how your Nest Hub and TV is integrated into HA. Everyone has wildly different HA setups and it sounds like at least 3 integrations are working together here.

**Comment by SeBsZ** [comment]
There is only home assistant, Nabu Casa cloud and its google assistant integration. I also tried using the service Camera: Play Stream and then specifying my Nest Hub. Then I don't see the Nabu Casa image in the screen but instead the cast logo shows and remains in the center of the screen.

I don't see what is weird about my setup. I'd just like someone to chime in who has the same setup. Thanks again.

**Comment by briis** [comment]
The way it works works for me is: I have 3 Google Nest Hubs and a bunch of Cameras through our UniFi Protect Integration. I have setup the Nest Hubs using the Google Cast Integration as you can see from the image below.
<img width="280" alt="Skærmbillede 2021-11-06 kl  16 59 08" src="https://user-images.githubusercontent.com/24776272/140615942-20676a23-c199-46d7-86e4-1f4bc2592c00.png">
e 

With that setup the below Service call will stream the camera `camera.carport` to the Nest Hub `media_player.nest_office`. 

```yaml
service: camera.play_stream
target:
  entity_id: camera.carport
data:
  media_player: media_player.nest_office
````

and this service call will stop the camera casting to the Nest Hub again:

```yaml
service: media_player.turn_off
target:
  entity_id: media_player.nest_office

````

**Comment by SeBsZ** [comment]
Right, I have tried that as well, but that will only show a cast icon in the center of my nest hub. I wonder if there is something I need to do, why isn't it loading the stream. I have the rtsp enabled on the cameras.

**Comment by SeBsZ** [comment]
I think there is a port issue? I'm seeing this in the log:
Failed to cast media https://192.168.1.200:8123/api/hls/b3a070c594f46325f53ff470b537c21060b2abbf35ef8d273aa95ca1e5059fcf/master_playlist.m3u8 from internal_url (https://192.168.1.200:8123). Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

**Comment by briis** [comment]
This looks like some kind of network error. I am not a cast expert, so not sure why you get this. Try and search the community forum to see if others have issues like this when casting.

**Comment by SeBsZ** [comment]
It's no longer a cast issue though. The url is unreachable. It seems like an issue with the protect integration, why is that /API/ url not exposed? It should be accessible by any device in the network, and not return a 404. Any way I can debug this further?

**Comment by briis** [comment]
Can you view the stream in a `picture/entity` car in your UI. If yes this is not an integration issue.

**Comment by AngellusMortis** [comment]
The `/api/hls` URL is very likely temporary. HA likely removes it as soon as it is "done" with the stream. So as soon as you get the casting error, HA would delete the URL and you would get a 404 trying to view it manually.

**Comment by SeBsZ** [comment]
I see. Yes I can see the stream in the HA UI.

Then the only question remaining is whether the stream needs a valid SSL certificate? Should I try installing that? Perhaps the cast stream does not ignore the SSL certificate error? Or can I somehow tell it to go through Nabu Casa so that it uses proper SSL?

**Comment by briis** [comment]
I am still convinced this is an internal network setup issue, as I wrote above, the way it works for me is without having done any special settings and SSL certificates and it does not matter if I access my HA through Nabu Casa or directly on the internal IP - it works.
I do remember having issues like yours, I do know I changed something in my setup, I am just note sure what it was. But you could try turning off: `Block LAN to WLAN Multicast and Broadcast Data`

**Comment by SeBsZ** [comment]
Thanks for your help, that setting was already turned off.

This comment on another forum eventually helped me. I can now cast the stream to my Nest Hub:
https://community.home-assistant.io/t/media-play-does-not-work/241696/26

The problem indeed seems to be the missing SSL certificate, which the Nest Hub does not like. By setting the internal url to the Nabu Casa one, the SSL url is used and the stream starts.

Unfortunately there is now a 10s or so delay in the feed... If you think this is caused by going through Nabu Casa, then it may be worth setting up an SSL certificate on the internal url somehow.

Thanks again.

**Comment by briis** [comment]
Glad you found the issue. The 10 second delay is unfortunately not something we can fix easily, but [see this comment](https://github.com/briis/unifiprotect/discussions/325#discussioncomment-1585271) from @AngellusMortis in the Discussions area

**Comment by AngellusMortis** [comment]
> By setting the internal url to the Nabu Casa one, the SSL url is used and the stream starts.

This sounds like an issue. It should be using your external URL. I would raise it up on the core HA repos under the stream or camera components

**Comment by AngellusMortis** [comment]
Also going to close this since you got everything working.
