### ISSUE TITLE
UDMP at latest official update complaining about wrong version of Protect

### ISSUE THREAD

**Issue by segfaultex** [briis/unifiprotect#333]
### Home Assistant Version?

2021.11.2

### UniFi Protect Version?

1.19.2

### UniFi Protect HA Integration version?

0.10.0-beta.4

### What happened?

Getting a version error with a UDM Pro on the latest official versions of both the UnifiOS and Protect.
Release Channel: Official
UniFi OS Version: 1.10.4
Protect Version: 1.19.2
Based on the readme the version should only effect CloudKeys not UDMP, or is that wrong?

### Relevant log output

```shell
Log Details (ERROR)
You are running V1.19.2 of UniFi Protect. Minimum required version is V1.20.0. Please upgrade UniFi Protect and then retry.
```

**Comment by AngellusMortis** [comment]
Please read. 

![image](https://user-images.githubusercontent.com/490848/141164328-9811f334-41f1-4e4c-9921-530099729a3e.png)

Beta versions of integration are designed to be ran

**Comment by segfaultex** [comment]
ah.
sorry.
i saw all the info on the main page about "End of support for Non UnifiOS devices"
didn't even think to look at the actual beta release notes.
