### ISSUE TITLE
Camera state always shows Recording even though nothing is being recorded

### ISSUE THREAD

**Issue by alonjr** [briis/unifiprotect#337]
### Home Assistant Version?

2021.11.2

### UniFi Protect Version?

1.19.2

### UniFi Protect HA Integration version?

0.9.1

### What happened?

Camera is set to record only during a motion event. 
The camera state in HA shows Recording even though there is no motion event and nothing is being recorded on the Cloudkey gen2+.

Expected: 
If no motion event, the video stream is not being recorded and therefore the camera state in HA should show Idle.

**Comment by briis** [comment]
This is per Home Assistant design, unless the you have set Motion Detection to `never`. So the Camera state does not display if motion is occuring, just that it is activated. The binary_sensors show if a motion event occur.
