### ISSUE TITLE
live stream is 10 seconds behind

### ISSUE THREAD

**Issue by Pzharyuk** [briis/unifiprotect#34]
Hi,

I integrated Unifi Protect with HA and my live stream is 10 seconds behind. Everything else is flawless.  I know that it uses RTSP, when I integrate through "genetic camera" using RTSP url, there's no lag. When I remove everything and re-add it with this add-on I get the 10 sec delay. 

I love this add-on and I hope I can get some help with this.

**Comment by briis** [comment]
This is the same issue as #25 and unfortunately there is not a lot I can do. When I do what you do with the Generic Camera setup I still get the same delay in streaming. (Unless you connect directly to the Camera) So as long as we go through the Unifi Protect Server there seems to be a delay, which I currently can't fix.

**Comment by briis** [comment]
Just to confirm my personal findings. I just installed a spare Unifi Camera, set it up as standalone (So no Unifi Protect Server), and then accessed the camera directly using the Generic Camera component from HA. And also here I see a delay of 5-10 seconds in the stream.

**Comment by Pzharyuk** [comment]
Thanks, appreciate the quick reply!
