### ISSUE TITLE
Did a dumb thing

### ISSUE THREAD

**Issue by PRGeno** [briis/unifiprotect#356]
OK, I freely admit I did a very dumb thing.  I was blindly started upgrading my HA instance at our second home.  I didn't fully read the release notes and upgraded to .10 without noticing the Unifi Protect 1.20 requirement (still on 1.19.1).

Obviously this integration is no longer working and I can't risk remotely upgrading Unifi Protect since I'm 2000 miles away and not planning to be at that home until after the new year.  So my only options are to leave this integration broken, or try to roll it back to the .9 release.

While I will acknowledge I might be the only one to have done such a dumb thing, but I suspect not.  So I'm wondering is there an easier way to roll back to the previous version without complete removal and re-install of the integration, or a full HA backup restore?

**Comment by briis** [comment]
If you installed through HACS, just select reinstall and select the 0.9.1 release, restart Home Assistant and everything should be like before. If not HACS then you can download the 0.9.1 release from the Releases page on Github, and then just replace the files in `custom_components/unifiprotect`.

**Comment by AngellusMortis** [comment]
You _should_ just be able to install 0.9.1 from HACS and then restart Home Assistant. If that does not 100% work, a last resort would be to re-install the correct version of `pyunifiprotect` manually.

If you have HA OS:

* Install the SSH & Web Terminal add-on, **under Community Add-ons**, not the official one.
![image](https://user-images.githubusercontent.com/490848/143609211-b1fa28bd-eecc-44f1-931e-09453388ce2d.png)
* Run the following:

```bash
docker exec -it homeassistant bash
pip install pyunifiprotect==0.33.0
```

If you are not using HACS / HA OS, then reinstall `unifiprotect` using the [0.9.1 tag](https://github.com/briis/unifiprotect/tree/v0.9.1) and manually install that version of `pyunifiprotect` into your Python virutalenv.

**Comment by PRGeno** [comment]
Perfect, rolled back via HACS and I'm back in business.

Thank you for your quick support, and for such a useful integration.
