### ISSUE TITLE
Not sure whats wrong

### ISSUE THREAD

**Issue by Thepyropc** [briis/unifiprotect#357]
i logged into home assistant and all my cameras and doorbells were unavailable so i tried logging back in and i keep getting an error that says "_UniFi Protect Version is not supported by this Integration_" I'm not really sure what to do here i believe i have logged everything in correctly, my home assistant and my UDM are up to date

**Comment by AngellusMortis** [comment]
Your UniFi Protect instance is out of date. 0.10 of the integration requires Protect 1.20.0 to run. Double check in your UDM for an update.

Otherwise, you will need to downgrade the extension to 0.9.1

**Comment by Thepyropc** [comment]
i found it i actualy had to get on the computer and update protect itself. couldn't get to it from my phone. i appreciate the help
