### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by Golab** [briis/unifiprotect#36]
Hello I’m on Home Assistant 0.109.0b3 and unifi ver: 
5.13.10 and protect ver: 1.13.3-beta1 and your addOn Is V0.1.6

My problem is that I get this error all the time in my log

Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120 
First occurred: 2:03:31 PM (6156 occurrences) 
Last logged: 4:36:42 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 109: verify=self._verify_ssl,
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 210: verify=self._verify_ssl,

![image](https://user-images.githubusercontent.com/1252745/80310956-7d6c6780-87dd-11ea-8325-c227efd93ec9.jpeg)

![image](https://user-images.githubusercontent.com/1252745/80310964-852c0c00-87dd-11ea-86e1-9764d75fab33.jpeg)

![image](https://user-images.githubusercontent.com/1252745/80310972-8b21ed00-87dd-11ea-96a7-89221dd825c9.jpeg)

![image](https://user-images.githubusercontent.com/1252745/80311010-b1e02380-87dd-11ea-9736-d0262cced761.jpeg)

**Comment by briis** [comment]
I am not yet on the 109 Beta, so I have not seen this error. The lines that are referenced are doing IO as these are the request calls to get the cameras and the events from the Protect Server. I will look in to this once I have a 109 version installed. But it seems that there are some changes that can severely impact this Integration.

**Comment by Golab** [comment]
I really hop you can fix this sone it seems this error comes up at lest 10 times every minute, because if I clean log and wait 5 seconds and do a refresh then the error shows up again :/


If you have missed this


Detection of blocking I/O in the event loop

This is a bit technical, but some things happening in Home Assistant, like fetching data from an API or website, can lock up Home Assistant for a small moment, if not done correctly. Until now, this has been hard to detect.

This release adds logic in the core of Home Assistant that is able to detect if an integration does one of those blocking calls and writes a messages to the logs.


https://rc.home-assistant.io/blog/2020/04/21/release-109/

**Comment by briis** [comment]
Thanks for the link to the Beta Release notes. Unfortunately it does not say anything about what needs to be done to avoid this, but I would assume I need to rewrite the whole engine to use the Async libraries. I don't have the time as I don't have the knowledge, to do this fast, so unfortunately this Integration might not work for a while when you upgrade to 109.x.

**Comment by basroovers** [comment]
I just upgraded to 0.109.0 and got the same message in the logs:
```
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 109: verify=self._verify_ssl,
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 210: verify=self._verify_ssl,
```

**Comment by briis** [comment]
Yes I know. I am working on a fix, but have NO timeframe for when this will be done.

**Comment by boralyl** [comment]
@briis I can probably help out with this if you need some assistance as I use this component.  Taking a quick look at your code, I think it should be pretty straightforward to swap out requests with async.  If you'd like help I can create a branch and give it a whirl.

**Comment by briis** [comment]
@boralyl You are more than welcome. I would be really glad if you could give it a shot. Let me know when you need something testet.
Thanks
/B

**Comment by boralyl** [comment]
:+1: I'll be upgrading HA to 0.109 today, so I'll start work on sometime this week.

**Comment by Veldkornet** [comment]
I also seem to get this, in at least 4 locations:

```
2020-04-29 19:39:32 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 210: verify=self._verify_ssl,
2020-04-29 19:39:35 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 109: verify=self._verify_ssl,
2020-04-29 20:33:15 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 89: verify=self._verify_ssl,
2020-04-29 20:33:16 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 304: response = self.req.get(img_uri, verify=self._verify_ssl)
```

**Comment by dodg3r** [comment]
@briis  I dont know if this can help ?

https://github.com/home-assistant/core/pull/34896

**Comment by briis** [comment]
I did some quick fideling with this, without positive results. But as you can see from above @boralyl will give it a shot next week.

**Comment by briis** [comment]
Hi all
Thanks to @pruchai there is now a fix available, so that this will also work with V0.109.x.
I have made a new release, and for those who use HACS, it should show up soon.

Thanks again Igor, really appreciate it.

**Comment by pruchai** [comment]
@briis glad to help! 

Looks like this may need to be added in a few more places. I only fixed the ones that I saw on my end. Theoretically, every function that does a `get()` request has to be updated, but I don't want to change more than i can personally test.

These are the line numbers that would need to be changed `async ` added

@Veldkornet this should fix all of your errors. My commit only fixes 2
```
57:    async def _get_api_auth_bearer_token(self):
76:    async def _get_api_access_key(self):
100:    async def _get_camera_list(self):
187:    async def _get_motion_events(self, lookback=86400):
243:    async def get_thumbnail(self, camera_id, width=640):
278:    async def get_snapshot_image(self, camera_id):
316:    async def set_camera_recording(self, camera_id, mode):
357:    async def set_camera_ir(self, camera_id, mode):
```

**Comment by briis** [comment]
I pulled the release as the Switches and Sensors don't show up after changing to async, so there is some work to do here.
Is this working for you @pruchai ?

**Comment by briis** [comment]
I made all the modifications to async you suggested. But with that, the component loads withut any errors but no cameras, sensors, binary_sensors or switches are setup in HA-
Hmmm - I am clueless

**Comment by johntdyer** [comment]
@pruchai  / @Veldkornet  - Was it working on your end w/ those fixes ?   if so I am curious whats different w/ @briis deployment...

**Comment by Veldkornet** [comment]
No, for me it wasn’t working either, all of my cameras were missing...

**Comment by boralyl** [comment]
Have been busy this week, but am going to dig into this issue this weekend.  Looks like it's still outstanding.

**Comment by jcollas** [comment]
Looks like there's quite a bit of async infrastructure in the __init__.py file.  @boralyl, if you want some assistance, I was going to take a shot at fixing this tomorrow.

**Comment by briis** [comment]
Yes it is still not working. Really appreciate it guys if you can help me out.

**Comment by boralyl** [comment]
I've got a draft PR here: https://github.com/briis/unifiprotect/pull/39  It's not fully working yet as I had to comment out registering services.  If I uncomment them, HA doesn't start up for me, and there is nothing in the logs.  Am still looking into it, but if anyone has any ideas, feel free to comment on the PR.

**Comment by boralyl** [comment]
Ok!  I"ve got everything working in #39 .  I ended up rewriting the component to be completely async.  See the PR for more details.  Would also be great if someone else could test the branch and ensure it works for them too.

**Comment by jcollas** [comment]
I've been running it for the last hour (with minor fix in sensor.py), works great.

**Comment by boralyl** [comment]
Awesome!  What fix did you need in sensor.py?  Mind adding it to the PR?

**Comment by jcollas** [comment]
The fix is already in the PR.  It was just a typo that was corrected just before his announcement.

**Comment by boralyl** [comment]
Oh, gotcha!  Thanks for testing it out!

**Comment by jcollas** [comment]
@boralyl I went through your code, that's some nice work.

**Comment by briis** [comment]
This is awesome work - Everything is working and I have now merged the PR in to the master. I am building a new release, to be available in HACS. THANK YOU so much for doing this.
