### ISSUE TITLE
Integration is not supported post HASS upgrade

### ISSUE THREAD

**Issue by sajid2310** [briis/unifiprotect#363]
Post upgrade the unifiprotect integration stopped working.  I have attached below the version details. It was working prior to the upgrade.

Error Message:
"UniFi Protect Version is not supported by this Integration"

**HASS Version:**
core-2021.11.5
supervisor-2021.10.8

**Comment by AngellusMortis** [comment]
0.10 of the integration requires Protect 1.20 to work. Either upgrade Protect or downgrade your integration to 0.9.1
