### ISSUE TITLE
Problem after upgrading 

### ISSUE THREAD

**Issue by erikjvanderveen** [briis/unifiprotect#365]
Yesterday updated HACS and this integration, and noticed this morning that automations are not running. 
The log file said that I had to upgrade unifi protect from 1.19.0 to 1.20.0. So I did. 
But after that the integration is still not loaded with this log message: 

2021-11-30 11:47:23 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry UniFi Cloud Key Gen2 Plus for unifiprotect
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/unifiprotect/__init__.py", line 108, in async_setup_entry
await _async_get_or_create_nvr_device_in_registry(hass, entry, nvr_info)
File "/config/custom_components/unifiprotect/__init__.py", line 124, in _async_get_or_create_nvr_device_in_registry
device_registry.async_get_or_create(
TypeError: async_get_or_create() got an unexpected keyword argument 'configuration_url'

**Comment by AngellusMortis** [comment]
0.10.x requires Home Assistant 2021.11+ and Protect 1.20+.

If you cannot upgrade Home Assistant, you will have to downgrade Protect and the Integration.

**Comment by slootjes** [comment]
I'm confirming it works fine after I've updated both the plugin and Home Assistant to the latest version.

**Comment by erikjvanderveen** [comment]
Yes, I upgraded the Home Assistant Core to 2021.11 and
I can confirm too that my Unify doorbell now makes my google home and sonos speakers tell that there is someone at the door again

**Comment by eh8** [comment]
The link posted above is a 404 for me, but I found that these steps worked for my Cloud Key Gen 2+. 

```bash
apt-get update 
apt-get install --reinstall --allow-downgrades unifi-protect=1.19.2 -y
```
