### ISSUE TITLE
switch.record_always, motion, never    isn't running after update to 0.10.1

### ISSUE THREAD

**Issue by clmalacarne** [briis/unifiprotect#367]

**Comment by AngellusMortis** [comment]
Please use the submission form and provide more details about your issue.

**Comment by clmalacarne** [comment]
After I have updated to vers. 0.10.1 the entity switch.record_motion and switch.record_never is not more running. Is this function not more supportetd?

**Comment by AngellusMortis** [comment]
I think that would be under this changelog:

> CHANGE: BREAKING CHANGE All switches called switch.record_smart_CAMERANAME and switch.record_motion_CAMERANAME have been removed from the system. They are being migrated to a Select Entity which you can read more about below. If you have automations that turns these switches on and off, you will have to replace this with the select.select_option service, using the valid options described below for the option data.

They have been migrated to a select entity instead.

**Comment by AngellusMortis** [comment]
The full list of changes can be found in https://github.com/briis/unifiprotect/blob/master/CHANGELOG.md#0100

**Comment by clmalacarne** [comment]
All right. Thank's a lot for your help
