### ISSUE TITLE
After 10/11 updates. Live views of cameras lagging alot

### ISSUE THREAD

**Issue by CoreyJ87** [briis/unifiprotect#384]
### Home Assistant Version?

2021.11.5

### UniFi Protect Version?

1.20.0

### UniFi Protect HA Integration version?

0.10.1

### What happened?

Ever since these updates were made. I went from 9-11. Im just seeing weirdness. I have 6 cameras on a lovelace dashboard live view. They seemed to work fine before. And they are barely working now. I've noticed a couple things. It seems like they are using wayyy more memory or something in the background(not sure if thats it or not). But basically they start lagging out. Getting farther and farther behind in time on my tablets that I have around the house. This was never a problem before I could have them sitting there live on for hours and they'd all stay perfectly in sync. On the computer it works a bit better. Although, theres one specific camera that it basically only updates about every 15-30 seconds. So its pretty much ALWAYS behind. While the others just slowly get out of sync. Until they get to a point where they are just sooooo far behind that I have to refresh. Or sometimes they even freeze all together. I've got one camera right now that shows it last updated 2 mins and 30 seconds ago. I've removed that camera. Re-added. Deleted the integration. Re-added and reconfiged. Ive put those cameras on a different lovelace UI with only a few cameras on it. This one particular one. Just cant seem to stay up to date. Same model cameras. Same everything. Anyone experiencing any of these issues?

**Comment by AngellusMortis** [comment]
Streaming to the frontend is really a Home Assistant thing. We do not have any control over how it works. We just give HA a URL and it does the rest. Under the hood, HA spins up a FFMPEG stream to convert the RTSP(S) stream into a (LL-)HLS stream. 

Some things to try out: 

* You can upgrade to the 0.11-beta which will give you all of the different possible RTSP(S) sources as camera entities. Maybe it is a specific combination of them that is giving you issues?
* If you HA instance is not already behind an HTTP/2 proxy (like nginx), put it behind one. That will help a lot with connection pooling.
* Try enabling [LL-HLS in HA](https://www.home-assistant.io/integrations/stream#ll-hls). It will require above mentioned HTTP/2 proxy.

**Comment by CoreyJ87** [comment]
> 

Thats kind of what I thought. Would anything have changed though(in terms of performance) because of the types of streams being sent? Or did nothing really change with that? Like is it somehow pulling a higher quality stream now? 

I'll deff give those options u mentioned a try and see if it helps

**Comment by AngellusMortis** [comment]
Each camera has 3 channels (High / Medium / Low). Each channel can have RTSP enabled or not. Before 0.11, we were always taking the highest quality channel that had RTSP enabled on (so if you had all 3, it would be the first channel, High). 

The only thing that changed between 0.9.2 and 0.10.1 is switching to the RTSPS URL instead of the RTSP URL since UI removed the non-secure one from the UI. We never saw any change that had on HA (I have 4x G4 Pros and none of them had any issues). I am pretty sure the only difference here is that it is RTSP over HTTPS instead of RTSP over HTTP. So that _could_ cause CPU spikes on the lowest possible end hardware (like a RPI Zero or something seriously underpowered).

For 0.11, the default enabled camera entity is still the same as 0.10, but we also added up to 5 others for all of the other combinations if they were enabled correctly in UFP.

The only other thing of note is that I discovered in my testing that using the "High FPS" video mode that affect the quality of the "High" channel stream. If High FPS mode is on, the High channel stream for G4 Pros and G4 Doorbell is cut down to 1080p (from 2160p and 1600p).

**Comment by CoreyJ87** [comment]
Gotcha, weird... I actually didnt have any RTSP turned on. I just bought the G4 Bullets a couple weeks ago. And by default arent all 3 rtsp streams off? I just turned one on today to test casting to a tv. But then I had some problems. So I turned it back off. 

Aside from that I assume you mean HA running on a underpowered device? HA is running on a pi 4(8 gig). And where I'm seeing the most lag is on a samsung a7 tablet. Although, I see it on the PC too. So its gotta be something on the HA side/stream side. So i'll give your original suggestions a go. They sound like good possibilities

**Comment by AngellusMortis** [comment]
If you do not have RTSP enabled, you will not get actually streaming. That would be your problem. With RTSP enabled, Home Assistant will just pull a new image every second, but that will will choppy and bad.

With RTSP enabled,l and the above link stream component, a 9-15 second delay is expected/normal. If you enabled LL-HLS in the stream component, you can expected a 1-3 second delay.

**Comment by CoreyJ87** [comment]
Interesting. So basically the way I had it before. RTSP was off completely across all the cameras. Thats still the same. But maybe now that im doing more in HASS period. Maybe thats where im getting the lag. Odd timing on the upgrade though. I think I will go the LL-HLS route. As id rather have a smooth stream and just have a delay. As opposed to this jumpy random lag im getting.

**Comment by AngellusMortis** [comment]
Going to go ahead and close this. Feel free to post though if you need any more help setting it up.

**Comment by CoreyJ87** [comment]
Sounds good man. Thanks for the help. I do have one question. whats your commendation on setting up nginx?....Im seeing now that nginx on a regular hass pi setup. Isnt easily installed unless you use that addon(NGINX Home Assistant SSL proxy and Duck DNS). That allows you to do the reverse proxy via it and duckdns....Id rather keep it all internal. As thats how I connect all my devices around the house to hass anyways. Is my only option running nginx on another pi or something else and just setting it up on there and forwarding? Or do I have to use the Duck DNS/NGINX Home Assistant SSL proxy setup? I dont see why I would need to. But I cant figure out a way to install nginx manually and do what I want on the default hass pi setup. I figure thats intentional though. They made a slimmed down image for the pi

**Comment by AngellusMortis** [comment]
I was trying to run nginx on a separate machine at first, but then HA made a bunch of changes to restrict that and make it harder. Now though, I just use the [official nginx add-on](https://github.com/home-assistant/addons/tree/master/nginx_proxy).

As for DNS, I have my own domain that I have purchased. Then I use a PiHole as a DNS server to set up internal only DNS name and Cloudflare + Let's Encrypt to make HTTPS certs (the internal domains to not need to exist if you use a DNS plugin for Let's Encrypt like Cloudflare).

**Comment by CoreyJ87** [comment]
I've got a domain and a PiHole running on another pi right now. so Perfect

**Comment by CoreyJ87** [comment]
One more question. It appears. that fullykiosk on the android tablet I have is not handling rtsp streams in HA. With the new beta will. I be able to pick the option that is basically "no rtsp" for one setup while also having another that says "ima use rtsp high" different entities i guess?
