### ISSUE TITLE
Camera state attribute Online missing?

### ISSUE THREAD

**Issue by jayscovill** [briis/unifiprotect#400]
### New Feature

The camera state (online: true) used to be reported as an attribute.  I was using it to create a sensor for the camera status.  However it looks like at some point that state attribute has been removed.

Is there another way to determine camera status now?

`
- platform: template
  sensors:
    garage_camera_status:
      friendly_name: 'Garage Camera Status'
      value_template: >-
        {% if is_state_attr('camera.garage', 'online', true) %}Online{% else %}Offline{% endif %}
      icon_template: >-
        {% if is_state_attr('camera.garage', 'online', true) %}
          mdi:cloud-check
        {% else %}
          mdi:cloud-alert
        {% endif %}
`

**Comment by AngellusMortis** [comment]
It looks like it was removed in 0.10. We will likely not be bringing that attribute back since it is duplicated data. Just checking to see if the Camera entity is available is a good enough check for that. 

```
not is_state('camera.garage', 'unavailable')
```
