### ISSUE TITLE
Component implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by CumpsD** [briis/unifiprotect#402]
### Home Assistant Version?

2021.12.x

### UniFi Protect Version?

n/a

### UniFi Protect HA Integration version?

n/a

### What happened?

As of HA 2021.12.x they now report this warning for custom components:

```
2021-12-14 10:56:16 WARNING (MainThread) [homeassistant.helpers.entity] Entity xxxxx (<class 'custom_components.unifiprotect.switch.UnifiProtectSwitch'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by briis** [comment]
You are not writing what version of the Integration you are running. This has been fixed in V0.10.0 and onwards.

**Comment by CumpsD** [comment]
"version": "0.9.1",

Hmm, sorry... I didn't see it in my HACS, maybe I installed it manually 🤷🏻 

I'll see to re-install

**Comment by briis** [comment]
0.10.x and onwards will require you to update UniFi Protect to V1.20.x. If you cannot do that, stick with 0.9.1 and we will fix the `device_state_attributes` warning.

**Comment by CumpsD** [comment]
Nah, I'm always with the latest version, just updated again after the log4j patch a few days ago

**Comment by briis** [comment]
If you activate Beta versions in HACS, the latest version is 0.11-beta.3.
Lots of breaking changes though from 0.9.1, so read release notes carefully.

**Comment by CumpsD** [comment]
I think I manually installed it, now did it with HACS and it's working fine, 0.10.1 now

**Comment by CumpsD** [comment]
Congrats on going to be integrated into core! Just read the changelog for 0.11 :)

**Comment by briis** [comment]
We are not there yet, but hopefully in the 2022.2 release 😁
