### ISSUE TITLE
"Reboot" Service

### ISSUE THREAD

**Issue by ervwalter** [briis/unifiprotect#403]
### New Feature

I don't know if the underlying Unifi API that you're tapping into supports this, but it would be really nice if there was a service that could reboot a given protect device.  

My specific use case is that I'd like to reboot my ViewPort once a day.  ViewPorts are notorious for some kind of memory leak or something that causes their FPS to drop after being on for a while.  A reboot fixes the problem, and I'd like to automate that.

### Additional context

https://community.ui.com/questions/Sluggish-Viewport-after-multiple-days/b6632235-99dc-4c48-b39b-7fce81037254
https://community.ui.com/questions/Viewport-video-becomes-sluggish-after-a-few-days/42cdd58b-0b41-47a8-b385-e91dafd5f144

**Comment by AngellusMortis** [comment]
Already added in the 0.11-beta. You are required to have Home Assistant 2021.12 or newer and you will have a "Reboot" button for every adoptable device (not the NVR itself).

**Comment by ervwalter** [comment]
Ooh.  That's excellent.  Sorry for not looking harder.  I already have that version and just didn't see the disabled-by-default button.  Thanks!

**Comment by AngellusMortis** [comment]
Yep, they are disabled by default since they can be a bit destructive. They really do reboot as soon as you trigger them, no confirmation.

**Comment by ervwalter** [comment]
They work great and it makes total sense that they are disabled by default.  I already created my automation and tested that it works perfectly.  Thanks again.
