### ISSUE TITLE
What exactly has changed between Version 0.1.7 and 0.2.0?

### ISSUE THREAD

**Issue by adandl** [briis/unifiprotect#41]
Hello @briis !

Can you please explain what has changed between Version 0.1.7 and 0.2?
I can live with the warnings, but since I upgraded to 0.2 my camera stream has stopped.

However I have to admit that I use your code in combination with the UnifiOS proxy.
Eventually this is why it stopped with 0.2?

Thanks a lot!

Albert

**Comment by briis** [comment]
Hi Albert,
The whole component has been re-written to use the Async libraries, and thus making it more conform to the HA standards. I have heard from another user who uses UDMP with the Proxy, that he has the same issues.
The GOOD news is that there is a PR waiting to get merged, that will make this support both the UDMP and CloudKey+ without using the proxy. I believe that will solve your issues. 
If all goes well this should be done within the next day.

**Comment by adandl** [comment]
Wow - that is very good news - I'm looging forward and will provide feedback asap if it works without Proxy as well!
Thank you for giving this to the community :)

**Comment by adandl** [comment]
It works now directly with UnifiOS - I can confirm that :)
You are my hero :)

Thank you!!!
