### ISSUE TITLE
last_changed not a direct replacement of last_tripped_time

### ISSUE THREAD

**Issue by dersher** [briis/unifiprotect#411]
### Home Assistant Version?

2021.12.3

### UniFi Protect Version?

1.20.1

### UniFi Protect HA Integration version?

0.11.0

### What happened?

The changelog mentions that:
`last_tripped_time will be removed from binary sensor entities -- use the last_changed value provided by the HA state instead`

However, this is not the case. I'm trying to get the last motion detection, which last_tripped_time provides accurately.

As you can see from the screenshot below:
`Last detection {{relative_time(states.binary_sensor.motion_doorbell.last_changed)}} ago` returns the last changed state which unfortunately isn't the last tripped time.
`Last detection {{relative_time(state_attr('binary_sensor.motion_doorbell','last_tripped_time'))}} ago` returns correctly that the last motion was triggered 56 minutes ago.

![image](https://user-images.githubusercontent.com/76836569/146637776-80c59f21-bde2-44e4-bab7-76f21932a82e.png)

**Comment by dersher** [comment]
I think I figured this out, last_tripped_time survives a reboot, but last_changed does not.
Still, I don't see this as a direct replacement but it's not as huge of a concern as I thought.

**Comment by AngellusMortis** [comment]
`RestoreEntity` did not quite work as expected. After some discussion we decided to keep `last_tripped_time` since there is no good way to persist the data. So, you can consider `last_tripped_time` no longer deprecated. Will post an update in the changelog when we release 0.11.1 (I finally found a proper fix for talkback not always working).

**Comment by dersher** [comment]
Hi @AngellusMortis, the state attribute last_tripped_time seems to have been removed in v0.12.0-beta6.

I'm now running HA 2021.12.6 with Protect 1.20.2.

**Comment by AngellusMortis** [comment]
It looks like it was only removed for the camera motion sensor. I cannot find where it was moved, but I am guessing maybe when I added the thumbnail URL? But that was quite a while ago. 

Regardless, definitely an issue, I will fix it right away.

**Comment by AngellusMortis** [comment]
@dersher Fixed in 0.12-beta.8.

**Comment by dersher** [comment]
Great! Thanks for your really fast response!
