### ISSUE TITLE
Media player not working

### ISSUE THREAD

**Issue by kmlucy** [briis/unifiprotect#416]
### Home Assistant Version?

2021.11.5

### UniFi Protect Version?

1.20.1

### UniFi Protect HA Integration version?

0.11.1

### What happened?

I'm not able to get TTS working on my G4 Doorbell or G3 Instant. TTS works fine on other speakers, either directly from the media player more-info popup, or via the tts.*_say service. On the Unifi devices, nothing happens; no log entries, no speech. I've restarted the cameras and Home Assistant with no change.

**Comment by AngellusMortis** [comment]
Some things to try:

* Make sure you can ping the IP address of your camera from your Home Assistant machine
* Enable debug logging: https://github.com/briis/unifiprotect#enable-debug-logging and post your logs
* Make sure you actually have the speaker sound turned up
* Can you do 2 Way Talk from the UniFi Protect app?

**Comment by kmlucy** [comment]
Thank you for the help, it was a firewall rule that was blocking traffic. I hadn't realised that the TTS didn't go through the NVR like all the other parts of the integration.
