### ISSUE TITLE
No camera entities

### ISSUE THREAD

**Issue by IT-Lueg** [briis/unifiprotect#419]
I installed the Integration via HASC an successfully added my UCKP. I also added "stream:" to the config. And the User is a local admin.

![image](https://user-images.githubusercontent.com/4661044/147007382-ab0ef880-f564-4b01-b71d-aea25a5f2f2a.jpeg)

There are a lot of sensors of my cams an they are all working, but there are no camera entities. :/

Can someone please tell me what I'm doing wrong?

![image](https://user-images.githubusercontent.com/4661044/147007261-c8f8d4c3-1ccf-4b9f-b67e-3940762bd3a2.jpeg)

![image](https://user-images.githubusercontent.com/4661044/147007273-b94b73f1-a705-448b-a934-b6776ecff07b.png)

![image](https://user-images.githubusercontent.com/4661044/147007284-f599ae73-16d3-403d-8bba-9e9a14f6bce3.png)

**Comment by IT-Lueg** [comment]
... the rtsp streams are activated in the UCKP

![image](https://user-images.githubusercontent.com/4661044/147007767-808edc01-c3af-4458-8328-11e258a7033c.jpeg)

**Comment by AngellusMortis** [comment]
I hate to close the ticket after you have already uploaded so many images, but please use the provided issue template, including the versions of Home Assistant, UniFi Protect and the UniFi Protect HA integration. Also please make sure you check for Home Assistant logs. If you do not have camera entities, you should definitely have logs.
