### ISSUE TITLE
Unifi OS

### ISSUE THREAD

**Issue by causefx** [briis/unifiprotect#42]
With last two updates, Cameras are working fine in HA but now I am not getting any motion events.

With new update I changed from docker containter to native with port 443 for unifi OS

protect log:
```
# tail events.cameras.log -f
2020-05-05T21:19:34.924Z - verbose: motion.start Doorbell [E063DA3F4029 @ 10.0.9.40] 1588713571807
2020-05-05T21:19:42.622Z - verbose: motion.stop Doorbell [E063DA3F4029 @ 10.0.9.40] 1588713581486 
{ clockBestMonotonic: 449907872,
  clockBestWall: 1588713575680,
  clockMonotonic: 449929836,
  clockStream: 449914818,
  clockStreamRate: 1000,
  clockWall: 1588713582486,
  edgeType: 'stop',
  eventId: 47,
  eventType: 'motion',
  levels: { '1': 87 },
  motionHeatmap: 'heatmap_00000047.png',
  motionSnapshot: 'motionsnap_00000047.jpg' }
2020-05-05T21:19:42.657Z - info: event saved 
{ type: 'motion',
  start: 1588713571807,
  end: 1588713581486,
  score: 87,
  cameraId: '5e9f7ecc0241450387000b7f',
  partitionId: null,
  metadata: { objectType: null, objectCoords: null, objectConfidence: null },
  id: '5eb1d866039df40387001748' }
```

**Comment by briis** [comment]
I have posted a potential fix for that. Could you go here https://github.com/briis/unifiprotect/tree/V0.3.1/custom_components/unifiprotect and replace `sensor.py` and `binary_sensor.py` with the files in this repository, and tell me if this fixes the issue?

**Comment by wralb** [comment]
@briis  FYI, Binary sensors have started working for me after I replaced sensor.py and binary_sensor.py with the code in the link above (V0.3.1).  They had not worked with on my UCK+ over the last couple of days.  Thanks for the amazingly fast responses to the various moving targets from both Ubiquiti and HASS!

**Comment by briis** [comment]
The fixes are not implemented together with a fix for handling token expiration on UnifiOS. Release 0.3.1 is ready. I will close this.

**Comment by causefx** [comment]
Sorry i was away,  This fixed worked great! thank you.
