### ISSUE TITLE
No cameras entities when there are unadopted cameras

### ISSUE THREAD

**Issue by LuegM** [briis/unifiprotect#420]
### Home Assistant Version?

2021.12.4

### UniFi Protect Version?

1.20.1

### UniFi Protect HA Integration version?

0.11.1

### What happened?

camera entities are not created

### Relevant log output

```shell
Logger: homeassistant.components.camera
Source: custom_components/unifiprotect/camera.py:83 
Integration: Camera (documentation, issues) 
First occurred: 12:18:13 AM (1 occurrences) 
Last logged: 12:18:13 AM

Error while setting up unifiprotect platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/unifiprotect/camera.py", line 96, in async_setup_entry
    for camera, channel, is_default in get_camera_channels(data.api):
  File "/config/custom_components/unifiprotect/camera.py", line 83, in get_camera_channels
    yield camera, camera.channels[0], True
IndexError: list index out of range
```

**Comment by AngellusMortis** [comment]
Can you enable the beta versions and try out 0.11.2-beta1? it should remove fix the exception and then add logging so you can see which cameras are causing issues.

**Comment by LuegM** [comment]
Yes that was me :)
I created the first report with the app and I didn‘t see the templates there. 

So I installed the beta and the entities are successfully created now. 

Here are my logs: 
`2021-12-22 00:43:35 DEBUG (MainThread) [pyunifiprotect.api] 200 application/json <ClientResponse(https://192.168.1.2/api/auth/login) [200 OK]>
<CIMultiDictProxy('Vary': 'Origin', 'X-DNS-Prefetch-Control': 'off', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Accept-Ranges': 'bytes', 'X-CSRF-Token': 'b8e591f8-03c4-4c50-a377-edcc11e54ede', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '2975', 'X-Response-Time': '477ms', 'Set-Cookie': 'TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmVG9rZW4iOiJiOGU1OTFmOC0wM2M0LTRjNTAtYTM3Ny1lZGNjMTFlNTRlZGUiLCJ1c2VySWQiOiIzOGUyYTc5OS05ZjkzLTRjMGMtYWExNi0wOTVhMzY2NmQ3MjkiLCJpYXQiOjE2NDAxMzAyMTIsImV4cCI6MTY0MDEzMzgxMn0.6OQbpzJdkx2dmDm4c36sje7IDpxlU_tIKSToD-GCuDQ; path=/; samesite=strict; secure; httponly', 'Date': 'Tue, 21 Dec 2021 23:43:32 GMT', 'Connection': 'keep-alive')>
2021-12-22 00:43:35 DEBUG (MainThread) [pyunifiprotect.api] Authenticated successfully!
2021-12-22 00:43:35 DEBUG (MainThread) [pyunifiprotect.api] Request url: https://192.168.1.2/proxy/protect/api/nvr
2021-12-22 00:43:36 DEBUG (MainThread) [pyunifiprotect.api] 200 application/json <ClientResponse(https://192.168.1.2/proxy/protect/api/nvr) [200 OK]>
<CIMultiDictProxy('Vary': 'Origin', 'x-dns-prefetch-control': 'off', 'x-frame-options': 'SAMEORIGIN', 'strict-transport-security': 'max-age=15552000; includeSubDomains', 'x-download-options': 'noopen', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'Accept-Ranges': 'bytes', 'content-security-policy': "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'cross-origin-resource-policy': 'same-site', 'expect-ct': 'max-age=0', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'strict-origin-when-cross-origin', 'Access-Control-Allow-Credentials': 'true', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '3355', 'Etag': 'W/"d1b-jTJNOBNluk5ACgSFbd9XLW6jMHs"', 'Date': 'Tue, 21 Dec 2021 23:43:35 GMT', 'Connection': 'close', 'Set-Cookie': 'TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmVG9rZW4iOiJiOGU1OTFmOC0wM2M0LTRjNTAtYTM3Ny1lZGNjMTFlNTRlZGUiLCJ1c2VySWQiOiIzOGUyYTc5OS05ZjkzLTRjMGMtYWExNi0wOTVhMzY2NmQ3MjkiLCJwYXNzd29yZFJldmlzaW9uIjoxNjQwMTIxNDkzLCJpYXQiOjE2NDAxMzAyMTUsImV4cCI6MTY0MDEzMzgxNX0.CqxwIzSyiktEoeJ8_Aw2L9HQza6r10URcKuoMtdfawY; path=/; samesite=strict; secure; httponly')>
2021-12-22 00:43:36 DEBUG (MainThread) [pyunifiprotect.api] Adding subscription: <bound method ProtectData._async_process_ws_message of <custom_components.unifiprotect.data.ProtectData object at 0x7f82ec8a00>>
2021-12-22 00:43:36 DEBUG (MainThread) [pyunifiprotect.api] Request url: https://192.168.1.2/proxy/protect/api/bootstrap
2021-12-22 00:43:38 DEBUG (MainThread) [pyunifiprotect.api] 200 application/json <ClientResponse(https://192.168.1.2/proxy/protect/api/bootstrap) [200 OK]>
<CIMultiDictProxy('Vary': 'Origin', 'x-dns-prefetch-control': 'off', 'x-frame-options': 'SAMEORIGIN', 'strict-transport-security': 'max-age=15552000; includeSubDomains', 'x-download-options': 'noopen', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'Accept-Ranges': 'bytes', 'content-security-policy': "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'cross-origin-resource-policy': 'same-site', 'expect-ct': 'max-age=0', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'strict-origin-when-cross-origin', 'Access-Control-Allow-Credentials': 'true', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '55853', 'Etag': 'W/"da2d-FsZtg5BBMQ2q2VTBjpe8MC4m2LI"', 'Date': 'Tue, 21 Dec 2021 23:43:38 GMT', 'Connection': 'close', 'Set-Cookie': 'TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmVG9rZW4iOiJiOGU1OTFmOC0wM2M0LTRjNTAtYTM3Ny1lZGNjMTFlNTRlZGUiLCJ1c2VySWQiOiIzOGUyYTc5OS05ZjkzLTRjMGMtYWExNi0wOTVhMzY2NmQ3MjkiLCJwYXNzd29yZFJldmlzaW9uIjoxNjQwMTIxNDkzLCJpYXQiOjE2NDAxMzAyMTgsImV4cCI6MTY0MDEzMzgxOH0.pY-P6CWD-XygYs84y9cBXXkOdyXtJuj_SaMSdULb8jA; path=/; samesite=strict; secure; httponly')>
2021-12-22 00:43:38 DEBUG (MainThread) [pyunifiprotect.api] Checking websocket
2021-12-22 00:43:38 DEBUG (MainThread) [pyunifiprotect.api] Request url: https://192.168.1.2/proxy/protect/api/events
2021-12-22 00:43:39 DEBUG (MainThread) [pyunifiprotect.api] WS connecting to: wss://192.168.1.2/proxy/protect/ws/updates
2021-12-22 00:43:39 DEBUG (MainThread) [pyunifiprotect.api] 200 application/json <ClientResponse(https://192.168.1.2/proxy/protect/api/events?start=1640130216606&end=1640130216606) [200 OK]>
<CIMultiDictProxy('Vary': 'Origin', 'x-dns-prefetch-control': 'off', 'x-frame-options': 'SAMEORIGIN', 'strict-transport-security': 'max-age=15552000; includeSubDomains', 'x-download-options': 'noopen', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'Accept-Ranges': 'bytes', 'content-security-policy': "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'cross-origin-resource-policy': 'same-site', 'expect-ct': 'max-age=0', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'strict-origin-when-cross-origin', 'Access-Control-Allow-Credentials': 'true', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '2', 'Etag': 'W/"2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w"', 'Date': 'Tue, 21 Dec 2021 23:43:39 GMT', 'Connection': 'close', 'Set-Cookie': 'TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmVG9rZW4iOiJiOGU1OTFmOC0wM2M0LTRjNTAtYTM3Ny1lZGNjMTFlNTRlZGUiLCJ1c2VySWQiOiIzOGUyYTc5OS05ZjkzLTRjMGMtYWExNi0wOTVhMzY2NmQ3MjkiLCJwYXNzd29yZFJldmlzaW9uIjoxNjQwMTIxNDkzLCJpYXQiOjE2NDAxMzAyMTksImV4cCI6MTY0MDEzMzgxOX0.hf41k98X-Uto7Z4ZOx2bT0FAY7a14BIvafdmbM2BTeQ; path=/; samesite=strict; secure; httponly')>
2021-12-22 00:43:39 WARNING (MainThread) [custom_components.unifiprotect.camera] Camera does not have any channels: None (id: 616be15501c98703e70003f6)
2021-12-22 00:43:39 WARNING (MainThread) [custom_components.unifiprotect.camera] Camera does not have any channels: None (id: 616be15501a58703e70003f5)
2021-12-22 00:43:39 WARNING (MainThread) [custom_components.unifiprotect.camera] Camera does not have any channels: None (id: 616be15502168703e70003f9)
2021-12-22 00:43:39 WARNING (MainThread) [custom_components.unifiprotect.camera] Camera does not have any channels: None (id: 616be15501e38703e70003f7) `

**Comment by AngellusMortis** [comment]
Can you go to these following URLs in your Protect Web app and see if it shows cameras?

/protect/devices/616be15501c98703e70003f6
/protect/devices/616be15501a58703e70003f5
/protect/devices/616be15502168703e70003f9
/protect/devices/616be15501e38703e70003f7

I am curious if the 1.20 upgrade just gave you broken cameras or something odd.

**Comment by LuegM** [comment]
Yes I checked them, and those cameras are not adopted (_correct_) right now. 
Also the update to the beta has solved my problem. 
So everything works fine for me now 👍🏻 

Thanks for helping me that fast. 💯

**Comment by AngellusMortis** [comment]
Wait before you adopt them!

**Comment by LuegM** [comment]
Okay… I won’t do that right now.
But fyi they also weren’t adopted before.

**Comment by AngellusMortis** [comment]
Can you go to `/proxy/protect/api/cameras/616be15501c98703e70003f6` (or replace the ID with any of the 4 if they are not adopted) and search for `isAdopted` and tell me if is true or false? 

The issue might just be as simple as I have not been checking if devices are adopted by the current NVR before trying to add entitles for them. Haha.

**Comment by LuegM** [comment]
I checked the url you gave me, and it says:
`"isAdopting":false, "isAdopted":false, "isAdoptedByOther":true `

If you want me do check the others, just tell me… but I think it will be the same with them.

**Comment by AngellusMortis** [comment]
Okay, thanks that is all I needed. I will leave this issue open until I fix the underlaying issue (making sure to check `isAdopted` before trying to use the device).

**Comment by johnahyland** [comment]
Hi, I've upgraded HA from 2021.11.4 to 2021.12.4 and the camera entities are no longer available.  I'm using UniFi-CloudKey-Gen2-Plus Network Version 6.5.55 Protect with a number of cameras and have also tried the beta v0.11-2.beta1.

HA Shows I have the 9 devices but the camera entity is no longer available.

![image](https://user-images.githubusercontent.com/84412390/147113358-947000f2-9394-4bef-93fe-ee0f0d0f5274.png)

![image](https://user-images.githubusercontent.com/84412390/147113631-db46c5ad-7135-4744-8a5c-f0459df8d935.png)


Would you have any ideas?

**Comment by AngellusMortis** [comment]
Are the cameras already adopted? If so, it is unrelated to this issue. Please make a separate one.

**Comment by johnahyland** [comment]
Hi @AngellusMortis Ok, thanks, I'll create a separate issue

**Comment by tobes49** [comment]
HI,

You seem to have worked out what the problem is.   I do have un-adopted camera on my protect
![unifiProtect](https://user-images.githubusercontent.com/73558713/147152833-2a5ec902-ea80-4c0a-a270-b8c493081419.jpg)
The top 3 bullets are managed by Cloudkey gen2 (at a different location, 2 miles away but link to my network by some nanobeams) - these never used to appear but from the 1.20.1 update they now appear in my device list!

Currently my cameras still don't work on Home assistant, would it be best to wait for the next beta or is there a temporary fix I can do?

Many thanks for the fast help.

**Comment by tobes49** [comment]
Found it, reloaded the integration and the entities have changed name.
Still have the warning for the 3 un-adapted ones
Just need to figure out why the door bell is no longer working.

Thanks again for the help,
Have you got a donation page?

**Comment by AngellusMortis** [comment]
Yeah, there will be a warning about them for now. Once 0.11.2 comes out, you will stop getting the warning.

**Comment by AngellusMortis** [comment]
0.11.2 is released. Unadopted entities should now be completely ignored.
