### ISSUE TITLE
No camera feed

### ISSUE THREAD

**Issue by agrauballe** [briis/unifiprotect#437]
### Home Assistant Version?

2021.12.5

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

0.11.4

### What happened?

Just played around in my home assistant today for another purpose, but just saw that the camera entity from unifi protect was unavailable for all my three cameras. Tried to reload the integration, but same result. Ended up in deleting the integration and installing again. Now the camera "feed" entity (camera.x) is missing.
Anybody else seeing this issue? Also noticed that my UDM-pro has been updated to 1.11.0 recently.

![image](https://user-images.githubusercontent.com/92588941/147704013-82103b45-b65d-4369-94da-b508ec98cde4.png)

**Comment by AngellusMortis** [comment]
Your camera entity is right there. The "High" one.

2021.11 started hiding/collaps8ng entities names that matched the device name. So if the device is named "Front Yard Camera" and the entity is named "Front Yard Camera High", HA only shows it as "High". 

0.11.x also added entities for all enabled channel qualities (High/Medium/Low) and changed the entity naming scheme to match what HA was expecting so it can collapse the names like that.

**Comment by agrauballe** [comment]
@AngellusMortis 
Yes I see that it is under camera.x.high now. was just camera.x before. Thanks.
Closing issue.

**Comment by AngellusMortis** [comment]
Yep, that happened because you deleted the integration, so you automatically go the new naming scheme.

1.20.2 of UniFi Protect had some issues with the application crashing a lot. That is probably what you got hit by.
