### ISSUE TITLE
Camera does not support play stream service

### ISSUE THREAD

**Issue by amoklilli** [briis/unifiprotect#439]
### Home Assistant Version?

2021.12.7

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

0.11.4

### What happened?

The automation should stream the camera-feed to one of my nest-hub. The real integration fires when the ring-button is pressed. I've attached a test-automation to reproduce the error. I'm not for how long it's not working. We barely get visitors.

I've tried with different nest-hub, but unfortunatly have only one camera at the moment.

But now every time there is the error message:

Camera does not support play stream service

If you need any more information, just let me know.

Great work btw. to get this into ha-core!

### Relevant log output

```shell
Triggered manually at 31. Dezember 2021, 19:49:12
Call service camera.play_stream on devices 6c5b1dd74de2e020ccda575e8f95dfd6
Stopped because an error was encountered at 31. Dezember 2021, 19:49:12 (runtime: 0.01 seconds)

camera.haustuer_high does not support play stream service
Not all shown logbook entries might be related to this automation.

id: '1612475988827'
alias: Test
description: ''
trigger: []
condition: []
action:
  - service: camera.play_stream
    target:
      device_id: 6c5b1dd74de2e020ccda575e8f95dfd6
    data:
      media_player: media_player.hub_kuche
      format: hls
mode: single
```

**Comment by amoklilli** [comment]
Showing the video-feed in the home-assistant app or in the unifi-protect-app works fine. As does taking snapshots and sending them via notification to the mobile app.

**Comment by AngellusMortis** [comment]
Do you have RTSP enabled on your camera? And/or have you enabled the "Disable the RTSP stream" config option?

**Comment by amoklilli** [comment]
Man I'm feeling really stupid right now. Had some issues with the camera and had to unmanage/manage the whole thin and do a factory reset. RTSP must have been disabeld by that. It's working as designed after enabling that. Must have forgotten to check as I mostly use the mobile-app of unifi-protect. Sorry!

Anyway:

Thanks for the quick and awesome respone. I wish you all the best for 2022 and a happy new year.

Best regards!
