### ISSUE TITLE
Typo cpu utilization

### ISSUE THREAD

**Issue by Mulle00** [briis/unifiprotect#443]
### Home Assistant Version?

2021.12.7

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

0.12.0-beta5

### What happened?

In my opinion, the CPU usage factor of 10 is miscalculated. 
In HA, usage is shown as 1.1%. In UniFi OS is that around 12%.

**Comment by AngellusMortis** [comment]
It is not a typo and the values are not calculated. They come directly from UniFi Protect. UniFi OS != UniFi Protect. I have always noticed discrepancies between values reported by the various different locations and apps (UniFi Network, UniFi OS, UniFi Protect).

![image](https://user-images.githubusercontent.com/490848/148230282-a27ef5e9-073a-450e-b20c-03e05658f282.png)
