### ISSUE TITLE
Integration will not load after moving from v0.12.0-beta6 to 11.4

### ISSUE THREAD

**Issue by curt7000** [briis/unifiprotect#450]
### Home Assistant Version?

2021.12.8

### UniFi Protect Version?

1.20.1

### UniFi Protect HA Integration version?

0.11.4

### What happened?

HACS reported and update from 0.11.4 to v0.12.0-beta6.  I left it and tried moving to it last yesterday, all was working well, then saw a update this AM for 0.11.4, let HACS update, but now it will not come back.

### Relevant log output

```shell
Logger: homeassistant.setup
Source: setup.py:153 
First occurred: 10:05:41 AM (1 occurrences) 
Last logged: 10:05:41 AM

Setup failed for unifiprotect: Integration not found.
```

**Comment by AngellusMortis** [comment]
For some reason HACS broke for people that accidently installed the 0.12.0-beta6 version I accidently marked as stable. 

https://community.home-assistant.io/t/custom-component-unifi-protect/158041/811

You can fix it by move `/config/custom_components/unifiprotect/unifiprotect` to `/config/custom_components/unifiprotect`. Or just completely delete `/config/custom_components/unifiprotect` and re-install it.

**Comment by AngellusMortis** [comment]
I had a user report that downgrading to HACS 1.17 fixes the issue. You may try that as well. 

It is less then 4 weeks until UniFi Protect is in core though and no more HACS!

**Comment by AngellusMortis** [comment]
Confirmed from the HACS dev. It looks like 1.19 of HACS is causing the issue. Downgrading to 1.17 or 1.18 should fix it. **If you have not yet upgraded to 1.19, do not do it.**

**Comment by curt7000** [comment]
I rolled HACS to 1.18, redownloaded, all is working now!  Thanks for the super fast response!  Looking forward to seeing this in Core, one of my critical HACS integrations!
