### ISSUE TITLE
Request to disable the doorbell chime at night

### ISSUE THREAD

**Issue by wolterink** [briis/unifiprotect#451]
### New Feature

There is a setting to set the Chime type in the doorbell settings. (NONE, mechanical, digital). 
Would it be possible to have these settings available within home assistant? This would enable me to set a schedule to set the internal chime to "none" at night so it doesn't wake the children.

**Comment by AngellusMortis** [comment]
I thought setting Chime Duration to 0 would accomplish the same thing. I will do some further testing this week and make sure there is a way in HA to disable your chime via automation. If there is not, I will add it.

**Comment by AngellusMortis** [comment]
Digging more into it yeah, Chime Duration is what you want. I actually need to update the entity to be a select instead of a number slider. It looks like:

* Chime Duration of 0 = Chime Type of None from the Protect UI
* Chime Duration of 300 = Chime Type of Mechanical from the Protect UI
* Chime Duration of 1000 = Chime Type of Digital from the Protect UI

**Comment by wolterink** [comment]
Thank you for the quick response. I found that setting now (number.doorbell_duration). I will have some tests with that one to see if I can get the effect I want with it. But if you can change the slider into a select box that would be great.

**Comment by wolterink** [comment]
I can confirm, setting "number.doorbell_duration" to "0" will disable the chime box. And "300" will again enable it. This will work for now, but I'm look forward to having a select box instead. Thank you

**Comment by AngellusMortis** [comment]
I have everything I need to make the select, but it is a breaking change, so I am waiting until we finish the HA core migration before I start adding "new" features that are breaking. I have a bunch of stuff to add for the UP Sense and G4 Doorbell Pro as well.

**Comment by AngellusMortis** [comment]
"Chime Duration" number entity has been replaced with a "Chime Type" select entity in 0.12.0-beta10

**Comment by nannoz** [comment]
Will this change remove the option to change the duration of the chime? Because I now use it to set my mechanical chime to ring for something over 2 seconds. This way I can't miss it if someone is at the door. At night I just set the duration to 0 with an automation.

**Comment by AngellusMortis** [comment]
Yes. It may be called the "chime duration", even internally in the app, but I do not fully understand how the field works. Setting to a different value then what Protect does in the app could be dangerous and damage your doorbell. So, the new Select limits you to the same 3 choices that Protect gives you (None, Digital, Mechicnal).
