### ISSUE TITLE
Feature request: update interval for camera.

### ISSUE THREAD

**Issue by vandalon** [briis/unifiprotect#46]
Hi,

Would it be possible to have configurable update_interval for the camera when not using the streaming option? Now it only updates once every 10 seconds and it would be nice to have it update every second.

Thanks!

**Comment by briis** [comment]
I assume when you say it only updates every 10 seconds, you mean the camera image? I have been digging in to this, and as I can see there is no way to change the image update frequency. Even if you set the Scan Interval to 1 seconds, it will only be the attributes that change, not the image.
I am not sure if people with more knowledge than me of the CORE working of HA, has another view.

Anyway, if you could set it to 1 second, you will make a call to Unifi Protect every second to fetch the image - that might put an undesired strain on the Unifi system

**Comment by vandalon** [comment]
Yes that is what I meant :)
Only when a camera view is open it will pull the image every second. I think the strain on the cloudkey will be limited. I know pull the image directly from the camera's every second via the generic camera integration. This works ok but you get the full quality image whereas the unifi protect api offers a smaller snapshot :)

**Comment by vandalon** [comment]
(Also I am running HA directly on the cloudkey so it would be ideal to just access localhost ;-))

**Comment by briis** [comment]
I will not implement this as it violates the standard way Home Assistant operates. But you are welcome to Fork the project and make it yourself.
Sorry, for this.
