### ISSUE TITLE
Not receiving Object Detection changes on sensors on 3 of 4 cameras

### ISSUE THREAD

**Issue by JohnGalt1717** [briis/unifiprotect#461]
### Home Assistant Version?

2021.12.9

### UniFi Protect Version?

1.21.beta-3

### UniFi Protect HA Integration version?

0.11.4

### What happened?

My Unifi Doorbell works great with object detections and they show up fine in HA.  My dome and g4 cameras do not.  The Unifi app notifies me just fine on these for both vehicle and person.  But looking at the status of the sensor for object detection there is never anything recorded in HA for a change.

### Relevant log output

```shell
Nothing.
```

**Comment by AngellusMortis** [comment]
Please try 0.12-beta9 and add logs.

**Comment by UrbanDave** [comment]
Hi there, I have G4 cameras as well with the same issue, I was running beta9, I just upgraded to beta10 and will continue to monitor.

**Comment by AngellusMortis** [comment]
Since there has been no response for more data, I am just going to assume it is a duplicate of https://github.com/briis/unifiprotect/issues/441. If you have logs or proof this is not because of the Websocket disconnecting and not reconnecting, please make a new issue with the details.
