### ISSUE TITLE
0.12.0-beta11 triggered status LED to be turned on

### ISSUE THREAD

**Issue by Calimerorulez** [briis/unifiprotect#462]
### Home Assistant Version?

2021.12.9

### UniFi Protect Version?

1.21.0-beta3

### UniFi Protect HA Integration version?

0.12.0-beta11

### What happened?

Not a major issue, but I just upgraded to 0.12.0-beta11 and after that I noticed that on my G3 Flex's and my G3 Instant, the blue status LED was turned on, on the camera and in the camera settings of the camera in Protect.

Before the upgrade they were disabled.

Strange thing is, that my G4 Instant did not have its status LED turned on after the upgrade.

**Comment by Calimerorulez** [comment]
"To be turned on" is kind of strangely formulated, but I think you will now what I mean ;)

**Comment by AngellusMortis** [comment]
Not related to this integration. Either they were turned on inside of UniFi Protect outside of HA or there was an HA bug that cause them to be turned on. This integration only creates the entities, there is no code that changes the status of them.

**Comment by Calimerorulez** [comment]
Ok, clear.
