### ISSUE TITLE
Doorbell not showing correct Text from Doorbell Text select entity

### ISSUE THREAD

**Issue by gulli1986** [briis/unifiprotect#467]
### Home Assistant Version?

2021.12.10

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

0.12

### What happened?

Hello,
I managed to edit a list of custom doorbell text in HA using `unifiprotect.add_doorbell_text` service. I also restarted HA after adding the text messages as mentioned in the release note.

The list is updated in HA as shown below:
![g](https://user-images.githubusercontent.com/84970544/151174898-eb7fb3c9-c9f0-43f4-899d-aa2d654f3968.PNG)
 

However it doesn't seem like the list is updated in unifi protect:
![h](https://user-images.githubusercontent.com/84970544/151175102-54a28ed1-0180-4772-9c78-68eb1bc50d5a.PNG)

When I choose a text from my list in HA, it justs shows the CUSTOM_MESSAGE on the doorbell and in Unifi Protect.

Is that a bug or I am missing something?
I was using the old method of inputing text to the doorbell before I updated the integration to 0.12 and it was working fine if that can help.

**Comment by AngellusMortis** [comment]
What does the actual doorbell show?

**Comment by gulli1986** [comment]
@AngellusMortis it shows as in Unifi Protect : CUSTOM_MESSAGE

I am able to set the text dynamically, just tested it.

**Comment by AngellusMortis** [comment]
I do not mean what does it show in UniFi Protect. I mean _what does the physical doorbell in real life_ show.

**Comment by gulli1986** [comment]
Well understood, _the physical doorbell in real life_ shows the same text as in Unifi Protect which is CUSTOM_MESSAGE when trying to select a text from the HA list:

![IMG_1593](https://user-images.githubusercontent.com/84970544/151176586-a4349939-c5e8-465b-b4ee-96167043256c.JPG)

**Comment by AngellusMortis** [comment]
Okay, thanks for verifying. The UniFi Protect Web app does not always show the correct message.

**Comment by briis** [comment]
I see the same thing @AngellusMortis. Tried to remove all custom messages and add a few again. The select the new messages from the Select Dropwdown, and then I get the same result `CUSTOM_MESSAGE`

**Comment by AngellusMortis** [comment]
Yeah, I was able to verify it as well. I was checking it while were looking. Something probably went wrong with the select look up. Digging into it now.

**Comment by gulli1986** [comment]
It looks like the list from HA is not "transferred" to Unifi Protect.
When trying to select the pre-registered messages like "DO NOT DISTURB" or "LEAVE PACKAGE AT DOOR", then it works.

**Comment by gulli1986** [comment]
> The saved messages list only appears in the Android or iOS app. Not the Web app.

 OK thanks for the input! :)

**Comment by AngellusMortis** [comment]
Issue will be fixed in the HA core beta that comes out later today. It will _not_ be backported to HACS.

**Comment by gulli1986** [comment]
Thanks @AngellusMortis, much appreciated.
