### ISSUE TITLE
Enhancement: Door Lock support

### ISSUE THREAD

**Issue by zacs** [briis/unifiprotect#468]
### New Feature

Hi there, I am hoping to get the door lock supported in the integration. It's currently in EA, but I just installed mine. 

I've tried to dump sample data using the below, but nothing is ever written to `/config`

```
unifi-protect generate-sample-data -o /config/ufp-data --actual -w 300 -v -U username -P password -a IPADDR
```

Let me know if there are updated instructions on gathering the sample and I'll be happy to send along via HA community message.

**Comment by AngellusMortis** [comment]
Already completed. It is in the HA Core 2022.2.0b0 release. It will **not** be backported to HACS.

**Comment by zacs** [comment]
Totally missed that in the notes, thank you! Time to upgrade from 2021.12 :)
