### ISSUE TITLE
config deprecated

### ISSUE THREAD

**Issue by ensjens** [briis/unifiprotect#47]
when using the sample configs, a warning is given in the HA log:

SwitchDevice is deprecated, modify UnifiProtectSwitch to extend SwitchEntity
BinarySensorDevice is deprecated, modify UfpBinarySensor to extend BinarySensorEntity

I am still able to get a motion sensor entity, but no switch entity is created

**Comment by ensjens** [comment]
I am on Home Assistant 0.110.0.dev20200512
Unifi Protect Integration V0.3.1

**Comment by briis** [comment]
I am aware of this, as I am testing on the 0.110 dev branch also. But I still get both Switches and Binary Sensors created, I just have the 'Deprecated' warning in the logs. It is strange that you don't get Switches created, as they should be supported, even with the 'old' naming.

The issue right now is that if I change to SwitchEntity and BinarySensorEntity, it will stop working for people who are not on 0.110, so it will have to stay there for a few versions.
