### ISSUE TITLE
Person detected do not trigger motion sensor

### ISSUE THREAD

**Issue by gulli1986** [briis/unifiprotect#470]
### Home Assistant Version?

2021.12.10

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

0.12

### What happened?

Not sure if this is a bug or supposed to work that way. Let's say I have a camera name "driveway".

At 21.33 pm last night `sensor.driveway_detected_object ` detected a person and triggered, see below. If you look at `binary_sensor.driveway_motion` however, you can see that it didn't update:

![person](https://user-images.githubusercontent.com/84970544/151652706-163a99c8-ee29-4b6d-b82e-27f7743ebe66.PNG)

![motion](https://user-images.githubusercontent.com/84970544/151652709-72595676-3927-4ebf-9027-f073adf23f5e.PNG)

It has happened several times so this is quite consistent.

For me, if a person is detected, it is because there have been motion, and hence the motion sensor should also have triggered which is not the case here.

Is it supposed to work that way?

If yes it makes using the motion sensor difficult to use because it will not triggered when a person is detected which I would like to. Using motion and object combined is not easy because sometimes both will triggered if the camera detects both a person and a motion which will make the automation trigger 2 times.

**Comment by AngellusMortis** [comment]
The only way I am able to reproduce this is by changing default settings on my smart detection zones or my motion zones. If they both do not have the same exact settings, it can lead to the smart detect zone firing, but not the motion zone. Like if you delete the motion zone, turn down the sensitivity on the motion zone or turn up the sensitivity on the smart detect zone.

**Comment by gulli1986** [comment]
Strange, my motion zone and smart detection zone setting are identical, same sensitivy and zone selection.
I am getting motion in general, but in some cases, I only getting smart object (person) detection without the motion sensor to trigger. This has happened both on a G4 bullet and on my G4 doorbell.

I checked in Unifi and can actually see that sometimes it only report the smart detection without any motion so you are right this is not an HA issue. I guess I will just have to cope for that in my automations, checking both parameters from now one.

Anyway, thanks for your feedback!
