### ISSUE TITLE
Smart object detection triggers at the end of a person movement

### ISSUE THREAD

**Issue by gulli1986** [briis/unifiprotect#471]
### Home Assistant Version?

2021.12.10

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

0.12

### What happened?

I found out that if you make an automation that takes a camera snapshot and trigger using let's say `binary_sensor.driveway_motion `, the snapshot is taken instantaneously as the motion gets detected, this is fine and as expected.

However if I trigger the automation using the smart object `sensor.driveway_detected_object` (person), it looks like the snapshot is taken at the end of the motion.  This can be a challenge as the person gets outside of the camera view and the snapshot is taken too late (the picture is "empty" without the person in it).

I am wondering if this is an HA issue as it looks like the person is detected early enough in Unifi. If the snapshot was taken instantaneously, it would include the person but as mentioned, it looks like `sensor.driveway_detected_object` only triggers at the end of the person motion.

**Comment by AngellusMortis** [comment]
As mentioned in your previous issue. The sensors are updated from the data provided from UniFi Protect. If you do not like how your motion/smart detections are firing, you either need to tweak your settings or go to the community forums for UniFi Protect to complain.

We will be adding the ability to use event thumbnails in the future for notifications which should help with consistently getting a usable image, but as of now, you are pretty much at Protect's mercy if the snapshot is going to line up with the smart detection depending on how "fast" the smart detections clears.

**Comment by gulli1986** [comment]
Understood, thanks.
