### ISSUE TITLE
All cameras Privacy turned at the same time

### ISSUE THREAD

**Issue by tekjc** [briis/unifiprotect#472]
### Home Assistant Version?

2021.12.10

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

1.19.3

### What happened?

All at the same time all my cameras were set to Privacy mode.  All the overlays were turned on at the same time as well.  The home  
 assistant logs say it was turned on by supervisor.

**Comment by AngellusMortis** [comment]
1.19.3 is not a valid version for the Integration.


Also, this issue not an issue with UniFi Protect. As you said supervisor turned them on. You would need to make an issue with [HA core](https://github.com/home-assistant/core/).

**Comment by tekjc** [comment]
Your correct, I put in the version of HACS I was running.  I am on the latest version of Unifi Protect as I just installed it a few days ago.  Thanks for the reply.  I will follow up in the HA forums.

**Comment by AngellusMortis** [comment]
If you do find the cause or get more information, please let us know! We have had a number of users report switches randomly turning on.

**Comment by tekjc** [comment]
Will do!  For now I just made the user with read only rights to prevent it from happening until I figure out the cause.

**Comment by AngellusMortis** [comment]
You can also just disable the entities being flipped as well.
