### ISSUE TITLE
Removed Unifi Camera in Unifi Protect still listed in HA as device .. cannot be removed nor disappearing?

### ISSUE THREAD

**Issue by joergbattermann** [briis/unifiprotect#473]
### Home Assistant Version?

2022.2.0

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

The 'officialversion that comes with 2022.2.0

### What happened?

Removed a G4 Dome camera days ago from my Unifi Protect / Cloud Key Gen2, however the unif protect HA integration still lists the device and there is no way to remove it.

Soooo how -do- I remove it?

**Comment by AngellusMortis** [comment]
This repo is not deprecated. Please report issues to the HA core repo.

**Comment by joergbattermann** [comment]
Thanks, I did just that: https://github.com/home-assistant/core/issues/65555

**Comment by AngellusMortis** [comment]
Sorry it got closed. I was afraid it might. They are really strict over there about what is a feature request and a bug!

**Comment by joergbattermann** [comment]
No worries Christopher, not taking it personally. I got the information I needed ("not supported").

Cheers and thanks!
