### ISSUE TITLE
sound

### ISSUE THREAD

**Issue by filoor** [briis/unifiprotect#50]
Hi,

Thank you for all your work.
The video is working great only i dont hear any sound?

**Comment by briis** [comment]
You are welcome. Unfortunately, the Stream component in Home Assistant currently does not support Audio  I don't have audio either. The feed you are getting from this Integration includes Audio, but HA does not have a way to output it. It will require some more work on `stream` which is not something I am able to do.

Sorry.
/B

**Comment by filoor** [comment]
Thank you so much for you quick response.
