### ISSUE TITLE
question about V0.4.0 installation

### ISSUE THREAD

**Issue by Golab** [briis/unifiprotect#52]
Hello I'm running

Home Assistant 0.110.0b4 on HassOS 4.6 Supervisor 222 beta Channel, I'm trying to install your V0.4.0,

1: I have dinstalld your add-on from HACS and also check that nothing is left in custom_components
2: I have rebooted my Hassio, now to my question is the files in custom_components/unifiprotect on 0.4.0  where should I put them? In /config? Is it the files or is it the folder unifiprotect  i need to copy from your github and place it in /config?

**Comment by briis** [comment]
You should put them in the same directory where the old files were: custom_components/unifiprotect 
The restart HA and go to Settings and Integration. Here search for UniFi Protect. Hope this helps. 
/B

**Comment by briis** [comment]
I will close this. Please re-open if it did not solve your issue.
