### ISSUE TITLE
Activation/Deactivation of notifications

### ISSUE THREAD

**Issue by Flodu31** [briis/unifiprotect#53]
Hello,
Do you know how to activate/deactivate notifications for one or more user?
Thanks.
Florent

**Comment by briis** [comment]
Hi Florent,
Is it notifications from the Unifi Protect APP or from Home Assistant?

**Comment by Flodu31** [comment]
Hi,
Directly from Unifi Protect App.
Thanks.
Florent

**Comment by briis** [comment]
Hi Florent,
It does not seem that you can do it in the settings page for the App, so the only way I can think off is to go to Notifications on the phone the user has, and remove the Notifications for the Unifi Protect App.

**Comment by Flodu31** [comment]
Ok thanks.
My goal is to have notification, only when I’m not at home.
Currently, when I’m at home, my camera stop recording (automation with your plugin). And when I’m not at home, I’ve notifications by mail.
Florent

**Comment by briis** [comment]
You are correct. Use Home Assistant to only send notifications when you are not home, and also here you can select who will get the notification. Seems you are on the right track. I will close this now.
