### ISSUE TITLE
Unique id in new version (0.4.0)

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#56]
Suggest using the mac address of the camera instead for the unique_id.
https://developers.home-assistant.io/docs/entity_registry_index/#unique-id-requirements

The bootstrap api returns it under the `mac` key.

https://github.com/briis/unifiprotect/blob/93ff559bd0146bc59e6a87ad97bad2e18ae22dd5/custom_components/unifiprotect/camera.py#L81

**Comment by briis** [comment]
MAC Address is now used for all components instead of camera_id to generate the Unique ID. Thx.
