### ISSUE TITLE
async_will_remove_from_hass can be removed from most platforms (0.4.0)

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#57]
In `async_added_to_hass` you have `self.async_on_remove` which means the listener will already be removed.

https://github.com/briis/unifiprotect/blob/93ff559bd0146bc59e6a87ad97bad2e18ae22dd5/custom_components/unifiprotect/camera.py#L196

**Comment by briis** [comment]
I assume the same applies for the Sensor, Binary_Sensor and Switch Components?

**Comment by bdraco** [comment]
Yes

**Comment by briis** [comment]
Fixed.
