### ISSUE TITLE
Adding device_info (0.4.0)

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#58]
If you add 
```
import homeassistant.helpers.device_registry as dr
    @property
    def device_info(self):
        return {
            "connections": {(dr.CONNECTION_NETWORK_MAC, self.mac_address)},
            "name": self.name,
            "manufacturer": ...,
            "model": ...,
            "sw_version": ...,
            "via_device": (DOMAIN, self.protect_server_unique_id),
        }
```

To each of the entities, Home Assistant will be able to map them together into a logical device.
https://developers.home-assistant.io/docs/device_registry_index/#device-properties

**Comment by briis** [comment]
Good suggestion, but I am not completely sure what to put in the `connections` and `via_device` fields? I have now added the MAC Address to the pyunifiprotect, so that we have access to that but I am still not sure how to ensure I link it all together?

**Comment by briis** [comment]
Ok, I made the changes and added device_info to all components, and it seems to group it logically in to the number of Cameras - which makes sense to me. Could you have a look and see if you agree with my implementation?

**Comment by B-Hartley** [comment]
I've installed 0.4.0 - all seems ok with my cameras and sensors.
HACS does seem to be behaving weirdly since i installed HACS 1.0

**Comment by briis** [comment]
Great to hear it still works for you. Yes, I need to get used to the new Interface of HACS. It might be cached data that prevents it from showing, so I'll give it a few hours.

**Comment by bdraco** [comment]
For the `via_device` you can register a the NVR itself.    You can use the `mac` in the `nvr` field of the `bootstrap` json
```
	"nvr": {
		"mac": "xxxx",
		"host": "192.168.208.1",
		"name": "UDMP",
```

An example of how to do this is here

https://github.com/home-assistant/core/blob/be416d9fc66306027991afbc2d9f22557bde794c/homeassistant/components/isy994/__init__.py#L225

**Comment by bdraco** [comment]
For the `device_info`

You can save a lot of code by using a base class.

Example
https://github.com/home-assistant/core/blob/be416d9fc66306027991afbc2d9f22557bde794c/homeassistant/components/powerwall/entity.py#L8

**Comment by briis** [comment]
Hi @bdraco 
I worked on the device_info piece, and I am now implementing it for both the Server and the Cameras. When first setting it up, it works great and I get 4 Devices with 15 entities, which fits with my environment of 3 Cameras and 1 CloudKey. However, after restart of HA the CloudKey disappears as a device, and I have only 3 left. I looked over it now for 2 days, and I can't figure where I am going wrong. Could you have a look?

**BTW** I messed something up and could no longer sync to Github with the v0.4.0 Branch. So I had to create a new branch, which is just called v0.4 - Please look in this for the newest files.

**Comment by bdraco** [comment]
The cloudkey disappearing much be caused by a bug that might have been fixed in https://github.com/home-assistant/core/pull/35977

Can you check to see if 0.110.2 fixes this?

**Comment by briis** [comment]
I did an upgrade on my dev container (0.111) and now it seems to be stable and stay there. I will try on the 0.110.2 a bit later, to see if that also works.

**Comment by briis** [comment]
Hi @bdraco 
I believe that now both the device info and the base entity has been implemented.

**Comment by briis** [comment]
I will close this now, as this has all been implemented. Thanks again.
