### ISSUE TITLE
Update can be broken up now that data coordinator is used

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#59]
https://github.com/briis/unifiprotect/blob/5c30c6645d8946301af776b175175cc338bd3733/custom_components/unifiprotect/camera.py#L128

In `def update` above the coordinator data is available in the properties that are using it so they can be moved out of `def update` into the properties and the coordinator data accessed directly since its not doing any I/O.

Then you can delete `def update` and replace it with `async def async_update` from https://developers.home-assistant.io/docs/integration_fetching_data/

```
    async def async_update(self):
        """Update the entity.

        Only used by the generic entity update service.
        """
        await self.coordinator.async_request_refresh()
```

This will allow users to make use of the generic entity update service to request the entity updates now: https://www.home-assistant.io/integrations/homeassistant#service-homeassistantupdate_entity.

You'll also be able to remove the `should_poll` as well https://github.com/briis/unifiprotect/blob/62c90b4912e81fcf989769839c730245a813e6b7/custom_components/unifiprotect/camera.py#L94

**Comment by briis** [comment]
Works like a charm and is now modified in camera.py. Damn I learn a lot.
