### ISSUE TITLE
Some or all services can be replaced with entity services

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#61]
https://github.com/briis/unifiprotect/blob/62c90b4912e81fcf989769839c730245a813e6b7/custom_components/unifiprotect/__init__.py#L134

https://developers.home-assistant.io/docs/dev_101_services#entity-services

You can use entity services which will significantly reduce the amount of code needed to implement the services.

**Comment by briis** [comment]
Is there a component (beside Sonos) that you can point me too, as I am not completely sure how my current implementation differs from what dev docs suggest?

**Comment by bdraco** [comment]
`harmony/remote.py` has an example

````
    platform.async_register_entity_service(
        SERVICE_SYNC, HARMONY_SYNC_SCHEMA, "sync",
    )
    platform.async_register_entity_service(
        SERVICE_CHANGE_CHANNEL, HARMONY_CHANGE_CHANNEL_SCHEMA, "change_channel"
    )
```

Note that entity services will call the method on the entity itself by default so if you want to call an entity service like `unifiprotect.set_ir_mode` on `camera.XYZ`

```
    platform.async_register_entity_service(
        "set_ir_mode", IR_MODE_SCHEMA, "async_set_ir_mode",
    )
```
You can do something like the above and then add a 

`async_set_ir_mode` to the entity in `camera.py`

**Comment by briis** [comment]
Hi @bdraco 
First and foremost, I want to thank you for all the great suggestions and guidance - I really learned more of good coding over the last few days than ever before - so a BIG thank you.

But this piece about the Service I can't grasp. I tried different ways based on your guidance and looking at the Harmony code, but I am confused about where to put things and how to rewrite the existing code. If you have the time, I would appreciate if you could take one of the three services and show me how this can be done in the context you specify here.

**Comment by bdraco** [comment]
@briis Glad I could help 😄 

I pushed up an example here https://github.com/bdraco/unifiprotect/commit/9b92446d1e9c9f6d006ea0fd0a78e4b0e68881ff  (untested so it may need some tweaking)

**Comment by briis** [comment]
Damn this was easy - once I understood it. It works perfectly, so now I just need to convert the remaining two services. Thanks again.

**Comment by briis** [comment]
This is done, so I will close the issue.
