### ISSUE TITLE
Unloading the config entry

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#64]
https://github.com/briis/unifiprotect/blob/62c90b4912e81fcf989769839c730245a813e6b7/custom_components/unifiprotect/__init__.py#L228

We usually unload all the platforms at the same time as its faster.  We also check if any of them fail and return false so the user is presented with a message that they need to restart to fully unload.

Example:

https://github.com/home-assistant/core/blob/be416d9fc66306027991afbc2d9f22557bde794c/homeassistant/components/august/__init__.py#L178

**Comment by briis** [comment]
Code changed. Thx.
