### ISSUE TITLE
Code readability suggestion

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#65]
https://github.com/briis/unifiprotect/blob/62c90b4912e81fcf989769839c730245a813e6b7/custom_components/unifiprotect/binary_sensor.py#L123

You can safe yourself some indentation and improve the code readablity by doing something like

`camera_data = self.coordinator.data[self._camera_id]`

And then changing all the instances of `self.coordinator.data[self._camera_id]` to `camera_data`

**Comment by briis** [comment]
All cleaned up. Thx.
