### ISSUE TITLE
Side effects in __init__

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#66]
https://github.com/briis/unifiprotect/blob/62c90b4912e81fcf989769839c730245a813e6b7/custom_components/unifiprotect/binary_sensor.py#L88

HomeAssistant core doesn't allow side effects in `__init__`.  In this case moving the logging to `async_setup_entry` should take care of this.

**Comment by briis** [comment]
Got it, and changed the code. Thx.
