### ISSUE TITLE
Returning attributes

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#67]
https://github.com/briis/unifiprotect/blob/5c30c6645d8946301af776b175175cc338bd3733/custom_components/unifiprotect/sensor.py#L96

Instead of building the `dict` one key at a time you can return the whole thing in one shot which is more efficient 

```
        return {
            ATTR_ATTRIBUTION: DEFAULT_ATTRIBUTION,
            ATTR_BRAND: DEFAULT_BRAND,
            ATTR_CAMERA_TYPE: self._camera_type,
            ATTR_FRIENDLY_NAME: self._name
        }
```

**Comment by briis** [comment]
All fixed now. Thanks.

**Comment by bdraco** [comment]
I put a suggestion in the commit here

https://github.com/briis/unifiprotect/commit/f93e256023d463197b48ae08d3415d4c8d2b0d6e#r39400089
