### ISSUE TITLE
Home Assistant can retry setup later if the protect server is offline.

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#69]
https://github.com/briis/unifiprotect/blob/6bcc09c3bb222d9e243cd6b326bd8cbd793b708f/custom_components/unifiprotect/__init__.py#L110

If you move the `server_information` cal before `await coordinator.async_refresh()` you can do something like this (untested example):

```
        try:
            nvr_info = await protectserver.server_information()
        except NotAuthorized:
            _LOGGER.error(".....message about needing to resetup the integration because auth failed.")
             return
        except NvrError:
            # Home Assistant will try again later 
            raise ConfigEntryNotReady
```

When you raise `ConfigEntryNotReady` Home Assistant will retry to setup the integration so if the protect server is down, upgrading, or restarting the integration still gets setup when things get back to normal.

You'll need this import
`from homeassistant.exceptions import ConfigEntryNotReady`

**Comment by briis** [comment]
Great Idea, which I implemented.
