### ISSUE TITLE
Restarting Home assitant let all camera's disappear

### ISSUE THREAD

**Issue by DirkTas67** [briis/unifiprotect#72]
When setting up the unifi protect I get all devices, that is all 3 camera's that I have and the Cloud key 2+, but when restarting Home assistant, every device is not available.

![Schermafdruk van 2020-05-30 21-54-09](https://user-images.githubusercontent.com/30079864/83337987-2405c580-a2c0-11ea-9b4b-dc27f2337e8b.png)
![Schermafdruk van 2020-05-30 21-53-51](https://user-images.githubusercontent.com/30079864/83337988-2536f280-a2c0-11ea-9368-aa2a33401418.png)
![Schermafdruk van 2020-05-30 21-53-36](https://user-images.githubusercontent.com/30079864/83337989-2536f280-a2c0-11ea-82b0-e63514d12425.png)

When removing the integration and adding it again everything is available again.

Regards
Dirk

**Comment by briis** [comment]
Sorry for the delay Dirk. Can you tell what version of HA you are running? I have not been able to reproduce this error, so I am just looking more info on your environment.

**Comment by DirkTas67** [comment]
Hello Briis,

Supervisor 225, OS version 4.8, HA Core 0.110.1
Latest version of Unifi protect. 

The problem started some weeks ago, but I really have no idea when exactly, I thought it would fix itself.

Regards
Dirk

**Comment by briis** [comment]
Hi Dirk,
It is hard to debug, as you don't get any errors and I can't reproduce. But sometimes when things like this happens, there are some old stuff floating around that might disturb, so can you try the following:

1. Make sure there are no references to *unifiprotect* in your yaml files
2. Delete all files in the `custom_components/unifiprotect` directory, including `__pycache__` 
3. Copy the files from [here](https://github.com/briis/unifiprotect/tree/v0.4/custom_components/unifiprotect) to your unifiprotect directory.
4. Restart Home Assistant
5. Add the Integration, and then try to restart again.

**Comment by DirkTas67** [comment]
Hello Briis,

I totaly understand.

Coincidence sometimes changes things, last night I had problems with Homeassistant, it suddenly stopped working (homeassistant runs on a proxmox server), I had to reinstall everything, coulnd't get it working again, the supervisor refused to start and the problem with that was that samba also didn't start and the problem with that was.... you can guess.

The last backup was from 13 March 2020, so today I reinstalled everything and restored the backup, I was back in version 0.108.something, and the first I saw was my camera's again, strange I tought!


![Schermafdruk van 2020-06-04 12-53-44](https://user-images.githubusercontent.com/30079864/83748465-87964700-a662-11ea-98e5-080bdfd48022.png)


So I had to upgrade everything again, also to the lastest version of unifi protect integration. and now I have another problem, so first I install  the unifiprotect in HACS/integrations, if I add the 0.3.4 version and add the unifiprotect info in configuration.yaml everything is fine, if I add the 0.4-beta2 then I can remove the information in configuration.yaml and I have to add it in configuration/integrations then add and search unifiprotect, the problem is I don't have unifiprotect in the list, 'unifi' just show the ubiquiti unifi integration!

Any idea's? I have added it before so I don't understand why I can't add it now.

Regards
Dirk

**Comment by briis** [comment]
Hi Dirk,
There is a new release out now, called 0.5 which is the official release to support the Integration Page. Could you please try to install this, and let me know if this works for you.

**Comment by tobbensoft** [comment]
Hi

I think I have the same issue.. Some more info below

Running Home Assistant 0.111.0b2 and v0.5 of unifiprotect on UDMP 1.7.2-rc.4

When adding v0.5 from the HACS integration page it does not let me add any connection/credentials for the UDMP. (No error either, tested with never used browser so it should not be a caching problem) Debug possible?

After removing the old version all entities are renamed but not available. 

Any more I could check to be able to nail this down?

**Comment by tobbensoft** [comment]
@DirkTas67 do you use the HACS integration page and not HA's own?

**Comment by briis** [comment]
@tobbensoft A few clarifying questions:
You removed the previous version of Unifi protect and cleaned out the configuration files for all manual entries?
You then installed version 0.5, did you restart Home Assistant after that?
After the restart, when you go to the *Configuration* tab, and then select *Integrations* are you not seeing Unifi Protect as an installation option?

What do you mean when you say 

> @DirkTas67 do you use the HACS integration page and not HA's own?

 You can only use HACS to install the Integration in Home Assistant (Copy the files to Home Assistant), to set it up, you will have to use the process I described above to actually get it running in Home Assistant.

**Comment by tobbensoft** [comment]
@briis 

- You removed the previous version of Unifi protect and cleaned out the configuration files for all manual entries? **Yes**
- You then installed version 0.5, did you restart Home Assistant after that? **Yes**
- After the restart, when you go to the Configuration tab, and then select Integrations are you not seeing Unifi Protect as an installation option? **It is installed, but shouldn't there be a dialog somewhere to add credentials/connection information?**

And for the question from @DirkTas67 I think he is looking for the integration in the wrong place.

**Comment by briis** [comment]
Here is what I see when I go to the *Integrations* page and click the Yellow + Button at the bottom right and then type *Unifi*:
![image](https://user-images.githubusercontent.com/24776272/83996905-7d739180-a95d-11ea-8ae5-9408b9f30d4c.png)

And when selecting *Unifi Protect* I get the following:

![image](https://user-images.githubusercontent.com/24776272/83996964-9da35080-a95d-11ea-99bf-bf06cabd1c1c.png)

If Unifi Protect is not on the above list, then it is most certainly a caching problem in your browser. You could check the `custom_components/unifiprotect` folder to see if there is a file in there called `config_flow.py` if there is, I am 99.9% sure it is a caching problem.

**Comment by tobbensoft** [comment]
@briis 

You are correct, I was confused as it is called Integration in both HACS menu and in the HA Integration menu... (Plus probably a caching issue)

Now it seems correct, only need to adress that it readded the entities with a "_2" after the name.

**Comment by tobbensoft** [comment]
They seem to be stuck there...  
I may done something in the wrong order when I tried to find out what was wrong.

But it was a simple fix to remove and change the names with the entitie "editor" in the UI. :)

Thanx!

**Comment by briis** [comment]
Perfect - And you are welcome.

**Comment by DirkTas67** [comment]
[](url)
