### ISSUE TITLE
After reinstall of unifiprotect component it doesn't show up in HA integrations

### ISSUE THREAD

**Issue by Deez73** [briis/unifiprotect#76]
Hi, thanks for a fantastic component @briis !

I had v.034 previously installed and running fine (with manual entries in YAML configuration)

Then I deleted manual YAML, upgraded to v.05 via HACS and the HA integration could be added fine and everything was running fine.

But I got the _2 suffix to all cameras, so I decided to clean it up and reinstall.

So, I uninstalled v.05, removed camera entities I HA to clean my install.

After installing the v.05 via HACS again, the component installs fine, but it is not visible via HA integrations, so I can't add it now. It was working as intended the first time as described above, but not since uninstalling and reinstalling the component.

Did restarts of HA between all changes, and have also now tried rebooting the rpi3 host itself, but the unified protect component is not showing in HA integrations to be added.

Any ideas?

**Comment by briis** [comment]
99% of the times this is a Browser Cache issue. Could you try and Force a Refresh of your browser and/or clear the browser cache, and see if that does not fix it? I have had a few coming with the same problem today and that fixed it for them.

**Comment by Deez73** [comment]
Tried clearing entire cache on my primary browser (Safari) but no change... installed another browser (chrome) and still the same result. The Unifi protect HACS addon doesn't show in the HA integrations list (which as stated above worked perfectly the first time before uninstalling)
Running latest HA (0.110.5)

**Comment by briis** [comment]
Can you access the `custom_components/unifiprotect` directory? If yes, could you go there and delete the `__pycache__` directory, and then restart Home Assistant, and see if it works? Also just check, if there is a file called `config_flow.py` in the unfiprotect directory. (Just to make sure that you do have the latest version)

**Comment by Deez73** [comment]
There is no cache directory (guess it is because the integration was never started this time around?)

Config_flow.py is present

After uninstalling the previous version I checked that the unifiprotect directory under custom_components was deleted, which it was.

Maybe HA doesn’t recognize the component to be back after the previous uninstall? I have also checked that the integration is not marked as ignored.

**Comment by briis** [comment]
I am honestly out of ideas. The last thing I can suggest you try, is: 
* Go to HACS, and remove the Integration
* Restart Home Assistant
* Install Unifi Protect from HACS again
* Clear your Browser Cache and make a Hard Refresh
* Go to *Configuration* Tab and the *Integrations* menu, and see if it now shows up after pressing the Yellow + Plus button in the lower right corner.

**Comment by Deez73** [comment]
After restoring a snapshot of HA 0.110.3 with HACS 1.0.3 and then upgrading to HA 0.110.5 and HACS 1.1.0 the problem persisted. Restoring the snapshot again and not upgrading HA or HACS the UnifiProtect was able to install fine and the integration was visible through HA...
I don’t know what was the cause, but since I don’t expect it to be with your component I close this issue.
Thanks for your help and suggestions.

**Comment by briis** [comment]
Thanks for reporting back. Glad it now works.
