### ISSUE TITLE
Camera only updates every 10 seconds

### ISSUE THREAD

**Issue by timmillwood** [briis/unifiprotect#77]
How can I get a live view card on my panel?

**Comment by thomas70** [comment]
use "camera_view: live" in the card

**Comment by timmillwood** [comment]
Yeh, have that @thomas70 and it only updates every 10 seconds.

**Comment by briis** [comment]
Have you enabled the RTSP stream, as described in the README.md?

> RTSP Stream Select each camera under the CAMERAS tab, click on the camera and you will get a menu on the right side. Click the MANAGE button and there will be a menu like the picture below. (If you can't see the same picture click the + sign to the right of RTSP). Make sure that at least one of the streams is set to on. It does not matter which one, or if you select more than one, the integration will pick the one with the highest resolution.

**Comment by timmillwood** [comment]
🤦🏼‍♂️ that was it, I was sure I'd done that ages ago.

**Comment by briis** [comment]
Little thing - big impact. Glad it works.
