### ISSUE TITLE
After v0.5 I have 3 camera

### ISSUE THREAD

**Issue by timmillwood** [briis/unifiprotect#78]
I now have 3 camera entities for my one camera, only the 3rd works.

How do I remove the other two and rename the third to just the camera name?

**Comment by briis** [comment]
If you go to the *Entities* section under the *Configuration* tab, you should see a couple of cameras which are unavaliable. Maybe also some sensors, switches etc. Select all these by clicking the box on the left, and then press *Remove Selected* in the upper right corner.

After this, you can click on the remaining Camera and change the EntityID to rename it.

**Comment by timmillwood** [comment]
Thanks for the tips!
