### ISSUE TITLE
Can't configurate  Unifi Protect I

### ISSUE THREAD

**Issue by 4umedia** [briis/unifiprotect#79]
After installation in the HACS store, I restarted HA. But when I go to tge Integrations page inside the configuration panel I can't add my CloudKey+

In other words where can I config Unifi Protect?

**Comment by 4umedia** [comment]
Found it

**Comment by gohassgo** [comment]
> Found it

Where? I'm not seeing it either... Tried reinstalling, no luck...

**Comment by briis** [comment]
When this happens, it is typical a browser caching problem. Try Force Refresh your browser, and go to the *Configuration* Tab and then *Integrations* to see if it does not show up.
And remember that you have to restart Home Assistant after installing an Integration.

**Comment by gohassgo** [comment]
> Try Force Refresh your browser

That did it... Had to force refresh on the Integrations page. Thanks!
