### ISSUE TITLE
Cameras show in Recording state all the time

### ISSUE THREAD

**Issue by biiiink** [briis/unifiprotect#81]
I have 5 cameras set to only record motion.  However, in HA, they are all showing as recording, all the time.  Not sure how to fix this

**Comment by briis** [comment]
Are you saying that if you go to the Unifi Protect App, the Cameras are set to Record only Motion, but when you go to the Unifi Protect Integration in Home Assistant the Switch for Always recording is turned on, and the sensors say Always?

What version of Home Assistant and Unifi Protect are you running?

**Comment by biiiink** [comment]
Sorry.  I should have been more clear.  All of the cameras are set to Record motion only in the Protect App, and in Home Assistant ("Record Motion" switches are all on, and the "Record Always" switches are all off). If i toggle the switches the change is reflected in the protect app, but the camera's status in HA always says "Recording".  I've included some screenshots
![Screen Shot 2020-06-12 at 2 10 58 PM](https://user-images.githubusercontent.com/1641304/84542616-0f113500-acb7-11ea-81ac-19be2424c6d6.png)
![Screen Shot 2020-06-12 at 2 11 17 PM](https://user-images.githubusercontent.com/1641304/84542618-10426200-acb7-11ea-8025-604ae88f4238.png)



Im on HA version 0.111.1 (Just updated today) and Protect version 1.13.3

**Comment by briis** [comment]
Got it. That is not an error, this is how the Home Assistant Camera Entity is designed. The Camera can show either `idle` or `recording` as state. 
For most cameras this is fine, but as Unifi Protect can have 3 states: never, motion and always, I made the decision to set it to true if the value is different from *never*. So recording will be shown also for motion detection.
Does this explain it?

**Comment by briis** [comment]
I assume the explanation above closes this issue. Else please re-open.
