### ISSUE TITLE
Camera view broken

### ISSUE THREAD

**Issue by tborychowski** [briis/unifiprotect#84]
So this shows up in logs recently:
```
The unifiprotect platform for the camera integration does not support platform setup. Please remove it from your config.
```
and there's no video stream from cameras...

**Comment by briis** [comment]
This is usually caused when the previous integration was not completely cleared from the .yaml files. See also Issue #80 
Please go through your .yaml files and see if you still have references to `unifiprotect` in there.

**Comment by tborychowski** [comment]
That is correct.
I missed the info about the configuration changes.
Thanks very much and sorry for bothering you unnecessarily :-)
