### ISSUE TITLE
Camera Audio

### ISSUE THREAD

**Issue by m11rphy** [briis/unifiprotect#87]
Hi first I want to say thank you for your amazing working, without you I wouldn't have my UniFi protect in HomeKit so thank you so much. 

I wanted to ask a question if its possible to audio from the camera, I cant figure how tho do it?

**Comment by briis** [comment]
Hi,
Thank you, happy it ads value to you.
Unfortunately the Home Assistant Stream component is currently not supporting audio - The feed you get from UniFi Protect does contain Audio, but it cannot be played through HA right now.

**Comment by m11rphy** [comment]
Thank you for clarifying, so its actually a HA issue that prevents the audio?

**Comment by briis** [comment]
Yes. But it is not because there is something wrong with HA, it is because currently the component that is needed for Streaming does not support Audio.

**Comment by briis** [comment]
I will close this, as it is not a Unifi Protect issue.
