### ISSUE TITLE
Unifi cameras missing from Google integration

### ISSUE THREAD

**Issue by fribse** [briis/unifiprotect#89]
UDM Pro
G3 and G3 flex cameras
HA: 0.112.1
I have 5 cameras in the protect.
When I use the integration I can see the cameras show up under the integration, but not on the google cloud sync,
The integration:
![image](https://user-images.githubusercontent.com/13660621/86498268-628e1480-bd85-11ea-89be-a6fda387b971.png)
But it only shows the cameras Have and Facade which has RTSP activated.
Is that a requirement for them to show up in Google?

**Comment by fribse** [comment]
I just found out that google doesn't seem to be able to stream the camera's from unifi via HA at all.

**Comment by briis** [comment]
Hi,
Enabling the RTSP stream is a requirement for being able to get a live stream in to Home Assistant, as this is the only way the API allows us to get a live stream. (As documented in the README.md file).

I am not that familiar with how Google Home works, but once the RTSP stream is enabled, have a look at the [HA Cast function](https://www.home-assistant.io/blog/2019/08/06/home-assistant-cast/), that might help.

**Comment by briis** [comment]
I will close this now, as it is not an issue with this Integration.
