### ISSUE TITLE
Binary sensor per motion zone instead of per camera

### ISSUE THREAD

**Issue by scottt732** [briis/unifiprotect#90]
Would it be possible to get a binary sensor for each motion zone defined in Unifi Protect?  

I have 2 cameras with 2 zones each.  They all have different sensitivity levels.  I don't really care about one of them from an automation perspective (motion on the street in front of my house) but I do like having them in the events view in Unifi Protect.  I care about the other 3 independently from an automation perspective.

Right now I have:
- `binary_sensor.driveway_camera_motion`
- `binary_sensor.front_yard_camera_motion`

Really I'd like:
- ~~`binary_sensor.driveway_camera_motion`~~
   - `binary_sensor.driveway_motion`
   - `binary_sensor.patio_motion`

- ~~`binary_sensor.front_yard_camera_motion`~~
   - `binary_sensor.front_yard_motion`
   - `binary_sensor.street_motion`

**Comment by briis** [comment]
Hi Scott,
I honestly don't know at this point. I know I can read some Zone info, but I am not sure that the Event Log supplies zone when showing that motion is occurring. But let me run some tests, and see what is possible.

**Comment by briis** [comment]
Hi Scott,
Did some testing, and unfortunately this can not be done at this point in time, as the motion zone is not supplied in the API when a motion event occurs. Hopefully it will be some day, but not currently. You can get [more information here](https://community.home-assistant.io/t/custom-component-unifi-protect/158041/241), where another user had a similar request.
