### ISSUE TITLE
Recording and IR turning off after some time

### ISSUE THREAD

**Issue by Michsior14** [briis/unifiprotect#91]
I have set recording to `always` and IR to `on` in the Unifi Protect app, but after some time all my cameras change it's settings and disable recording and IR. I am not sure what is going on, but It never happened before I've used this integration. 
You can have a look on screenshot of changes in my logbook. I've tried to set it via HA, but it also ends up as disabled after few hours. Do you have any idea what might be wrong?

![Screenshot_20200711_220808](https://user-images.githubusercontent.com/1410035/87233290-54b04300-c3c6-11ea-8769-653ee2986a39.png)
![Screenshot_20200711_222101](https://user-images.githubusercontent.com/1410035/87233291-57ab3380-c3c6-11ea-800e-a7c5cae0446d.png)

**Comment by Michsior14** [comment]
Unfortunately this happens everyday all the time, for now I just removed the integration.

**Comment by briis** [comment]
Hi,
There is nothing in the programming that automatically switches between states on both recording and IR. Are you sure that you don't have an automation somewhere that does this?

**Comment by Michsior14** [comment]
I've rechecked once again after your comment and I think I found the reason - in one automation I had `switch.turn_off` for `entity_id: all`. Anyhow I made another automation that makes sure IR and Recording is always on.
