### ISSUE TITLE
Error retrieving data from Unifi Protect.

### ISSUE THREAD

**Issue by samuprofe** [briis/unifiprotect#94]
Hi,

First of all thank you for this component. I love UniFi Network and Protect plataform and I have install them at home.

When I install and try to configure ip, port, user and pass I get the next message: "Error retrieving data from Unifi Protect.". Any idea why? I have tried several times and confirmed IP, user, pass, etc. I have 4 cameras with RTSP actived

Cloud Key G2+
Controller 1.13.4
2xG3 and 2xG3 Flex Cameras
Home Assistant up to date over Raspberry 4

**Comment by briis** [comment]
Did you create a local user on your CloudKey with admin rights?

**Comment by jasonkelly214** [comment]
I'm also having this issue. I have a new unifi UNVR running protect. I created a local super admin account. I have the IP of the UNVR and the default 7443 port.

**Comment by briis** [comment]
For the UNVR you have to use port 443

**Comment by jasonkelly214** [comment]
> For the UNVR you have to use port 443

Great! solved for me!

**Comment by samuprofe** [comment]
> Did you create a local user on your CloudKey with admin rights?

I used the global admin user but It didn't work. Nevertheless I have created a new local user (with no online access) and great! It Works!!

Thanks a lot!
