### ISSUE TITLE
Ability to split scan interval for events between cameras and binary sensors

### ISSUE THREAD

**Issue by coomacheek** [briis/unifiprotect#96]
I've found with the doorbell I have to keep the "scan interval for events" option to the minimum value.  If set higher, I miss button press events on the doorbell.  For installations with a high number of cameras and a doorbell, would be nice to set two different polling intervals: cameras and doorbell, or just have the doorbell binary sensor always be set to the minimum.

**Comment by briis** [comment]
Thanks for the suggestion, and I just wish I could get my hands on a doorbell to play with. But never the less, I will look in to this, but it will require some rework of the IO module, so don't expect it tomorrow.

**Comment by briis** [comment]
There is now a new Beta Version 0.6.0 Beta 1 released via HACS. If you are on a UDMP or UNVR server, please try this version, as it uses Websockets for instant push instead of Pulling the Server.

**Comment by briis** [comment]
The release 0.6.3, that is coming out soon, is moved to pure Websockets, and as such there is now scanning anymore. Instead events are pushed as they occur. If you are on a CloudKey+ it will require you to upgrade to minimum V2.0.18 to get UnifiOS installed.

I will close this now.
