### ISSUE TITLE
Use WebSockets for events

### ISSUE THREAD

**Issue by adrum** [briis/unifiprotect#97]
Unifi Protect apparently exposes a WebSocket interface that would allow for real-time updates of events such as motion and doorbell button events. 

This was recently implemented by this library: https://github.com/hjdhjd/homebridge-unifi-protect2

It would be amazing if we could implement real-time events.

**Comment by briis** [comment]
Thanks for spotting this. Apparently the WebSocket support is only for UnifiOS devices, so UDMP and UNVR and not the CloudKey, but never the less, this looks very interesting. I will put it on the to-look-at list, and see if I can figure out a way to implement this. Anyone else who wants to take a shot at this, feel free to jump in.

**Comment by adrum** [comment]
@briis I've started work on this. I have the connection setup, just parsing the response now.

**Comment by briis** [comment]
Fantastic, I will wait for what you come up with. 
Thanks

**Comment by mcondren** [comment]
Is there any way this could be used to ‘insert’ a motion event flag? I have the rtsp streams from protect running into Frigate [https://github.com/blakeblackshear/frigate](url) for person detection. Would be awesome if when Home Assistant detected motion on these streams (either via frigate integration or built-in tensorflow integration) it could trigger a motion event in protect. This would make scrolling through the timeline to find a detection much easier as it highlights motion events.

**Comment by OmenWild** [comment]
> Is there any way this could be used to ‘insert’ a motion event flag?

Like +Infinity on this. I would love to let my desktop do person detection to trigger the motion event on the Unifi side. So. Many. Spider. Webs.

**Comment by briis** [comment]
Hi @mcondren and @OmenWild 
This sounds like an interesting use-case, but before I look at that, we need to get the WebSocket implementation done. @adrum, has done the initial work on the IO component, but at present it has not been implemented in the Integration itself. I am honestly not completely sure how to do that, so it might take a little while. But once it is done, I will look at your request.

**Comment by mcondren** [comment]
Thanks @briis
